// GENERATED FILE — DO NOT EDIT.
//
// Source:      extension-condition/overlay.css
// Regenerate:  node scripts/gen-extension-overlay-css.mjs
// Guarded by:  test/overlay-shadow.test.cjs (fails the build on drift)
//
// US-1884 (AC4): the overlay mounts in a shadow root, and a document stylesheet
// cannot cross that boundary — so the sheet ships as a string the content script
// adopts into the shadow tree itself. Edit the .css, then run the generator.

(function (root, factory) {
  var api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api; // node
  if (typeof root !== "undefined") root.GT_CC_CSS = api; // content-script world
})(typeof self !== "undefined" ? self : this, function () {
  return [
    "/* GradeThread Condition Check — injected overlay styles (US-1755)",
    " *",
    " * THIS FILE IS THE AUTHORED SOURCE, NOT A SHIPPED ASSET (US-1884 AC4).",
    " *",
    " * The overlay mounts inside a SHADOW ROOT (content/overlay-host.js), and a",
    " * document stylesheet cannot cross that boundary — which is precisely why the",
    " * shadow root hardens us against a marketplace's CSS. So this sheet is compiled",
    " * into content/overlay-css.js and adopted into the shadow tree by the content",
    " * script itself. Edit here, then run:",
    " *",
    " *     node scripts/gen-extension-overlay-css.mjs",
    " *",
    " * (test/overlay-shadow.test.cjs fails the build if you forget.)",
    " *",
    " * Everything below therefore lives inside the shadow root, where the page's CSS",
    " * cannot reach it. Positioning, width and stacking are NOT here: they belong to",
    " * the host element, which is the one node the page can still select, so they are",
    " * inline `!important` declarations in overlay-host.js (OVERLAY_HOST_STYLE) —",
    " * the top of the author cascade, which no page rule can outrank. */",
    "",
    "/* US-2622: the card is a COLUMN inside a height-capped host, so its two parts",
    "   have different jobs. The header must always be on screen (it carries the only",
    "   two controls), and the report, whatever length the endpoint returns, has to",
    "   absorb the difference by scrolling. `min-height: 0` is what allows that: a",
    "   flex item refuses to shrink below its content without it, and the card would",
    "   overflow the host's cap exactly as it did before the cap existed. */",
    "#gt-cc-overlay.gt-cc-root {",
    "  all: initial;",
    "  display: flex;",
    "  flex-direction: column;",
    "  min-height: 0;",
    "  width: 100%;",
    "  box-sizing: border-box; /* `all: initial` reset it; the 1px border must fit */",
    "  font-family: Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;",
    "  color: #1a1a2e;",
    "  background: #ffffff;",
    "  border: 1px solid #e6e6ef;",
    "  border-radius: 14px;",
    "  box-shadow: 0 12px 32px rgba(15, 52, 96, 0.22);",
    "  overflow: hidden;",
    "}",
    "",
    "#gt-cc-overlay .gt-cc-head {",
    "  flex: 0 0 auto; /* never shrinks: it carries collapse and close */",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 8px;",
    "  padding: 10px 12px;",
    "  background: #0f3460;",
    "  color: #ffffff;",
    "}",
    "#gt-cc-overlay .gt-cc-brand {",
    "  font-weight: 700;",
    "  font-size: 13px;",
    "  letter-spacing: 0.2px;",
    "}",
    "#gt-cc-overlay .gt-cc-badge {",
    "  font-size: 10px;",
    "  text-transform: uppercase;",
    "  letter-spacing: 0.6px;",
    "  color: #cfe0ff;",
    "}",
    "/* US-2622: both header controls, sized as touch targets rather than as 18px of",
    "   glyph. The overlay runs on phone browsers too, where a 0-by-4px hit area on a",
    "   dismiss control is the difference between closing it and giving up. */",
    "#gt-cc-overlay .gt-cc-close,",
    "#gt-cc-overlay .gt-cc-collapse {",
    "  all: unset;",
    "  box-sizing: border-box;",
    "  cursor: pointer;",
    "  font-size: 16px;",
    "  line-height: 1;",
    "  color: #cfe0ff;",
    "  min-width: 28px;",
    "  padding: 6px 4px;",
    "  border-radius: 8px;",
    "  text-align: center;",
    "}",
    "#gt-cc-overlay .gt-cc-collapse { margin-left: auto; }",
    "#gt-cc-overlay .gt-cc-close { font-size: 18px; }",
    "#gt-cc-overlay .gt-cc-close:hover,",
    "#gt-cc-overlay .gt-cc-collapse:hover { color: #ffffff; background: rgba(255, 255, 255, 0.14); }",
    "#gt-cc-overlay .gt-cc-close:focus-visible,",
    "#gt-cc-overlay .gt-cc-collapse:focus-visible { outline: 2px solid #e94560; outline-offset: 1px; }",
    "",
    "/* US-2622: the scroll region. Everything above and below it is fixed-size, so",
    "   this is where a report of any length is absorbed.",
    "",
    "   `overscroll-behavior: contain` stops a flick that reaches the end of the",
    "   report from continuing into the marketplace's own page, which on a phone",
    "   reads as the overlay having thrown the shopper somewhere else. */",
    "#gt-cc-overlay .gt-cc-body {",
    "  flex: 1 1 auto;",
    "  min-height: 0;",
    "  overflow-y: auto;",
    "  overflow-x: hidden;",
    "  overscroll-behavior: contain;",
    "  -webkit-overflow-scrolling: touch;",
    "  scrollbar-width: thin;",
    "  scrollbar-color: #c3c3d2 transparent;",
    "  padding: 14px 14px 16px;",
    "  display: flex;",
    "  flex-direction: column;",
    "  gap: 10px;",
    "  /* Listing titles and seller handles arrive unsegmented and arbitrarily long;",
    "     one of them must never push the card sideways. */",
    "  overflow-wrap: break-word;",
    "}",
    "#gt-cc-overlay .gt-cc-body:focus-visible { outline: 2px solid #e94560; outline-offset: -2px; }",
    "",
    "/* Collapsed: the header alone, parked in the corner. The read is still there,",
    "   one click away, which is the difference between this and closing it. */",
    "#gt-cc-overlay.gt-cc-collapsed .gt-cc-body { display: none; }",
    "#gt-cc-overlay .gt-cc-lead {",
    "  margin: 0;",
    "  font-size: 13px;",
    "  line-height: 1.4;",
    "  color: #33334d;",
    "}",
    "",
    "#gt-cc-overlay .gt-cc-cta {",
    "  all: unset;",
    "  cursor: pointer;",
    "  text-align: center;",
    "  background: #e94560;",
    "  color: #ffffff;",
    "  font-weight: 600;",
    "  font-size: 13px;",
    "  padding: 10px 14px;",
    "  border-radius: 10px;",
    "}",
    "#gt-cc-overlay .gt-cc-cta:hover { background: #d43a53; }",
    "",
    "#gt-cc-overlay .gt-cc-secondary {",
    "  all: unset;",
    "  cursor: pointer;",
    "  text-align: center;",
    "  color: #0f3460;",
    "  font-weight: 600;",
    "  font-size: 12px;",
    "  padding: 6px;",
    "}",
    "#gt-cc-overlay .gt-cc-secondary:hover { text-decoration: underline; }",
    "",
    "#gt-cc-overlay .gt-cc-spin {",
    "  width: 28px;",
    "  height: 28px;",
    "  border-radius: 50%;",
    "  border: 4px solid #e6e6ef;",
    "  border-top-color: #0f3460;",
    "  animation: gt-cc-spin 0.8s linear infinite;",
    "  margin: 4px auto 0;",
    "}",
    "@keyframes gt-cc-spin { to { transform: rotate(360deg); } }",
    "",
    "#gt-cc-overlay .gt-cc-scorewrap {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 14px;",
    "}",
    "#gt-cc-overlay .gt-cc-score {",
    "  flex: 0 0 auto;",
    "  width: 58px;",
    "  height: 58px;",
    "  border-radius: 50%;",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  font-size: 22px;",
    "  font-weight: 700;",
    "  color: #ffffff;",
    "}",
    "#gt-cc-overlay .gt-cc-s-excellent { background: #1f9d55; }",
    "#gt-cc-overlay .gt-cc-s-good { background: #3a9d5d; }",
    "#gt-cc-overlay .gt-cc-s-fair { background: #d19a1e; }",
    "#gt-cc-overlay .gt-cc-s-poor { background: #d97a2b; }",
    "#gt-cc-overlay .gt-cc-s-bad { background: #e94560; }",
    "#gt-cc-overlay .gt-cc-meta { display: flex; flex-direction: column; gap: 3px; }",
    "#gt-cc-overlay .gt-cc-tier {",
    "  font-size: 15px;",
    "  font-weight: 700;",
    "  color: #0f3460;",
    "}",
    "#gt-cc-overlay .gt-cc-conf { font-size: 12px; color: #6b6b80; }",
    "",
    "#gt-cc-overlay .gt-cc-note {",
    "  margin: 0;",
    "  font-size: 12px;",
    "  line-height: 1.4;",
    "  color: #a4462d;",
    "  background: #fdf0ea;",
    "  border-radius: 8px;",
    "  padding: 8px 10px;",
    "}",
    "#gt-cc-overlay .gt-cc-saved {",
    "  margin: 0;",
    "  font-size: 11px;",
    "  line-height: 1.4;",
    "  color: #3f6b52;",
    "  background: #eef6f0;",
    "  border-radius: 8px;",
    "  padding: 6px 10px;",
    "}",
    "#gt-cc-overlay .gt-cc-disclaimer {",
    "  margin: 0;",
    "  font-size: 11px;",
    "  line-height: 1.4;",
    "  color: #8a8a9c;",
    "}",
    "#gt-cc-overlay .gt-cc-link {",
    "  color: #e94560;",
    "  font-weight: 600;",
    "  font-size: 13px;",
    "  text-decoration: none;",
    "}",
    "#gt-cc-overlay .gt-cc-link:hover { text-decoration: underline; }",
    "",
    "/* US-1884: condition factor breakdown bars + photo-coverage line. Fills reuse",
    "   the .gt-cc-s-* severity palette above. */",
    "#gt-cc-overlay .gt-cc-factors-h { margin: 4px 0 2px; font-size: 12px; font-weight: 700; color: #0f3460; }",
    "#gt-cc-overlay .gt-cc-factors { display: flex; flex-direction: column; gap: 5px; }",
    "#gt-cc-overlay .gt-cc-factor { display: flex; align-items: center; gap: 8px; }",
    "#gt-cc-overlay .gt-cc-factor-label { flex: 0 0 74px; font-size: 12px; color: #4a4a5e; }",
    "#gt-cc-overlay .gt-cc-factor-track { flex: 1 1 auto; height: 8px; border-radius: 4px; background: #ececf1; overflow: hidden; }",
    "#gt-cc-overlay .gt-cc-factor-fill { display: block; height: 100%; border-radius: 4px; min-width: 2px; }",
    "#gt-cc-overlay .gt-cc-factor-num { flex: 0 0 auto; width: 26px; text-align: right; font-size: 12px; font-weight: 700; color: #0f3460; font-variant-numeric: tabular-nums; }",
    "#gt-cc-overlay .gt-cc-photocount { margin: 2px 0 0; font-size: 11px; color: #6b6b80; }",
    "",
    "@media (prefers-color-scheme: dark) {",
    "  #gt-cc-overlay.gt-cc-root {",
    "    background: #1a1a2e;",
    "    color: #f5f5f5;",
    "    border-color: #2c2c44;",
    "  }",
    "  #gt-cc-overlay .gt-cc-body { scrollbar-color: #4a4a63 transparent; }",
    "  #gt-cc-overlay .gt-cc-lead { color: #d7d7e2; }",
    "  #gt-cc-overlay .gt-cc-tier { color: #cfe0ff; }",
    "  #gt-cc-overlay .gt-cc-disclaimer { color: #9a9ab0; }",
    "  /* US-1884: dark overrides for the factor breakdown + photo-coverage line. */",
    "  #gt-cc-overlay .gt-cc-factors-h { color: #cfe0ff; }",
    "  #gt-cc-overlay .gt-cc-factor-label { color: #c7c7d6; }",
    "  #gt-cc-overlay .gt-cc-factor-num { color: #eaeaf2; }",
    "  #gt-cc-overlay .gt-cc-factor-track { background: #2c2c44; }",
    "  #gt-cc-overlay .gt-cc-photocount { color: #9a9ab0; }",
    "}",
    "",
    "/* US-1834: claimed-vs-objective condition discrepancy signal. */",
    ".gt-cc-disc { margin: 6px 0; padding: 6px 8px; border-radius: 6px; font-size: 12px; font-weight: 600; }",
    ".gt-cc-disc-bad { background: #fde8e8; color: #b42318; }",
    ".gt-cc-disc-warn { background: #fef3c7; color: #92400e; }",
    ".gt-cc-disc-ok { background: #e7f6ec; color: #087443; }",
    "",
    "/* US-1837: coverage-gap photo request + actions. */",
    ".gt-cc-photos { margin: 4px 0 8px; padding-left: 18px; font-size: 12px; line-height: 1.5; }",
    ".gt-cc-actions { display: flex; flex-wrap: wrap; gap: 6px; margin: 6px 0; }",
    "",
    "/* ── generated: forced themes (US-3055), derived from the dark blocks above ── */",
    "/* forced dark: the media block's rules under [data-theme=\"dark\"] */",
    "#gt-cc-overlay.gt-cc-root[data-theme=\"dark\"] {",
    "  background: #1a1a2e;",
    "  color: #f5f5f5;",
    "  border-color: #2c2c44;",
    "}",
    "#gt-cc-overlay[data-theme=\"dark\"] .gt-cc-body {",
    "  scrollbar-color: #4a4a63 transparent;",
    "}",
    "#gt-cc-overlay[data-theme=\"dark\"] .gt-cc-lead {",
    "  color: #d7d7e2;",
    "}",
    "#gt-cc-overlay[data-theme=\"dark\"] .gt-cc-tier {",
    "  color: #cfe0ff;",
    "}",
    "#gt-cc-overlay[data-theme=\"dark\"] .gt-cc-disclaimer {",
    "  color: #9a9ab0;",
    "}",
    "#gt-cc-overlay[data-theme=\"dark\"] .gt-cc-factors-h {",
    "  color: #cfe0ff;",
    "}",
    "#gt-cc-overlay[data-theme=\"dark\"] .gt-cc-factor-label {",
    "  color: #c7c7d6;",
    "}",
    "#gt-cc-overlay[data-theme=\"dark\"] .gt-cc-factor-num {",
    "  color: #eaeaf2;",
    "}",
    "#gt-cc-overlay[data-theme=\"dark\"] .gt-cc-factor-track {",
    "  background: #2c2c44;",
    "}",
    "#gt-cc-overlay[data-theme=\"dark\"] .gt-cc-photocount {",
    "  color: #9a9ab0;",
    "}",
    "",
    "/* forced light: the base values back, under [data-theme=\"light\"], for every property the dark block touches */",
    "#gt-cc-overlay.gt-cc-root[data-theme=\"light\"] {",
    "  background: #ffffff;",
    "  color: #1a1a2e;",
    "  border-color: unset;",
    "}",
    "#gt-cc-overlay[data-theme=\"light\"] .gt-cc-body {",
    "  scrollbar-color: #c3c3d2 transparent;",
    "}",
    "#gt-cc-overlay[data-theme=\"light\"] .gt-cc-lead {",
    "  color: #33334d;",
    "}",
    "#gt-cc-overlay[data-theme=\"light\"] .gt-cc-tier {",
    "  color: #0f3460;",
    "}",
    "#gt-cc-overlay[data-theme=\"light\"] .gt-cc-disclaimer {",
    "  color: #8a8a9c;",
    "}",
    "#gt-cc-overlay[data-theme=\"light\"] .gt-cc-factors-h {",
    "  color: #0f3460;",
    "}",
    "#gt-cc-overlay[data-theme=\"light\"] .gt-cc-factor-label {",
    "  color: #4a4a5e;",
    "}",
    "#gt-cc-overlay[data-theme=\"light\"] .gt-cc-factor-num {",
    "  color: #0f3460;",
    "}",
    "#gt-cc-overlay[data-theme=\"light\"] .gt-cc-factor-track {",
    "  background: #ececf1;",
    "}",
    "#gt-cc-overlay[data-theme=\"light\"] .gt-cc-photocount {",
    "  color: #6b6b80;",
    "}"
  ].join("\n");
});
