import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  cardUprightQuarter,
  distanceToSegment,
  lineWithinBounds,
  quarterInverseAffine,
  recenterLine,
  rotateHomographyQuarter,
  rotatedDims,
  rotatePointQuarter,
  translateLine,
  type Point,
  type Quarter,
} from "@/lib/measure-photo-geometry";

// US-2889 AC5: the shared fixture is replayed HERE too, not only on iOS.
//
// Without this file the fixture proves only that Swift agrees with a JSON file
// nobody checks. `assets/measure-card/quarter-turn-cases.json` is generated
// from this very module, so if it is ever regenerated by accident - or edited
// by hand, which its own header forbids - the iOS suite would happily go on
// agreeing with the new numbers and both platforms would drift together,
// silently, away from the behaviour US-2888's tests actually pin.
//
// So: iOS asserts against the fixture, and the fixture asserts against the
// reference. Regenerating after a real behaviour change makes THIS file pass
// and is a decision; regenerating to make a failure go away makes US-2888's
// own suite fail instead, which is where it should be caught.

const FIXTURE = resolve(process.cwd(), "assets/measure-card/quarter-turn-cases.json");

interface Fixture {
  source: string;
  counts: Record<string, number>;
  cases: {
    dims: Array<{ w: number; h: number; turns: number; expected: [number, number] }>;
    points: Array<{ w: number; h: number; turns: number; point: Point; expected: Point }>;
    inverseAffine: Array<{ w: number; h: number; turns: number; expected: number[] }>;
    homographies: Array<
      { label: string; w: number; h: number; turns: number; homography: number[]; expected: number[] }
    >;
    upright: Array<
      { label: string; w: number; h: number; applied: number; homography: number[]; expected: number }
    >;
    translate: Array<
      {
        label: string;
        w: number;
        h: number;
        e1: Point;
        e2: Point;
        dx: number;
        dy: number;
        expected: { e1: Point; e2: Point };
      }
    >;
    recenter: Array<
      {
        label: string;
        w: number;
        h: number;
        e1: Point;
        e2: Point;
        within: boolean;
        expected: { e1: Point; e2: Point };
      }
    >;
    segment: Array<
      {
        label: string;
        point: Point;
        e1: Point;
        e2: Point;
        expected: { distance: number; t: number };
      }
    >;
  };
}

const fixture: Fixture = JSON.parse(readFileSync(FIXTURE, "utf8"));
const q = (n: number) => (((n % 4) + 4) % 4) as Quarter;

describe("the shared quarter-turn fixture matches the reference it was generated from", () => {
  it("is present and populated", () => {
    // Guards the guard. An empty fixture makes every loop below a no-op, and a
    // no-op loop is indistinguishable from a passing one.
    expect(fixture.source).toBe("src/lib/measure-photo-geometry.ts");
    expect(fixture.cases.dims.length).toBeGreaterThan(8);
    expect(fixture.cases.points.length).toBeGreaterThan(50);
    expect(fixture.cases.inverseAffine.length).toBeGreaterThan(8);
    expect(fixture.cases.homographies.length).toBeGreaterThan(20);
    expect(fixture.cases.upright.length).toBeGreaterThan(20);
    expect(fixture.cases.translate.length).toBeGreaterThan(50);
    expect(fixture.cases.recenter.length).toBeGreaterThan(20);
    expect(fixture.cases.segment.length).toBeGreaterThan(20);
  });

  it("rotatedDims", () => {
    for (const c of fixture.cases.dims) {
      expect(rotatedDims(c.w, c.h, q(c.turns)), `${c.w}x${c.h} turn ${c.turns}`).toEqual(c.expected);
    }
  });

  it("rotatePointQuarter", () => {
    for (const c of fixture.cases.points) {
      expect(
        rotatePointQuarter(c.point, q(c.turns), c.w, c.h),
        `${JSON.stringify(c.point)} turn ${c.turns} in ${c.w}x${c.h}`,
      ).toEqual(c.expected);
    }
  });

  it("quarterInverseAffine", () => {
    for (const c of fixture.cases.inverseAffine) {
      expect(quarterInverseAffine(q(c.turns), c.w, c.h), `turn ${c.turns} in ${c.w}x${c.h}`)
        .toEqual(c.expected);
    }
  });

  it("rotateHomographyQuarter", () => {
    for (const c of fixture.cases.homographies) {
      const got = rotateHomographyQuarter(c.homography, q(c.turns), c.w, c.h);
      for (let i = 0; i < 9; i++) {
        expect(got[i], `${c.label} H[${i}] turn ${c.turns} in ${c.w}x${c.h}`)
          .toBeCloseTo(c.expected[i]!, 12);
      }
    }
  });

  it("cardUprightQuarter", () => {
    for (const c of fixture.cases.upright) {
      expect(
        cardUprightQuarter(c.homography),
        `${c.label} applied ${c.applied} in ${c.w}x${c.h}`,
      ).toBe(c.expected);
    }
  });

  it("lineWithinBounds", () => {
    for (const c of fixture.cases.recenter) {
      expect(lineWithinBounds(c.e1, c.e2, c.w, c.h), `${c.label} in ${c.w}x${c.h}`)
        .toBe(c.within);
    }
  });

  it("translateLine", () => {
    for (const c of fixture.cases.translate) {
      expect(
        translateLine(c.e1, c.e2, c.dx, c.dy, c.w, c.h),
        `${c.label} by ${c.dx},${c.dy} in ${c.w}x${c.h}`,
      ).toEqual(c.expected);
    }
  });

  it("recenterLine", () => {
    for (const c of fixture.cases.recenter) {
      expect(recenterLine(c.e1, c.e2, c.w, c.h), `${c.label} in ${c.w}x${c.h}`)
        .toEqual(c.expected);
    }
  });

  it("distanceToSegment", () => {
    for (const c of fixture.cases.segment) {
      const got = distanceToSegment(c.point, c.e1, c.e2);
      expect(got.distance, `${c.label} distance from ${JSON.stringify(c.point)}`)
        .toBeCloseTo(c.expected.distance, 12);
      expect(got.t, `${c.label} t from ${JSON.stringify(c.point)}`)
        .toBeCloseTo(c.expected.t, 12);
    }
  });
});

describe("the fixture covers the shapes a port gets wrong", () => {
  it("includes a SQUARE frame, where a wrong axis swap is invisible in the dimensions", () => {
    expect(fixture.cases.points.some((c) => c.w === c.h)).toBe(true);
  });

  it("includes points off both axes of symmetry, where a mirror cannot look correct", () => {
    const asymmetric = fixture.cases.points.some(
      (c) => c.point[0] !== c.w - c.point[0] && c.point[1] !== c.h - c.point[1],
    );
    expect(asymmetric).toBe(true);
  });

  it("includes a non-zero applied turn for the upright reading", () => {
    // The sign in cardUprightQuarter is the one a port most reliably flips, and
    // an all-zero set of applied turns would never notice.
    expect(fixture.cases.upright.some((c) => c.applied !== 0 && c.expected !== 0)).toBe(true);
  });

  it("includes a line LONGER than its frame, which is where clamping diverges", () => {
    // translateLine deliberately does not clamp when the window is empty:
    // clamping into an empty range freezes the line, the same dead end as the
    // off-screen endpoint. A port that clamps unconditionally passes every
    // ordinary case and fails only here, so this case has to exist.
    const oversized = fixture.cases.translate.some(
      (c) => Math.abs(c.e1[0] - c.e2[0]) > c.w || Math.abs(c.e1[1] - c.e2[1]) > c.h,
    );
    expect(oversized).toBe(true);
  });

  it("includes a DEGENERATE segment, where the distance math divides by zero", () => {
    expect(
      fixture.cases.segment.some((c) => c.e1[0] === c.e2[0] && c.e1[1] === c.e2[1]),
    ).toBe(true);
  });

  it("includes a line that is already inside, so recenter proves it is a no-op", () => {
    expect(fixture.cases.recenter.some((c) => c.within)).toBe(true);
  });
});
