// US-307: dynamic Open Graph image for a public blog post.
//
// /og/blog/:slug returns a 1200x630 PNG generated by Satori (workers-og) with
// the post's title + category + author. The blog SSR
// (functions/blog/[[path]].ts) points og:image / twitter:image at this URL.

import {
  fetchJson,
  UpstreamUnavailable,
  upstreamUnavailableResponse,
  type PagesEnv,
  type PublicPost,
  siteUrl,
} from "../../_shared/blog-render";
import {
  buildBlogOgHtml,
  brandedFallbackResponse,
} from "../../_shared/og-template";
import { headOf } from "../../_shared/head-of";
import { renderViaEdge } from "../../_shared/render-via-edge";

type Ctx = EventContext<PagesEnv, "slug", Record<string, unknown>>;

const OG_CACHE_CONTROL =
  "public, max-age=86400, s-maxage=86400, stale-while-revalidate=604800";

export const onRequestGet: PagesFunction<PagesEnv> = async (context: Ctx) => {
  const { params, env } = context;
  const slug = String(params.slug ?? "");
  if (!slug) return await fallbackImage(env);

  try {
    // US-2044: fetchJson now THROWS UpstreamUnavailable rather than returning
    // null when it could not reach the API — so a transient failure can never
    // again be reported to a crawler as "this page is gone".
    let data: { post: PublicPost } | null;
    try {
      data = await fetchJson<{ post: PublicPost }>(
      env,
      `/api/content/public/posts/${encodeURIComponent(slug)}`,
    );
    } catch (e) {
      if (e instanceof UpstreamUnavailable) return upstreamUnavailableResponse();
      throw e;
    }
    if (!data?.post) return await fallbackImage(env);
    const post = data.post;

    // product_focus → human label for the badge area on the OG card.
    const categoryLabel = post.product_focus === "flipdesk"
      ? "FlipDesk"
      : post.product_focus === "both"
      ? "GradeThread + FlipDesk"
      : "GradeThread";

    const publishedAt = post.published_at
      ? new Date(post.published_at).toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
        })
      : null;

    const html = buildBlogOgHtml({
      title: post.title,
      category: categoryLabel,
      authorName: post.author ?? null,
      publishedAt,
      heroImageUrl: post.hero_image_url,
    });

    // US-2619: rasterised on the Deno edge, not here. This endpoint returned
    // 200 with an empty body for real published posts, so every blog link
    // preview was blank; buffering made the throw catchable and it has served
    // the branded fallback ever since. The markup was never the problem — the
    // same string produces valid SVG in satori — so the raster moves and the
    // template stays here.
    return await renderViaEdge(env, {
      markup: html,
      width: 1200,
      height: 630,
      cacheControl: OG_CACHE_CONTROL,
      label: "og/blog",
    });
  } catch (err) {
    console.error("[og/blog] render failed:", err);
    return await fallbackImage(env);
  }
};

// US-2108 AC3: a blank preview is worse for click-through than a generic
// branded card. Delegates to the shared branded fallback, which drops to the
// transparent pixel only if the static asset is also unreachable.
function fallbackImage(env: PagesEnv): Promise<Response> {
  return brandedFallbackResponse(siteUrl(env));
}

// US-2620: HEAD answers with the GET's status and headers, no body.
export const onRequestHead = headOf(onRequestGet);
