// US-307: dynamic Open Graph image for a public blog post.
//
// /og/blog/:slug returns a 1200x630 PNG generated by Satori (workers-og) with
// the post's title + category + author. The blog SSR
// (functions/blog/[[path]].ts) points og:image / twitter:image at this URL.

import { ImageResponse } from "workers-og";
import {
  fetchJson,
  UpstreamUnavailable,
  upstreamUnavailableResponse,
  type PagesEnv,
  type PublicPost,
} from "../../_shared/blog-render";
import {
  buildBlogOgHtml,
  FALLBACK_PNG_BASE64,
} from "../../_shared/og-template";

type Ctx = EventContext<PagesEnv, "slug", Record<string, unknown>>;

const OG_CACHE_CONTROL =
  "public, max-age=86400, s-maxage=86400, stale-while-revalidate=604800";

export const onRequestGet: PagesFunction<PagesEnv> = async (context: Ctx) => {
  const { params, env } = context;
  const slug = String(params.slug ?? "");
  if (!slug) return fallbackImage();

  try {
    // US-2044: fetchJson now THROWS UpstreamUnavailable rather than returning
    // null when it could not reach the API — so a transient failure can never
    // again be reported to a crawler as "this page is gone".
    let data: { post: PublicPost } | null;
    try {
      data = await fetchJson<{ post: PublicPost }>(
      env,
      `/api/content/public/posts/${encodeURIComponent(slug)}`,
    );
    } catch (e) {
      if (e instanceof UpstreamUnavailable) return upstreamUnavailableResponse();
      throw e;
    }
    if (!data?.post) return fallbackImage();
    const post = data.post;

    // product_focus → human label for the badge area on the OG card.
    const categoryLabel = post.product_focus === "flipdesk"
      ? "FlipDesk"
      : post.product_focus === "both"
      ? "GradeThread + FlipDesk"
      : "GradeThread";

    const publishedAt = post.published_at
      ? new Date(post.published_at).toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
        })
      : null;

    const html = buildBlogOgHtml({
      title: post.title,
      category: categoryLabel,
      authorName: post.author ?? null,
      publishedAt,
      heroImageUrl: post.hero_image_url,
    });

    return new ImageResponse(html, {
      width: 1200,
      height: 630,
      headers: {
        "Cache-Control": OG_CACHE_CONTROL,
        "Content-Type": "image/png",
      },
    });
  } catch (err) {
    console.error("[og/blog] render failed:", err);
    return fallbackImage();
  }
};

function fallbackImage(): Response {
  const bytes = Uint8Array.from(atob(FALLBACK_PNG_BASE64), (c) => c.charCodeAt(0));
  return new Response(bytes, {
    status: 200,
    headers: {
      "Content-Type": "image/png",
      "Cache-Control": "public, max-age=300",
    },
  });
}
