// GENERATED FILE — DO NOT EDIT.
//
// Source:      extension-unified/research/overlay.css
// Regenerate:  node scripts/gen-extension-overlay-css.mjs
// Guarded by:  test/overlay-shadow.test.cjs (fails the build on drift)
//
// US-1884 (AC4): the overlay mounts in a shadow root, and a document stylesheet
// cannot cross that boundary — so the sheet ships as a string the content script
// adopts into the shadow tree itself. Edit the .css, then run the generator.

(function (root, factory) {
  var api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api; // node
  if (typeof root !== "undefined") root.GT_CC_CSS = api; // content-script world
})(typeof self !== "undefined" ? self : this, function () {
  return [
    "/* GradeThread Condition Check — injected overlay styles (US-1755)",
    " *",
    " * THIS FILE IS THE AUTHORED SOURCE, NOT A SHIPPED ASSET (US-1884 AC4).",
    " *",
    " * The overlay and the scan badges each mount inside a SHADOW ROOT",
    " * (research/overlay-host.js), and a document stylesheet cannot cross that",
    " * boundary — which is precisely why the shadow root hardens us against a",
    " * marketplace's CSS. So this sheet is compiled into research/overlay-css.js and",
    " * adopted into each shadow tree by the content script itself. Edit here, then",
    " * run:",
    " *",
    " *     node scripts/gen-extension-overlay-css.mjs",
    " *",
    " * (test/overlay-shadow.test.cjs fails the build if you forget.)",
    " *",
    " * Everything below therefore lives inside a shadow root, where the page's CSS",
    " * cannot reach it. Positioning, width and stacking are NOT here: they belong to",
    " * the host element, which is the one node the page can still select, so they are",
    " * inline `!important` declarations in overlay-host.js (OVERLAY_HOST_STYLE /",
    " * BADGE_HOST_STYLE) — the top of the author cascade, which no page rule can",
    " * outrank. */",
    "",
    "#gt-cc-overlay.gt-cc-root {",
    "  all: initial;",
    "  display: block;",
    "  width: 100%;",
    "  box-sizing: border-box; /* `all: initial` reset it; the 1px border must fit */",
    "  font-family: Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;",
    "  color: #1a1a2e;",
    "  background: #ffffff;",
    "  border: 1px solid #e6e6ef;",
    "  border-radius: 14px;",
    "  box-shadow: 0 12px 32px rgba(15, 52, 96, 0.22);",
    "  overflow: hidden;",
    "}",
    "",
    "#gt-cc-overlay .gt-cc-head {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 8px;",
    "  padding: 10px 12px;",
    "  background: #0f3460;",
    "  color: #ffffff;",
    "}",
    "#gt-cc-overlay .gt-cc-brand {",
    "  font-weight: 700;",
    "  font-size: 13px;",
    "  letter-spacing: 0.2px;",
    "}",
    "#gt-cc-overlay .gt-cc-badge {",
    "  font-size: 10px;",
    "  text-transform: uppercase;",
    "  letter-spacing: 0.6px;",
    "  color: #cfe0ff;",
    "}",
    "#gt-cc-overlay .gt-cc-close {",
    "  all: unset;",
    "  cursor: pointer;",
    "  margin-left: auto;",
    "  font-size: 18px;",
    "  line-height: 1;",
    "  color: #cfe0ff;",
    "  padding: 0 4px;",
    "}",
    "#gt-cc-overlay .gt-cc-close:hover { color: #ffffff; }",
    "",
    "#gt-cc-overlay .gt-cc-body {",
    "  padding: 14px 14px 16px;",
    "  display: flex;",
    "  flex-direction: column;",
    "  gap: 10px;",
    "}",
    "#gt-cc-overlay .gt-cc-lead {",
    "  margin: 0;",
    "  font-size: 13px;",
    "  line-height: 1.4;",
    "  color: #33334d;",
    "}",
    "",
    "#gt-cc-overlay .gt-cc-cta {",
    "  all: unset;",
    "  cursor: pointer;",
    "  text-align: center;",
    "  background: #e94560;",
    "  color: #ffffff;",
    "  font-weight: 600;",
    "  font-size: 13px;",
    "  padding: 10px 14px;",
    "  border-radius: 10px;",
    "}",
    "#gt-cc-overlay .gt-cc-cta:hover { background: #d43a53; }",
    "",
    "#gt-cc-overlay .gt-cc-secondary {",
    "  all: unset;",
    "  cursor: pointer;",
    "  text-align: center;",
    "  color: #0f3460;",
    "  font-weight: 600;",
    "  font-size: 12px;",
    "  padding: 6px;",
    "}",
    "#gt-cc-overlay .gt-cc-secondary:hover { text-decoration: underline; }",
    "",
    "#gt-cc-overlay .gt-cc-spin {",
    "  width: 28px;",
    "  height: 28px;",
    "  border-radius: 50%;",
    "  border: 4px solid #e6e6ef;",
    "  border-top-color: #0f3460;",
    "  animation: gt-cc-spin 0.8s linear infinite;",
    "  margin: 4px auto 0;",
    "}",
    "@keyframes gt-cc-spin { to { transform: rotate(360deg); } }",
    "",
    "#gt-cc-overlay .gt-cc-scorewrap {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 14px;",
    "}",
    "#gt-cc-overlay .gt-cc-score {",
    "  flex: 0 0 auto;",
    "  width: 58px;",
    "  height: 58px;",
    "  border-radius: 50%;",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  font-size: 22px;",
    "  font-weight: 700;",
    "  color: #ffffff;",
    "}",
    "#gt-cc-overlay .gt-cc-s-excellent { background: #1f9d55; }",
    "#gt-cc-overlay .gt-cc-s-good { background: #3a9d5d; }",
    "#gt-cc-overlay .gt-cc-s-fair { background: #d19a1e; }",
    "#gt-cc-overlay .gt-cc-s-poor { background: #d97a2b; }",
    "#gt-cc-overlay .gt-cc-s-bad { background: #e94560; }",
    "#gt-cc-overlay .gt-cc-meta { display: flex; flex-direction: column; gap: 3px; }",
    "#gt-cc-overlay .gt-cc-tier {",
    "  font-size: 15px;",
    "  font-weight: 700;",
    "  color: #0f3460;",
    "}",
    "#gt-cc-overlay .gt-cc-conf { font-size: 12px; color: #6b6b80; }",
    "",
    "#gt-cc-overlay .gt-cc-note {",
    "  margin: 0;",
    "  font-size: 12px;",
    "  line-height: 1.4;",
    "  color: #a4462d;",
    "  background: #fdf0ea;",
    "  border-radius: 8px;",
    "  padding: 8px 10px;",
    "}",
    "#gt-cc-overlay .gt-cc-saved {",
    "  margin: 0;",
    "  font-size: 11px;",
    "  line-height: 1.4;",
    "  color: #3f6b52;",
    "  background: #eef6f0;",
    "  border-radius: 8px;",
    "  padding: 6px 10px;",
    "}",
    "#gt-cc-overlay .gt-cc-disclaimer {",
    "  margin: 0;",
    "  font-size: 11px;",
    "  line-height: 1.4;",
    "  color: #8a8a9c;",
    "}",
    "#gt-cc-overlay .gt-cc-link {",
    "  color: #e94560;",
    "  font-weight: 600;",
    "  font-size: 13px;",
    "  text-decoration: none;",
    "}",
    "#gt-cc-overlay .gt-cc-link:hover { text-decoration: underline; }",
    "",
    "/* US-1884: condition factor breakdown bars + photo-coverage line. Fills reuse",
    "   the .gt-cc-s-* severity palette above. */",
    "#gt-cc-overlay .gt-cc-factors-h { margin: 4px 0 2px; font-size: 12px; font-weight: 700; color: #0f3460; }",
    "#gt-cc-overlay .gt-cc-factors { display: flex; flex-direction: column; gap: 5px; }",
    "#gt-cc-overlay .gt-cc-factor { display: flex; align-items: center; gap: 8px; }",
    "#gt-cc-overlay .gt-cc-factor-label { flex: 0 0 74px; font-size: 12px; color: #4a4a5e; }",
    "#gt-cc-overlay .gt-cc-factor-track { flex: 1 1 auto; height: 8px; border-radius: 4px; background: #ececf1; overflow: hidden; }",
    "#gt-cc-overlay .gt-cc-factor-fill { display: block; height: 100%; border-radius: 4px; min-width: 2px; }",
    "#gt-cc-overlay .gt-cc-factor-num { flex: 0 0 auto; width: 26px; text-align: right; font-size: 12px; font-weight: 700; color: #0f3460; font-variant-numeric: tabular-nums; }",
    "#gt-cc-overlay .gt-cc-photocount { margin: 2px 0 0; font-size: 11px; color: #6b6b80; }",
    "",
    "@media (prefers-color-scheme: dark) {",
    "  #gt-cc-overlay.gt-cc-root {",
    "    background: #1a1a2e;",
    "    color: #f5f5f5;",
    "    border-color: #2c2c44;",
    "  }",
    "  #gt-cc-overlay .gt-cc-lead { color: #d7d7e2; }",
    "  #gt-cc-overlay .gt-cc-tier { color: #cfe0ff; }",
    "  #gt-cc-overlay .gt-cc-disclaimer { color: #9a9ab0; }",
    "  /* US-1884: dark overrides for the factor breakdown + photo-coverage line. */",
    "  #gt-cc-overlay .gt-cc-factors-h { color: #cfe0ff; }",
    "  #gt-cc-overlay .gt-cc-factor-label { color: #c7c7d6; }",
    "  #gt-cc-overlay .gt-cc-factor-num { color: #eaeaf2; }",
    "  #gt-cc-overlay .gt-cc-factor-track { background: #2c2c44; }",
    "  #gt-cc-overlay .gt-cc-photocount { color: #9a9ab0; }",
    "}",
    "",
    "/* US-1834: claimed-vs-objective condition discrepancy signal. */",
    ".gt-cc-disc { margin: 6px 0; padding: 6px 8px; border-radius: 6px; font-size: 12px; font-weight: 600; }",
    ".gt-cc-disc-bad { background: #fde8e8; color: #b42318; }",
    ".gt-cc-disc-warn { background: #fef3c7; color: #92400e; }",
    ".gt-cc-disc-ok { background: #e7f6ec; color: #087443; }",
    "",
    "/* US-1837: coverage-gap photo request + actions. */",
    ".gt-cc-photos { margin: 4px 0 8px; padding-left: 18px; font-size: 12px; line-height: 1.5; }",
    ".gt-cc-actions { display: flex; flex-wrap: wrap; gap: 6px; margin: 6px 0; }",
    "",
    "/* US-2237 — scan-mode badges on marketplace SEARCH result cards.",
    " *",
    " * These are NOT inside #gt-cc-overlay: they are appended into the marketplace's",
    " * own result tiles, so they sit in the middle of someone else's cascade. Since",
    " * US-1884 each row is its own SHADOW ROOT (createBadgeHost), so the page's rules",
    " * cannot reach these children at all; `all: initial` on the row remains because",
    " * INHERITED properties (font, colour, line-height) still pass through a shadow",
    " * boundary from the tile above it.",
    " *",
    " * Deliberately flat: one tint per chip, no border, no shadow. A badge that",
    " * competes visually with the marketplace's own price/condition text reads as an",
    " * ad, and the shopper trains themselves to ignore it. */",
    ".gt-cc-badge-row {",
    "  all: initial;",
    "  display: flex !important;",
    "  flex-wrap: wrap;",
    "  align-items: center;",
    "  gap: 4px;",
    "  margin: 6px 0 2px;",
    "  font-family: Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;",
    "  line-height: 1.4;",
    "}",
    "",
    ".gt-cc-badge-row .gt-cc-badge-chip {",
    "  display: inline-block;",
    "  padding: 2px 6px;",
    "  border-radius: 6px;",
    "  font-size: 11px;",
    "  font-weight: 600;",
    "  letter-spacing: 0;",
    "  white-space: nowrap;",
    "  background: #eef0f6;",
    "  color: #3d3d56;",
    "}",
    "",
    ".gt-cc-badge-row .gt-cc-b-good { background: #e7f6ec; color: #087443; }",
    ".gt-cc-badge-row .gt-cc-b-bad { background: #fde8e8; color: #b42318; }",
    ".gt-cc-badge-row .gt-cc-b-warn { background: #fef3c7; color: #92400e; }",
    ".gt-cc-badge-row .gt-cc-b-claim { background: #eef0f6; color: #3d3d56; }",
    ".gt-cc-badge-row .gt-cc-b-neutral { background: #eef0f6; color: #3d3d56; }",
    "",
    ".gt-cc-badge-row .gt-cc-badge-cta {",
    "  appearance: none;",
    "  border: 0;",
    "  padding: 2px 8px;",
    "  border-radius: 6px;",
    "  font-family: inherit;",
    "  font-size: 11px;",
    "  font-weight: 700;",
    "  cursor: pointer;",
    "  background: #0f3460;",
    "  color: #ffffff;",
    "}",
    "",
    ".gt-cc-badge-row .gt-cc-badge-cta:hover { background: #14427a; }",
    ".gt-cc-badge-row .gt-cc-badge-cta:focus-visible { outline: 2px solid #e94560; outline-offset: 2px; }",
    "",
    "@media (prefers-color-scheme: dark) {",
    "  .gt-cc-badge-row .gt-cc-badge-chip,",
    "  .gt-cc-badge-row .gt-cc-b-claim,",
    "  .gt-cc-badge-row .gt-cc-b-neutral { background: #2c2c44; color: #d7d7e2; }",
    "  .gt-cc-badge-row .gt-cc-b-good { background: #10331f; color: #8fe0ae; }",
    "  .gt-cc-badge-row .gt-cc-b-bad { background: #3a1618; color: #ffb4ae; }",
    "  .gt-cc-badge-row .gt-cc-b-warn { background: #3a2c10; color: #f5cd7a; }",
    "}",
    "",
    "/* US-2238 — the seller's Flip panel, appended inside the result overlay.",
    " *",
    " * Visually subordinate to the condition read on purpose: it is a second",
    " * question about the same listing, not a competing headline. One hairline rule",
    " * separates it, and elevation is declared once (by the overlay card itself). */",
    "#gt-cc-overlay .gt-cc-flip {",
    "  margin: 10px 0 0;",
    "  padding-top: 10px;",
    "  border-top: 1px solid #e6e6ef;",
    "}",
    "",
    "#gt-cc-overlay .gt-cc-flip-cta { margin: 0; }",
    "",
    "#gt-cc-overlay .gt-cc-verdict {",
    "  display: inline-block;",
    "  margin: 2px 0 6px;",
    "  padding: 3px 10px;",
    "  border-radius: 8px;",
    "  font-size: 13px;",
    "  font-weight: 700;",
    "}",
    "",
    "#gt-cc-overlay .gt-cc-v-buy { background: #e7f6ec; color: #087443; }",
    "#gt-cc-overlay .gt-cc-v-maybe { background: #fef3c7; color: #92400e; }",
    "#gt-cc-overlay .gt-cc-v-skip { background: #fde8e8; color: #b42318; }",
    "",
    "#gt-cc-overlay .gt-cc-flip-row {",
    "  display: flex;",
    "  align-items: baseline;",
    "  justify-content: space-between;",
    "  gap: 8px;",
    "  margin: 3px 0;",
    "  font-size: 12px;",
    "}",
    "",
    "#gt-cc-overlay .gt-cc-flip-val {",
    "  font-weight: 700;",
    "  color: #0f3460;",
    "  font-variant-numeric: tabular-nums;",
    "  white-space: nowrap;",
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    "  #gt-cc-overlay .gt-cc-flip { border-top-color: #2c2c44; }",
    "  #gt-cc-overlay .gt-cc-flip-val { color: #cfe0ff; }",
    "  #gt-cc-overlay .gt-cc-v-buy { background: #10331f; color: #8fe0ae; }",
    "  #gt-cc-overlay .gt-cc-v-maybe { background: #3a2c10; color: #f5cd7a; }",
    "  #gt-cc-overlay .gt-cc-v-skip { background: #3a1618; color: #ffb4ae; }",
    "}",
    "",
    "/* US-2239: the shopper's own history with this seller. Same weight as the other",
    " * notes — it is an observation they made, not a warning we are issuing. */",
    "#gt-cc-overlay .gt-cc-seller { font-style: normal; }"
  ].join("\n");
});
