// Public Condition Index (US-621/622).
//
// "The S&P 500 of secondhand condition" — public, crawlable pages showing the
// price-vs-grade curve for popular items. The Index shows ONLY a curated set of
// brand/category entries (CURATED_INDEX), each refreshed by a cron, so every
// public page has real comp depth. Curves with too little data are suppressed
// (US-622) — no false precision ever reaches the SEO surface.

import { supabaseAdmin } from "./supabase.ts";
import { requireJobSecret } from "./job-auth.ts";
import { acquireJobLock } from "./job-lock.ts";
import { isCertificateWithheld } from "./certificate-visibility.ts";
import {
  buildValueCurve,
  type CurvePoint,
  normalizeItemKey,
} from "./condition-curve.ts";
import { captureException, logEvent } from "./observability.ts";
import { describeValueBasis, type ValueBasis } from "./value-disclosure.ts";
import { getSetting } from "./system-settings.ts";

// Curated Index entries. categoryId is an eBay leaf/level the Browse comps come
// from; slug is the public URL. Keep this list tight + high-traffic.
export interface IndexSeed {
  slug: string;
  label: string;
  brand: string;
  categoryId: string;
  q?: string;
}

// Fallback catalog. The live catalog now lives in the condition_index_seeds
// table (US-845) so it can grow without a deploy; this array is used ONLY when
// the table is empty (fresh DB / migration not yet applied) so the Index never
// goes dark.
export const CURATED_INDEX: IndexSeed[] = [
  { slug: "patagonia-better-sweater", label: "Patagonia Better Sweater", brand: "Patagonia", categoryId: "11450", q: "Better Sweater" },
  { slug: "patagonia-jackets", label: "Patagonia Jackets", brand: "Patagonia", categoryId: "57988", q: "jacket" },
  { slug: "carhartt-jackets", label: "Carhartt Jackets", brand: "Carhartt", categoryId: "57988", q: "jacket" },
  { slug: "levis-501-jeans", label: "Levi's 501 Jeans", brand: "Levi's", categoryId: "11450", q: "501" },
  { slug: "nike-vintage-tees", label: "Nike Vintage Tees", brand: "Nike", categoryId: "15687", q: "vintage tee" },
  { slug: "the-north-face-fleece", label: "The North Face Fleece", brand: "The North Face", categoryId: "11450", q: "fleece" },
  { slug: "lululemon-leggings", label: "Lululemon Leggings", brand: "Lululemon", categoryId: "11450", q: "align leggings" },
  { slug: "ralph-lauren-polo", label: "Ralph Lauren Polo Shirts", brand: "Ralph Lauren", categoryId: "11450", q: "polo" },
];

interface IndexSeedRow {
  slug: string;
  label: string;
  brand: string;
  category_id: string;
  q: string | null;
}

/**
 * The live curated catalog (US-845). Reads enabled seeds from
 * condition_index_seeds, ordered by priority. Falls back to CURATED_INDEX when
 * the table is empty or unreachable so the Index never goes dark.
 */
export async function getIndexSeeds(): Promise<IndexSeed[]> {
  try {
    const { data, error } = await supabaseAdmin
      .from("condition_index_seeds")
      .select("slug, label, brand, category_id, q")
      .eq("enabled", true)
      .order("priority", { ascending: true })
      .order("label", { ascending: true });
    if (error) throw error;
    const rows = (data ?? []) as IndexSeedRow[];
    if (rows.length === 0) return CURATED_INDEX;
    return rows.map((r) => ({
      slug: r.slug,
      label: r.label,
      brand: r.brand,
      categoryId: r.category_id,
      q: r.q ?? undefined,
    }));
  } catch (err) {
    captureException(err, { level: "warn", route: "condition-index.seeds" });
    return CURATED_INDEX;
  }
}

// A curve needs at least this much total comp support to be PUBLISHED (US-622).
// Exported so the admin curation surface (US-846) can flag entries that fall
// below the publish threshold for pruning.
export const MIN_INDEX_TOTAL_SAMPLE = 8;

// US-847: a real, citable public certificate of this item used as an example
// internal link on the SEO detail page. Public (certificate_id != null) and
// not withheld; nothing per-tenant or private is exposed.
export interface IndexCurveExample {
  certificateId: string;
  title: string;
  overallScore: number;
  gradeTier: string;
}

export interface IndexCurveDto {
  slug: string;
  label: string;
  brand: string;
  categoryId: string;
  currency: string;
  // Only sufficient points are returned; insufficient grades are dropped so the
  // public chart never shows a fabricated number.
  points: Array<Pick<CurvePoint, "grade" | "lowCents" | "medianCents" | "highCents" | "sampleSize">>;
  totalSampleSize: number;
  refreshedAt: string;
  /**
   * US-2847: where these numbers came from.
   *
   * "seeded" = generated by filtering comps on the eBay conditionId a grade maps
   * to, which is a seller's own coarse label. "measured" = fitted from reads of
   * real listing photos. The page has to be able to say which, because the two
   * deserve different amounts of trust and only one of them is citable.
   */
  provenance: CurveProvenance;
  /**
   * US-2850: the provenance line, already worded, so the SPA renderer and the
   * Pages Function twin cannot say two different things about one curve.
   */
  disclosure: ValueBasis;
  // US-847: up to a few example public certificates of this item (may be []).
  examples?: IndexCurveExample[];
}

export interface IndexHubItem {
  slug: string;
  label: string;
  brand: string;
  currency: string;
  headlineMedianCents: number | null; // value at a grade-8 ("Excellent") anchor
  totalSampleSize: number;
  refreshedAt: string;
  provenance: CurveProvenance;
  disclosure: ValueBasis;
}

/** US-2847. A row that says nothing is a seeded row; the column defaults that way. */
export type CurveProvenance = "seeded" | "measured";

export function normalizeProvenance(value: unknown): CurveProvenance {
  return value === "measured" ? "measured" : "seeded";
}

interface CurveRow {
  slug: string;
  label: string | null;
  brand: string | null;
  category_id: string;
  currency: string;
  curve: CurvePoint[];
  total_sample_size: number;
  refreshed_at: string;
  provenance?: string | null;
  slope_cents_per_point?: number | string | null;
}

function toDto(row: CurveRow): IndexCurveDto {
  const provenance = normalizeProvenance(row.provenance);
  // US-622: publish only points with real comp support.
  const points = (row.curve ?? [])
    .filter((p) => p.sufficient && p.medianCents != null)
    .map((p) => ({
      grade: p.grade,
      lowCents: p.lowCents,
      medianCents: p.medianCents,
      highCents: p.highCents,
      sampleSize: p.sampleSize,
    }));
  const anchor = points.find((p) => p.grade === 8) ?? points[0] ?? null;
  return {
    slug: row.slug,
    label: row.label ?? row.brand ?? row.slug,
    brand: row.brand ?? "",
    categoryId: row.category_id,
    currency: row.currency,
    points,
    totalSampleSize: row.total_sample_size,
    refreshedAt: row.refreshed_at,
    provenance,
    // The headline number the page leads with is the grade-8 anchor, so the
    // slope is described against THAT median rather than against whichever
    // point a reader happens to hover.
    disclosure: describeValueBasis({
      source: provenance === "measured" ? "measured_curve" : "comp_median",
      sufficient: points.length > 0,
      sampleSize: row.total_sample_size,
      medianCents: anchor?.medianCents ?? null,
      slopeCentsPerPoint: numeric(row.slope_cents_per_point),
      currency: row.currency,
    }),
  };
}

/** numeric columns come back as strings from PostgREST often enough to matter. */
function numeric(v: number | string | null | undefined): number | null {
  if (typeof v === "number") return Number.isFinite(v) ? v : null;
  if (typeof v === "string" && v.trim() !== "") {
    const n = Number(v);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

const HUB_SELECT =
  "slug, label, brand, category_id, currency, curve, total_sample_size, refreshed_at, provenance, slope_cents_per_point";

/** Hub list: every published (sufficient) curated curve. */
export async function getIndexHub(): Promise<IndexHubItem[]> {
  const { data } = await supabaseAdmin
    .from("condition_price_curves")
    .select(HUB_SELECT)
    .not("slug", "is", null)
    .gte("total_sample_size", MIN_INDEX_TOTAL_SAMPLE)
    .order("total_sample_size", { ascending: false });

  return ((data ?? []) as CurveRow[]).map((row) => {
    const dto = toDto(row);
    const g8 = dto.points.find((p) => p.grade === 8) ?? dto.points.find((p) => p.medianCents != null);
    return {
      slug: dto.slug,
      label: dto.label,
      brand: dto.brand,
      currency: dto.currency,
      headlineMedianCents: g8?.medianCents ?? null,
      totalSampleSize: dto.totalSampleSize,
      refreshedAt: dto.refreshedAt,
      provenance: dto.provenance,
      disclosure: dto.disclosure,
    };
  });
}

// At most this many example certificates surface on a detail page (US-847).
const MAX_INDEX_EXAMPLES = 3;

interface ExampleCertRow {
  certificate_id: string | null;
  overall_score: number | string | null;
  grade_tier: string | null;
  submissions:
    | { title: string | null; brand: string | null; flagged: boolean | null; moderation_status: string | null }
    | Array<{ title: string | null; brand: string | null; flagged: boolean | null; moderation_status: string | null }>
    | null;
}

/**
 * Up to MAX_INDEX_EXAMPLES real PUBLIC certificates for `brand`, newest first
 * (US-847). Public-ness gate: certificate_id != null (US-268), and withheld
 * (flagged-but-unapproved) certs are dropped via the shared isCertificateWithheld
 * predicate so a suspect grade is never cited. Best-effort: any error → [] so the
 * detail page degrades gracefully (the internal-link block simply doesn't render).
 */
async function getExampleCertificates(brand: string): Promise<IndexCurveExample[]> {
  const b = brand.trim();
  if (!b) return [];
  try {
    const { data, error } = await supabaseAdmin
      .from("grade_reports")
      .select(
        "certificate_id, overall_score, grade_tier, created_at, submissions!inner(title, brand, flagged, moderation_status, status)",
      )
      .not("certificate_id", "is", null)
      // Only cite FINALIZED grades — a preliminary (pending-review) cert is not public.
      .in("review_status", ["approved", "modified"])
      .ilike("submissions.brand", b)
      .order("created_at", { ascending: false })
      .limit(12);
    if (error) throw error;
    const rows = (data ?? []) as ExampleCertRow[];
    const out: IndexCurveExample[] = [];
    for (const r of rows) {
      if (!r.certificate_id) continue;
      const sub = Array.isArray(r.submissions) ? r.submissions[0] : r.submissions;
      if (!sub || isCertificateWithheld(sub)) continue;
      out.push({
        certificateId: r.certificate_id,
        title: sub.title ?? "Graded garment",
        overallScore: Number(r.overall_score ?? 0),
        gradeTier: r.grade_tier ?? "",
      });
      if (out.length >= MAX_INDEX_EXAMPLES) break;
    }
    return out;
  } catch (err) {
    captureException(err, { level: "warn", route: "condition-index.examples" });
    return [];
  }
}

/** One curve by slug, or null if absent / suppressed for thin data (US-622). */
export async function getIndexCurveBySlug(slug: string): Promise<IndexCurveDto | null> {
  const { data } = await supabaseAdmin
    .from("condition_price_curves")
    .select(HUB_SELECT)
    .eq("slug", slug)
    .maybeSingle();
  if (!data) return null;
  const row = data as CurveRow;
  if (row.total_sample_size < MIN_INDEX_TOTAL_SAMPLE) return null;
  const dto = toDto(row);
  if (dto.points.length === 0) return null;
  dto.examples = await getExampleCertificates(dto.brand);
  return dto;
}


/**
 * Persist a SEEDED curve without ever clobbering a measured one (US-2847).
 *
 * Two statements rather than one upsert, because "insert, or update only when
 * the existing row is still seeded" is not something a single upsert can say.
 * The insert claims the key if it is free; the update then refreshes the row
 * only while it is still seeded, and matches nothing once it is measured.
 *
 * Deliberately `.eq()` twice rather than `.or()`: the self-hosted prod
 * PostgREST rejects logical operators on mutations while the local one accepts
 * them, so CI cannot catch that mistake (US-1552).
 */
export interface SeededCurveClient {
  from(table: string): {
    upsert(
      row: Record<string, unknown>,
      opts: { onConflict: string; ignoreDuplicates: boolean },
    ): Promise<{ error: { message: string } | null }>;
    update(row: Record<string, unknown>): {
      eq(column: string, value: unknown): {
        eq(column: string, value: unknown): {
          select(columns: string): Promise<{
            data: unknown[] | null;
            error: { message: string } | null;
          }>;
        };
      };
    };
  };
}

export async function persistSeededCurve(
  row: Record<string, unknown> & { item_key: string },
  // Injected so the "a measured row is left alone" case is a test rather than a
  // hope. Defaults to the real service-role client, so every caller is unchanged.
  client: SeededCurveClient = supabaseAdmin as unknown as SeededCurveClient,
): Promise<{ ok: boolean; skipped: boolean }> {
  const { error: insertErr } = await client
    .from("condition_price_curves")
    .upsert({ ...row, provenance: "seeded" }, {
      onConflict: "item_key",
      ignoreDuplicates: true,
    });
  if (insertErr) return { ok: false, skipped: false };

  const { data, error: updateErr } = await client
    .from("condition_price_curves")
    .update(row)
    .eq("item_key", row.item_key)
    .eq("provenance", "seeded")
    .select("item_key");
  if (updateErr) return { ok: false, skipped: false };

  return { ok: true, skipped: (data ?? []).length === 0 };
}

/**
 * Rebuild ONE curve from fresh comps and persist it. Returns true on success.
 * Shared by the cron (refreshConditionIndex) and the admin on-demand refresh
 * (US-846) so the build+persist logic lives in exactly one place.
 */
export async function refreshIndexSeed(seed: IndexSeed): Promise<boolean> {
  try {
    const curve = await buildValueCurve({ categoryId: seed.categoryId, brand: seed.brand, q: seed.q });
    const itemKey = normalizeItemKey({ categoryId: seed.categoryId, brand: seed.brand, q: seed.q });
    const result = await persistSeededCurve({
      item_key: itemKey,
      slug: seed.slug,
      label: seed.label,
      brand: seed.brand,
      category_id: seed.categoryId,
      query: seed.q ?? null,
      currency: curve.currency,
      curve: curve.points,
      total_sample_size: curve.totalSampleSize,
      refreshed_at: curve.refreshedAt,
    });
    if (!result.ok) {
      logEvent("warn", "condition-index.persist_failed", { slug: seed.slug });
      return false;
    }
    if (result.skipped) {
      // US-2847: this cell has been MEASURED. A generated curve must never
      // overwrite one fitted from real reads, so the refresh leaves it alone
      // and says so rather than reporting a write it did not make.
      logEvent("info", "condition-index.persist_skipped_measured", { slug: seed.slug });
    }
    return true;
  } catch (err) {
    captureException(err, { level: "warn", route: "condition-index.refresh", tags: { slug: seed.slug } });
    return false;
  }
}

// ── Comp-refresh scale + guardrails (US-1749) ────────────────────────
// The refresh cron previously rebuilt EVERY seed every run, so cost scaled
// linearly with the seed count (US-1746 grows this to thousands) with no ceiling.
// Now it is staleness-tiered (hot seeds refresh often, long-tail rarely) and
// bounded by an explicit per-run eBay call budget, with a kill-switch — all
// config-driven via the system_settings key `condition_index_refresh` (no
// migration: getSetting falls back to the defaults below when the key is unset).
export interface SeedRefreshConfig {
  /** Master kill-switch — false stops all comp fetching. */
  enabled: boolean;
  /** Per-run eBay Browse call budget (one call per seed refreshed). */
  maxSeedsPerRun: number;
  /** A "hot" (popular) seed is re-fetched when older than this many days. */
  hotDays: number;
  /** A long-tail seed is re-fetched when older than this many days. */
  coldDays: number;
  /** total_sample_size ≥ this ⇒ the seed is treated as hot. */
  hotSampleThreshold: number;
}

export const DEFAULT_SEED_REFRESH_CONFIG: SeedRefreshConfig = {
  enabled: true,
  maxSeedsPerRun: 20,
  hotDays: 1,
  coldDays: 7,
  hotSampleThreshold: 25,
};

export interface SeedState {
  /** Epoch ms of the last refresh, or null when never refreshed. */
  refreshedAtMs: number | null;
  totalSampleSize: number;
}

export interface SeedSelection {
  /** The budget-capped batch to refresh this run, oldest-first. */
  batch: IndexSeed[];
  /** Total seeds due for refresh (before the budget cap). */
  dueCount: number;
  /** Seeds skipped because their curve is still fresh for their tier. */
  freshCount: number;
  /** True when more seeds were due than the budget allowed (nothing silently lost — it's logged). */
  budgetCapped: boolean;
}

/**
 * Pick which seeds to refresh this run: a seed is due when it has never been
 * refreshed, or its curve is older than its tier's interval (hot vs long-tail by
 * comp depth). Due seeds are ordered oldest-first and truncated to the call
 * budget. PURE (takes nowMs) so the tiering + budgeting is unit-tested without eBay.
 */
export function selectDueSeeds(
  seeds: IndexSeed[],
  states: Map<string, SeedState>,
  config: SeedRefreshConfig,
  nowMs: number,
): SeedSelection {
  const due: Array<{ seed: IndexSeed; ageMs: number }> = [];
  let freshCount = 0;
  for (const seed of seeds) {
    const st = states.get(seed.slug);
    if (!st || st.refreshedAtMs == null) {
      due.push({ seed, ageMs: Infinity }); // never refreshed → maximally stale
      continue;
    }
    const ageMs = nowMs - st.refreshedAtMs;
    const isHot = st.totalSampleSize >= config.hotSampleThreshold;
    const intervalMs = (isHot ? config.hotDays : config.coldDays) * 86_400_000;
    if (ageMs >= intervalMs) due.push({ seed, ageMs });
    else freshCount += 1;
  }
  due.sort((a, b) => b.ageMs - a.ageMs); // oldest (incl. never-refreshed) first
  const cap = Math.max(0, Math.trunc(config.maxSeedsPerRun));
  const batch = due.slice(0, cap).map((d) => d.seed);
  return { batch, dueCount: due.length, freshCount, budgetCapped: due.length > batch.length };
}

/** Load each seed's current refresh state (last-refreshed + comp depth). */
async function loadSeedStates(seeds: IndexSeed[]): Promise<Map<string, SeedState>> {
  const map = new Map<string, SeedState>();
  const slugs = seeds.map((s) => s.slug);
  if (slugs.length === 0) return map;
  const { data } = await supabaseAdmin
    .from("condition_price_curves")
    .select("slug, refreshed_at, total_sample_size")
    .in("slug", slugs);
  for (const row of (data ?? []) as Array<{ slug: string; refreshed_at: string | null; total_sample_size: number }>) {
    map.set(row.slug, {
      refreshedAtMs: row.refreshed_at ? Date.parse(row.refreshed_at) : null,
      totalSampleSize: row.total_sample_size ?? 0,
    });
  }
  return map;
}

export interface RefreshResult {
  refreshed: number;
  failed: number;
  /** Seeds skipped because still fresh for their tier. */
  skippedFresh: number;
  /** Seeds that were due but deferred to a later run by the budget cap. */
  deferred: number;
  /** Refreshed seeds whose comp depth is below the public-display threshold. */
  droppedInsufficient: number;
  /** True when the kill-switch is off. */
  disabled?: boolean;
}

// Cron: staleness-tiered, budget-capped rebuild of the curated curves.
export async function refreshConditionIndex(nowMs = Date.now()): Promise<RefreshResult> {
  const config = await getSetting<SeedRefreshConfig>(
    "condition_index_refresh",
    DEFAULT_SEED_REFRESH_CONFIG,
  );
  if (!config.enabled) {
    logEvent("info", "condition-index.refresh.disabled", {});
    return { refreshed: 0, failed: 0, skippedFresh: 0, deferred: 0, droppedInsufficient: 0, disabled: true };
  }

  const seeds = await getIndexSeeds();
  const states = await loadSeedStates(seeds);
  const sel = selectDueSeeds(seeds, states, config, nowMs);

  let refreshed = 0;
  let failed = 0;
  for (const seed of sel.batch) {
    if (await refreshIndexSeed(seed)) refreshed += 1;
    else failed += 1;
  }

  // No silent truncation: re-read the batch's comp depth and log every seed that
  // landed below the public-display threshold (its page is suppressed, US-622).
  let droppedInsufficient = 0;
  if (sel.batch.length > 0) {
    const after = await loadSeedStates(sel.batch);
    const thin: string[] = [];
    for (const seed of sel.batch) {
      const st = after.get(seed.slug);
      if (st && st.totalSampleSize < MIN_INDEX_TOTAL_SAMPLE) thin.push(seed.slug);
    }
    droppedInsufficient = thin.length;
    if (thin.length > 0) {
      logEvent("info", "condition-index.refresh.insufficient_samples", { slugs: thin, count: thin.length });
    }
  }

  const deferred = sel.dueCount - sel.batch.length;
  logEvent("info", "condition-index.refresh", {
    refreshed,
    failed,
    skippedFresh: sel.freshCount,
    deferred,
    droppedInsufficient,
    budget: config.maxSeedsPerRun,
    budgetCapped: sel.budgetCapped,
  });
  return { refreshed, failed, skippedFresh: sel.freshCount, deferred, droppedInsufficient };
}

export async function handleConditionIndexRefreshCron(c: {
  req: { header: (name: string) => string | undefined };
  json: (body: unknown, status?: number) => Response;
}): Promise<Response> {
  if (!(await requireJobSecret(c))) {
    return c.json({ error: "Unauthorized" }, 401);
  }
  const lock = await acquireJobLock("condition-index-refresh", 600);
  if (!lock.acquired) {
    return c.json({ ok: true, skipped: true, reason: lock.reason });
  }
  try {
    const result = await refreshConditionIndex();
    return c.json({ ok: true, ...result });
  } catch (err) {
    captureException(err, { route: "condition-index.cron" });
    return c.json({ error: "Condition Index refresh failed" }, 500);
  } finally {
    await lock.release();
  }
}
