// US-870: per-platform social variant spec.
//
// Single source of truth (edge side) for the six networks the content engine
// fans out to: the canonical list, each network's character ceiling, the
// branded social-card aspect it should use (forward-looking label consumed by
// US-871/US-872), and the generation guidance the AI prompt injects so each
// variant matches that platform's length/tone/hashtag conventions.

export const SOCIAL_PLATFORMS = [
  "x",
  "linkedin",
  "facebook",
  "threads",
  "pinterest",
  "instagram",
] as const;

export type SocialPlatform = (typeof SOCIAL_PLATFORMS)[number];

export function isSocialPlatform(v: unknown): v is SocialPlatform {
  return typeof v === "string" &&
    (SOCIAL_PLATFORMS as readonly string[]).includes(v);
}

// Hard character ceilings. We truncate to these defensively after generation —
// a model that runs long shouldn't produce an un-postable variant.
export const PLATFORM_CHAR_LIMIT: Record<SocialPlatform, number> = {
  x: 280,
  linkedin: 3000,
  facebook: 5000,
  threads: 500,
  pinterest: 500,
  instagram: 2200,
};

// Which branded card aspect each platform should ship with. Labels only —
// the actual image is generated by US-871/US-872; we forward this so the
// webhook payload already names the right asset.
export const PLATFORM_IMAGE_FIELD: Record<SocialPlatform, string> = {
  x: "card_landscape", // 1.91:1
  linkedin: "card_landscape",
  facebook: "card_landscape",
  threads: "card_square", // 1:1
  pinterest: "pin_vertical", // 2:3
  instagram: "card_square",
};

export const PLATFORM_LABEL: Record<SocialPlatform, string> = {
  x: "X",
  linkedin: "LinkedIn",
  facebook: "Facebook",
  threads: "Threads",
  pinterest: "Pinterest",
  instagram: "Instagram",
};

// Per-platform generation guidance injected into the AI prompt. Each line is a
// hard convention for that network: length window, tone, hashtag/link handling.
export const PLATFORM_GENERATION_RULES: Record<SocialPlatform, string> = {
  x:
    "<=280 chars TOTAL including the link. One sharp thread-friendly hook. At most 1-2 hashtags. End with the CTA URL.",
  linkedin:
    "800-1500 chars, professional and insight-led. Short paragraphs separated by a blank line. End with 3-5 hashtags on their own line and the CTA URL.",
  facebook:
    "Conversational, 1-3 short paragraphs. Warm and plain-spoken; invite a reply with a light question. Include the CTA URL. 0-2 hashtags only.",
  threads:
    "<=500 chars, casual and conversational, like talking to other resellers. 1-2 hashtags max. Include the CTA URL.",
  pinterest:
    "Keyword-rich description <=500 chars that reads like a useful caption (front-load the searchable value). Describe the destination and include the CTA URL. 2-4 keyword hashtags.",
  instagram:
    "Caption with deliberate line breaks: hook on line 1, value in the middle, a clear CTA (note 'link in bio'). Put 5-10 grouped hashtags in a block at the very end.",
};

// Default enabled set when content_settings.social_platforms is missing/empty.
export const DEFAULT_ENABLED_PLATFORMS: SocialPlatform[] = [
  ...SOCIAL_PLATFORMS,
];

// Normalize an arbitrary enable-list (from settings) to a deduped, ordered,
// valid platform array. Falls back to all six when nothing valid is present.
export function normalizeEnabledPlatforms(input: unknown): SocialPlatform[] {
  if (!Array.isArray(input)) return [...DEFAULT_ENABLED_PLATFORMS];
  const seen = new Set<SocialPlatform>();
  for (const v of input) {
    if (isSocialPlatform(v)) seen.add(v);
  }
  if (seen.size === 0) return [...DEFAULT_ENABLED_PLATFORMS];
  // Preserve canonical order regardless of the stored order.
  return SOCIAL_PLATFORMS.filter((p) => seen.has(p));
}
