#!/usr/bin/env node
// make-catchup.mjs — generate a one-paste prod catch-up bundle for Supabase Studio.
//
// WHY: the edge boot guard (US-778, lib/schema-version.ts) refuses to start when
// prod's applied schema version is behind the version the edge build expects,
// crash-looping the site. We apply migrations to prod via the Studio SQL editor
// (no psql access), so recovery = paste every pending migration in order. This
// script builds that paste for you from the exact number in the boot log.
//
// USAGE:
//   npm run catchup -- 00256        # bundle every migration AFTER 00256
//   npm run catchup -- applied=00256 # same — paste the boot-log token verbatim
//   npm run catchup                  # no arg → prints how to find the number
//
// The "00256" is the `applied=NNNNN` value from the crash log:
//   [schema-version] DB is STALE: applied=00256, this build expects 00281.
//
// OUTPUT: scripts/prod-catchup-YYYY-MM-DD.sql  (+ copied to clipboard on Windows).
// Every migration is idempotent and self-records its version (US-1108), so the
// bundle is safe to re-run and advances latest_schema_migration() to the top.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const migrationsDir = join(repoRoot, "supabase", "migrations");

// --- parse the "from" version ------------------------------------------------
// Accept "00256", "256", or the whole "applied=00256" token. We take the first
// run of digits we see.
const rawArg = process.argv.slice(2).join(" ").trim();
if (!rawArg) {
  console.error(
    [
      "Usage: npm run catchup -- <applied-version>",
      "",
      "Find <applied-version> in the edge crash log line:",
      "  [schema-version] DB is STALE: applied=00256, this build expects 00281.",
      "                                        ^^^^^  use this number",
      "",
      "Then:  npm run catchup -- 00256",
    ].join("\n"),
  );
  process.exit(1);
}
const fromMatch = rawArg.match(/\d+/);
if (!fromMatch) {
  console.error(`Could not find a version number in argument: "${rawArg}"`);
  process.exit(1);
}
// Compare zero-padded prefixes LEXICALLY — identical to apply-prod-migrations.sh
// (`[[ "$prefix" > "$current" ]]`) and to the supabase_migrations ordering. This
// is what correctly treats legacy 6-digit prefixes (000355_, 000375_, …) as OLD:
// "000355" < "00256" as strings, even though 355 > 256 as numbers.
const fromVersion = fromMatch[0].padStart(5, "0");

// --- collect pending migrations ---------------------------------------------
const prefixOf = (name) => name.slice(0, name.indexOf("_"));

const pending = readdirSync(migrationsDir)
  .filter((f) => f.endsWith(".sql") && /^\d+_/.test(f))
  .filter((f) => prefixOf(f) > fromVersion)
  .sort();

if (pending.length === 0) {
  console.log(
    `Nothing pending — no migration files above ${fromVersion}. ` +
      `Prod is already current. (If the edge still crash-loops, redeploy it once.)`,
  );
  process.exit(0);
}

const topVersion = prefixOf(pending[pending.length - 1]);
const fromPadded = fromVersion;

// Local date (this runs on your machine, not the workflow sandbox) → YYYY-MM-DD.
const today = new Date().toISOString().slice(0, 10);
const outName = `prod-catchup-${today}.sql`;
const outPath = join(repoRoot, "scripts", outName);

// --- build the bundle --------------------------------------------------------
const rule =
  "-- ════════════════════════════════════════════════════════════════════════════";

const parts = [
  `-- ${outName}`,
  "--",
  "-- WHY: the edge boot guard (US-778, lib/schema-version.ts) is crash-looping:",
  `--   [schema-version] DB is STALE: applied=${fromPadded}, this build expects ${topVersion}.`,
  "--   Refusing to start.  → site down until prod reaches the expected version.",
  "--",
  `-- This bundles migrations ${prefixOf(pending[0])} → ${topVersion} VERBATIM (DDL + each file's`,
  "-- US-1108 self-record footer) so ONE paste both applies the schema AND advances",
  "-- latest_schema_migration() to the top. Every file is idempotent",
  "-- (IF NOT EXISTS / guarded enums / ON CONFLICT) → safe to re-run.",
  "--",
  "-- SOURCE OF TRUTH remains the individual migration files; this is a convenience",
  "-- bundle, regenerated by `npm run catchup`. Apply via Supabase Studio SQL editor.",
  "--",
  "-- ⚠️ Back up prod first (vault/10-ops/backups.md). Migrations are forward-only.",
  "--",
  `-- After running, the tail SELECT must report ${topVersion}; the next edge boot then`,
  `-- logs "[schema-version] OK — DB at ${topVersion} matches expected ${topVersion}".`,
  "",
];

for (const file of pending) {
  parts.push("", rule, `-- ${file}`, rule, "");
  parts.push(readFileSync(join(migrationsDir, file), "utf8").trimEnd(), "");
}

parts.push(
  "",
  rule,
  `-- VERIFY: must print ${topVersion}`,
  rule,
  "SELECT public.latest_schema_migration() AS now_at;",
  "",
);

const sql = parts.join("\n");
writeFileSync(outPath, sql, "utf8");

// --- copy to clipboard (best effort, Windows) --------------------------------
let copied = false;
if (process.platform === "win32") {
  try {
    const res = spawnSync("clip", { input: sql });
    copied = res.status === 0;
  } catch {
    copied = false;
  }
}

// --- report ------------------------------------------------------------------
console.log(
  [
    `Bundled ${pending.length} migration(s): ${prefixOf(pending[0])} → ${topVersion}`,
    `Wrote   scripts/${outName}`,
    copied
      ? "Copied  the SQL to your clipboard — paste it into the Supabase Studio SQL editor and run."
      : `Open    scripts/${outName} and paste its contents into the Supabase Studio SQL editor.`,
    "",
    `Then verify the final SELECT prints ${topVersion}, and the edge container boots clean.`,
  ].join("\n"),
);
