#!/usr/bin/env node
// US-2045: regenerate vault/00-index/INDEX.md (and per-folder MOCs) from note
// frontmatter.
//
// INDEX.md is the librarian. The whole retrieval design rests on an agent
// reading ONE page, following at most two links, and stopping — so the index has
// a hard 400-line cap (INDEX_LINE_CAP in vault-lint.mjs). That cap is the token
// budget for the entire knowledge surface, not a style preference. Uncapped, we
// would have rebuilt "grep 203 files" with extra ceremony.
//
// Generated content lives between <!-- vault-index:start --> and
// <!-- vault-index:end -->. Everything outside those markers is hand-written and
// is preserved verbatim — orientation prose is exactly the part a generator
// cannot produce.
//
// Usage:
//   node scripts/vault-index.mjs           # rewrite the generated regions
//   node scripts/vault-index.mjs --check   # exit 1 if they are stale (CI)
//
// MOC policy: a per-folder MOC is generated only once a folder carries
// MOC_THRESHOLD notes. Below that the index lists the folder's notes directly.
// Nine single-entry MOCs would add nine hops and nine graph hubs while telling a
// reader nothing the index did not already say — and US-2066 has to keep that
// graph legible.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { INDEX_LINE_CAP, loadNotes, ROOT_NOTE } from "./vault-lint.mjs";

export const START = "<!-- vault-index:start -->";
export const END = "<!-- vault-index:end -->";
export const MOC_THRESHOLD = 12;

export const FOLDER_LABELS = {
  "10-ops": "10-ops — operations and runbooks",
  "20-domain": "20-domain — grading, measurement, contracts",
  "30-platform": "30-platform — marketplace integration",
  "40-growth": "40-growth — SEO, content, distribution",
  "50-business": "50-business — pricing and economics",
  "60-decisions": "60-decisions — ADRs",
  "70-agent": "70-agent — how agents work here",
  "90-archive": "90-archive — historical snapshots",
  _meta: "Meta",
};

// The index entry for a note is its summary, or the first sentence of its body.
// A generator inventing prose here would be worse than a fallback: it would read
// as authored intent while being nothing of the kind.
export function summaryFor(note) {
  const s = note.fm?.summary;
  if (typeof s === "string" && s.trim()) return s.trim();
  const firstProse = note.body
    .split(/\r?\n/)
    .map((l) => l.trim())
    .find((l) => l && !l.startsWith("#") && !l.startsWith(">") && !l.startsWith("|") && !l.startsWith("-"));
  if (!firstProse) return "";
  const sentence = firstProse.split(/(?<=\.)\s/)[0];
  return sentence.replace(/\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]/g, "$1").trim();
}

// "vault/10-ops/x.md" -> "10-ops"; a note at the vault root (CONTRACT.md) has no
// folder, so it groups under _meta rather than under a heading named after its
// own filename.
export function folderOf(path) {
  const parts = path.split("/");
  return parts.length > 2 ? parts[1] : "_meta";
}

// Map<folder, notes[]>, excluding 00-index itself (INDEX and MOCs are the
// navigation layer, not destinations) and sorted for stable output.
export function groupByFolder(notes) {
  const groups = new Map();
  for (const [name, n] of notes) {
    const folder = folderOf(n.path);
    if (folder === "00-index") continue;
    if (!groups.has(folder)) groups.set(folder, []);
    groups.get(folder).push({ name, ...n });
  }
  for (const list of groups.values()) list.sort((a, b) => a.name.localeCompare(b.name));
  return new Map([...groups.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

function line(note) {
  const type = note.fm?.type ?? "?";
  const summary = summaryFor(note);
  return `- [[${note.name}]] — ${type}${summary ? ` — ${summary}` : ""}`;
}

export function renderIndexBody(notes, { mocThreshold = MOC_THRESHOLD } = {}) {
  const groups = groupByFolder(notes);
  const out = [];
  for (const [folder, list] of groups) {
    out.push(`## ${FOLDER_LABELS[folder] ?? folder}`, "");
    if (list.length >= mocThreshold) {
      const moc = mocNameFor(folder);
      out.push(`${list.length} notes — see [[${moc}]].`, "");
    } else {
      for (const n of list) out.push(line(n));
      out.push("");
    }
  }
  return out.join("\n").trimEnd();
}

export function mocNameFor(folder) {
  return `moc-${folder.replace(/^\d+-/, "")}`;
}

export function renderMoc(folder, list) {
  const label = FOLDER_LABELS[folder] ?? folder;
  return [
    "---",
    `title: ${label}`,
    "type: moc",
    "status: current",
    "source_of_truth: vault",
    "code_refs: []",
    `reviewed: ${new Date().toISOString().slice(0, 10)}`,
    "tags: [meta, moc]",
    `summary: Map of content for ${folder}.`,
    "---",
    "",
    `# ${label}`,
    "",
    `Generated by \`scripts/vault-index.mjs\`. Reached from [[${ROOT_NOTE}]].`,
    "",
    START,
    "",
    ...list.map(line),
    "",
    END,
    "",
  ].join("\n");
}

// Replace only the generated region, preserving hand-written prose around it.
/**
 * Compare generated text against what is on disk, ignoring line endings.
 *
 * The generator always writes LF. `.md` is not pinned in `.gitattributes`, so a
 * Windows checkout hands these files back as CRLF — and a raw `!==` then reports
 * every generated file as stale on every run, forever, on that machine. It did:
 * `--check` failed on moc-business.md while `git diff` showed one changed date,
 * because git normalises line endings and the comparison did not.
 *
 * That is worse than a noisy check. The only way to clear it is to re-run the
 * generator, which rewrites `reviewed` to today — so a guard meant to make
 * someone re-read a note instead trained them to bump its date without reading.
 */
export function sameContent(a, b) {
  const norm = (s) => s.split("\r\n").join("\n");
  return norm(a) === norm(b);
}

export function spliceGenerated(existing, body) {
  const s = existing.indexOf(START);
  const e = existing.indexOf(END);
  if (s === -1 || e === -1 || e < s) {
    throw new Error(`missing or malformed ${START} / ${END} markers`);
  }
  return existing.slice(0, s + START.length) + "\n\n" + body + "\n\n" + existing.slice(e);
}

export function main(argv = process.argv.slice(2)) {
  const check = argv.includes("--check");
  const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const notes = loadNotes(root);
  const indexPath = resolve(root, "vault/00-index/INDEX.md");

  const groups = groupByFolder(notes);
  const written = [];

  // MOCs first, so the index can link to ones that exist.
  for (const [folder, list] of groups) {
    if (list.length < MOC_THRESHOLD) continue;
    const p = resolve(root, `vault/00-index/${mocNameFor(folder)}.md`);
    const next = renderMoc(folder, list);
    let prev = "";
    try { prev = readFileSync(p, "utf8"); } catch { /* new file */ }
    // Ignore the reviewed line when comparing, or --check flaps daily.
    const undate = (s) => s.replace(/^reviewed: .*$/m, "");
    if (!sameContent(undate(prev), undate(next))) {
      if (check) { process.stdout.write(`  ✗ vault-index: ${mocNameFor(folder)}.md is stale\n`); return 1; }
      writeFileSync(p, next, "utf8");
      written.push(`vault/00-index/${mocNameFor(folder)}.md`);
    }
  }

  const existing = readFileSync(indexPath, "utf8");
  let next;
  try {
    next = spliceGenerated(existing, renderIndexBody(notes));
  } catch (err) {
    process.stdout.write(`  ✗ vault-index: ${err.message}\n`);
    return 1;
  }

  const lines = next.split(/\r?\n/).length;
  if (lines > INDEX_LINE_CAP) {
    process.stdout.write(
      `  ✗ vault-index: INDEX.md would be ${lines} lines, over the ${INDEX_LINE_CAP} cap. ` +
      `Lower MOC_THRESHOLD so more folders collapse to a MOC.\n`,
    );
    return 1;
  }

  if (!sameContent(next, existing)) {
    if (check) {
      process.stdout.write("  ✗ vault-index: INDEX.md is out of date — run `npm run vault:index`\n");
      return 1;
    }
    writeFileSync(indexPath, next, "utf8");
    written.push("vault/00-index/INDEX.md");
  }

  process.stdout.write(
    check
      ? `  ✓ vault-index: INDEX.md up to date (${lines}/${INDEX_LINE_CAP} lines)\n`
      : `  ✓ vault-index: ${written.length ? `wrote ${written.join(", ")}` : "already up to date"} (${lines}/${INDEX_LINE_CAP} lines)\n`,
  );
  return 0;
}

const invokedDirectly = process.argv[1]
  ? import.meta.url === pathToFileURL(process.argv[1]).href
  : false;
if (invokedDirectly) process.exit(main());
