-- US-2286: exclude sandbox purchases from revenue reporting.
--
-- 00559 stamped users.billing_environment so a sandbox-granted plan could be
-- told from a paid one. Nothing has read it since. Both revenue surfaces still
-- count a sandbox grant as a paying subscriber, which is the defect the marker
-- was added to make fixable: an App Review tester on a free entitlement shows
-- up in MRR.
--
-- SIX SITES, all of them reading public.users with the revenue predicate
-- (active|past_due AND a paid tier). trialing and past_due-only counts are NOT
-- revenue and are untouched.
--   revenue_dashboard      the MRR sum, activePaid, arpuCents, byPlan
--   admin_revenue_metrics  activePaid, byPlanInterval
--
-- `is distinct from` rather than `<>`. Pre-marker rows are NULL and
-- countsAsRevenue(NULL) is TRUE, so they must keep counting; a plain
-- inequality evaluates to NULL for them and would silently zero historical MRR.
--
-- These two bodies are otherwise BYTE-IDENTICAL to what is running: they were
-- generated by reading 00215 and 00514 and inserting one line at each site,
-- not retyped. Docker is down on the authoring host so there was no throwaway
-- Postgres to execute them against, and retyping 350 lines unverified was the
-- risk worth removing. CREATE OR REPLACE, so re-running is safe.
create or replace function public.revenue_dashboard(
  p_start       timestamptz,
  p_end         timestamptz,
  p_granularity text default 'day'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  result      jsonb;
  v_gran      text;
  v_mrr_cents numeric;
begin
  -- Authenticated end-users must be admins; the service-role edge (auth.uid()
  -- null) passes. anon can't reach this — execute is not granted to it.
  if auth.uid() is not null and not public.is_admin() then
    raise exception 'revenue_dashboard: admin role required'
      using errcode = '42501';
  end if;

  if p_start is null or p_end is null or p_end <= p_start then
    raise exception 'revenue_dashboard: invalid period window (start must precede end)'
      using errcode = '22023';
  end if;

  -- Only daily or weekly buckets are supported; anything else falls back to day.
  v_gran := lower(coalesce(p_granularity, 'day'));
  if v_gran not in ('day', 'week') then
    v_gran := 'day';
  end if;

  -- ── Point-in-time MRR (active paid subs, priced from pricing_plans) ──
  -- trialing is NOT counted toward MRR (no charge yet); free is not a paid tier.
  select coalesce(sum(
    case when u.flipdesk_interval = 'yearly'
      then pp.price_yearly_cents / 12.0
      else pp.price_monthly_cents
    end
  ), 0)
  into v_mrr_cents
  from public.users u
  join public.pricing_plans pp on pp.key = u.flipdesk_plan::text
  where u.subscription_status in ('active', 'past_due')
    and u.flipdesk_plan <> 'free'
    and u.billing_environment is distinct from 'sandbox';

  select jsonb_build_object(
    'period', jsonb_build_object(
      'start', p_start,
      'end', p_end,
      'granularity', v_gran
    ),

    -- ── Current snapshot ──
    'current', jsonb_build_object(
      'mrrCents', round(v_mrr_cents),
      'arrCents', round(v_mrr_cents * 12),
      'activePaid', (
        select count(*)::int from public.users
        where subscription_status in ('active', 'past_due') and flipdesk_plan <> 'free'
          and billing_environment is distinct from 'sandbox'
      ),
      'trialing', (
        select count(*)::int from public.users where subscription_status = 'trialing'
      ),
      'pastDue', (
        select count(*)::int from public.users where subscription_status = 'past_due'
      ),
      'arpuCents', (
        select case when count(*) > 0 then round(v_mrr_cents / count(*)) else 0 end
        from public.users
        where subscription_status in ('active', 'past_due') and flipdesk_plan <> 'free'
          and billing_environment is distinct from 'sandbox'
      ),
      -- Plan mix: active paid subs by (plan, interval) with each bucket's MRR.
      'byPlan', (
        select coalesce(jsonb_agg(jsonb_build_object(
          'plan', plan, 'interval', intv, 'count', cnt, 'mrrCents', mrr
        ) order by plan, intv), '[]'::jsonb)
        from (
          select
            u.flipdesk_plan::text as plan,
            coalesce(u.flipdesk_interval::text, 'monthly') as intv,
            count(*)::int as cnt,
            round(sum(case when u.flipdesk_interval = 'yearly'
              then pp.price_yearly_cents / 12.0 else pp.price_monthly_cents end)) as mrr
          from public.users u
          join public.pricing_plans pp on pp.key = u.flipdesk_plan::text
          where u.subscription_status in ('active', 'past_due') and u.flipdesk_plan <> 'free'
            and u.billing_environment is distinct from 'sandbox'
          group by u.flipdesk_plan, u.flipdesk_interval
        ) s
      )
    ),

    -- ── MRR movement over the window (event-based; monthly-price proxy) ──
    'movement', (
      with ev as (
        select
          e.event_type,
          e.from_plan::text as from_plan,
          e.to_plan::text   as to_plan,
          coalesce(fp.price_monthly_cents, 0) as from_cents,
          coalesce(tp.price_monthly_cents, 0) as to_cents
        from public.flipdesk_subscription_events e
        left join public.pricing_plans fp on fp.key = e.from_plan::text
        left join public.pricing_plans tp on tp.key = e.to_plan::text
        where e.created_at >= p_start and e.created_at < p_end
          and e.event_type in (
            'customer.subscription.created',
            'customer.subscription.updated',
            'customer.subscription.deleted'
          )
      )
      select jsonb_build_object(
        'newCount', (
          select count(*)::int from ev
          where event_type = 'customer.subscription.created'
            and to_plan is not null and to_plan <> 'free'
            and (from_plan is null or from_plan = 'free')
        ),
        'newMrrCents', (
          select coalesce(sum(to_cents), 0)::bigint from ev
          where event_type = 'customer.subscription.created'
            and to_plan is not null and to_plan <> 'free'
            and (from_plan is null or from_plan = 'free')
        ),
        'churnedCount', (
          select count(*)::int from ev
          where event_type = 'customer.subscription.deleted'
            and from_plan is not null and from_plan <> 'free'
        ),
        'churnedMrrCents', (
          select coalesce(sum(from_cents), 0)::bigint from ev
          where event_type = 'customer.subscription.deleted'
            and from_plan is not null and from_plan <> 'free'
        ),
        'expansionMrrCents', (
          select coalesce(sum(to_cents - from_cents), 0)::bigint from ev
          where event_type in ('customer.subscription.updated', 'customer.subscription.created')
            and from_plan is not null and from_plan <> 'free'
            and to_plan is not null and to_plan <> 'free'
            and to_cents > from_cents
        ),
        'contractionMrrCents', (
          select coalesce(sum(from_cents - to_cents), 0)::bigint from ev
          where event_type in ('customer.subscription.updated', 'customer.subscription.created')
            and from_plan is not null and from_plan <> 'free'
            and to_plan is not null and to_plan <> 'free'
            and to_cents < from_cents
        )
      )
    ),

    -- ── Trial-to-paid (cohort started in window, conversion measured to-date) ──
    'trial', (
      with started as (
        select subscription_status, flipdesk_plan
        from public.users
        where trial_started_at is not null
          and trial_started_at >= p_start and trial_started_at < p_end
      )
      select jsonb_build_object(
        'startedInPeriod', (select count(*)::int from started),
        'convertedFromCohort', (
          select count(*)::int from started
          where subscription_status in ('active', 'past_due') and flipdesk_plan <> 'free'
        )
      )
    ),

    -- ── One-time credit-pack revenue (gross; priced from pricing_config) ──
    'credits', (
      select jsonb_build_object(
        'packRevenueCents', coalesce(sum(pc.price_cents), 0)::bigint,
        'packCount', count(t.id)::int
      )
      from public.grade_credit_transactions t
      left join public.pricing_config pc
        on pc.kind = 'credit_pack' and pc.credits = t.delta
      where t.reason = 'pack_purchase'
        and t.created_at >= p_start and t.created_at < p_end
    ),

    -- ── Daily / weekly time series for charts ──
    'timeSeries', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'start', b.bucket,
        'newCount', coalesce(subs.new_count, 0),
        'churnedCount', coalesce(subs.churned_count, 0),
        'packRevenueCents', coalesce(cr.pack_revenue, 0),
        'packCount', coalesce(cr.pack_count, 0)
      ) order by b.bucket), '[]'::jsonb)
      from generate_series(
        date_trunc(v_gran, p_start),
        date_trunc(v_gran, p_end),
        ('1 ' || v_gran)::interval
      ) as b(bucket)
      left join lateral (
        select
          count(*) filter (
            where e.event_type = 'customer.subscription.created'
              and e.to_plan is not null and e.to_plan::text <> 'free'
          ) as new_count,
          count(*) filter (
            where e.event_type = 'customer.subscription.deleted'
              and e.from_plan is not null and e.from_plan::text <> 'free'
          ) as churned_count
        from public.flipdesk_subscription_events e
        where e.created_at >= b.bucket
          and e.created_at < b.bucket + ('1 ' || v_gran)::interval
      ) subs on true
      left join lateral (
        select
          coalesce(sum(pc.price_cents), 0) as pack_revenue,
          count(t.id) as pack_count
        from public.grade_credit_transactions t
        left join public.pricing_config pc
          on pc.kind = 'credit_pack' and pc.credits = t.delta
        where t.reason = 'pack_purchase'
          and t.created_at >= b.bucket
          and t.created_at < b.bucket + ('1 ' || v_gran)::interval
      ) cr on true
    )
  ) into result;

  return result;
end;
$$;

CREATE OR REPLACE FUNCTION public.admin_revenue_metrics()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  result jsonb;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'admin_revenue_metrics: admin role required'
      using errcode = '42501';
  end if;

  select jsonb_build_object(
    'subscriptions', jsonb_build_object(
      -- Genuinely-billing subscriptions: active or past_due (Stripe is still
      -- attempting collection), on a paid FlipDesk tier. trialing is NOT counted
      -- toward MRR (no charge yet) and is surfaced separately.
      'activePaid', (
        select count(*)::int from public.users
        where subscription_status in ('active', 'past_due')
          and flipdesk_plan <> 'free'
          and billing_environment is distinct from 'sandbox'
      ),
      'trialing', (
        select count(*)::int from public.users
        where subscription_status = 'trialing'
      ),
      'pastDue', (
        select count(*)::int from public.users
        where subscription_status = 'past_due'
      ),
      -- Raw active-subscription counts by (plan, interval) so the client derives
      -- MRR from FLIPDESK_PLANS pricing — pricing stays in one place (constants),
      -- never hard-coded here. Yearly is normalized to monthly client-side.
      'byPlanInterval', (
        select coalesce(jsonb_agg(jsonb_build_object(
          'plan', plan,
          'interval', coalesce(intv, 'monthly'),
          'count', cnt
        )), '[]'::jsonb)
        from (
          select
            flipdesk_plan::text as plan,
            flipdesk_interval as intv,
            count(*)::int as cnt
          from public.users
          where subscription_status in ('active', 'past_due')
            and flipdesk_plan <> 'free'
            and billing_environment is distinct from 'sandbox'
          group by flipdesk_plan, flipdesk_interval
        ) s
      ),
      -- Authoritative 30-day churn: distinct users whose subscription was
      -- canceled (Stripe customer.subscription.deleted) in the window. Replaces
      -- the old "free user with a recent sale" activity guess.
      'canceledLast30d', (
        select count(distinct user_id)::int
        from public.flipdesk_subscription_events
        where event_type = 'customer.subscription.deleted'
          and created_at >= now() - interval '30 days'
      )
    ),
    'ai', jsonb_build_object(
      -- Whether any cost has been tracked at all — lets the UI show an honest
      -- "no AI-cost data yet" state instead of a misleading $0 margin.
      'costTrackingActive', (
        select exists (select 1 from public.ai_usage_events)
      ),
      'last24h', (
        select jsonb_build_object(
          'costUsd', coalesce(sum(cost_usd), 0),
          'inputTokens', coalesce(sum(input_tokens), 0)::bigint,
          'outputTokens', coalesce(sum(output_tokens), 0)::bigint,
          'grades', count(distinct submission_id)::int
        )
        from public.ai_usage_events
        where created_at >= now() - interval '24 hours'
      ),
      'last30d', (
        select jsonb_build_object(
          'costUsd', coalesce(sum(cost_usd), 0),
          'inputTokens', coalesce(sum(input_tokens), 0)::bigint,
          'outputTokens', coalesce(sum(output_tokens), 0)::bigint,
          'grades', count(distinct submission_id)::int
        )
        from public.ai_usage_events
        where created_at >= now() - interval '30 days'
      ),
      -- Avg AI cost per graded submission over 30d (total cost / distinct grades).
      'avgCostPerGradeUsd', coalesce((
        select sum(cost_usd) / nullif(count(distinct submission_id), 0)
        from public.ai_usage_events
        where created_at >= now() - interval '30 days'
          and submission_id is not null
      ), 0),
      -- Last 30 daily buckets: cost + tokens + grades per day.
      'daily', (
        select coalesce(jsonb_agg(jsonb_build_object(
          'start', b.bucket,
          'costUsd', coalesce(agg.cost, 0),
          'grades', coalesce(agg.grades, 0),
          'inputTokens', coalesce(agg.in_tok, 0)::bigint,
          'outputTokens', coalesce(agg.out_tok, 0)::bigint
        ) order by b.bucket), '[]'::jsonb)
        from generate_series(
          date_trunc('day', now()) - interval '29 days',
          date_trunc('day', now()),
          interval '1 day'
        ) as b(bucket)
        left join lateral (
          select
            sum(e.cost_usd) as cost,
            sum(e.input_tokens) as in_tok,
            sum(e.output_tokens) as out_tok,
            count(distinct e.submission_id) as grades
          from public.ai_usage_events e
          where e.created_at >= b.bucket
            and e.created_at < b.bucket + interval '1 day'
        ) agg on true
      )
    )
  ) into result;

  return result;
end;
$function$;

insert into public.applied_migrations (version) values ('00608') on conflict do nothing;
