-- US-3125: seventeen skate, surf and streetwear brands, and colorways for the seven whose palettes earn it.
--
-- Catalogues read 2026-09-07 with scripts/ops/shopify-brand-harvest.mjs. Same
-- rules as 00734 and 00739 throughout: a colour on five or more products, a
-- brand with at least eight such colours and no more than 35% plain colour
-- words, base_color and shade from the brand's own facet where it publishes one
-- and aspect-normalize's family table otherwise.
--
-- -- REGISTERED NUMBERS: SEVEN OF SEVENTEEN ---------------------------------
--
--     Aime Leon Dore   RN 142781   AIME LEON DORE INC              [SWEATERS]
--     DC Shoes         RN 134459   DC SHOES INC.                   [JEANS AND TEE SHIRTS]
--     Hurley           RN 100691   HURLEY INTERNATIONAL LLC        [SPORTSWEAR]
--     Lakai            RN 102370   LAKAI, LTD.                     [CLOTHING]
--     Noah             RN 150322   NOAH CLOTHING LLC               [PANTS JACKETS T-SHIRTS SHOES HATS MENS CLOTHING]
--     Rip Curl         RN 61744    RIP CURL, INC.                  [SPORTSWEAR]
--     Stussy           RN 94974    STUSSY INCORPORATED             [CLOTHING]
--
-- Two of those needed the tie broken by PRODUCT LINE, which is the Ibex and Onia
-- rule from 00742 doing its job. "Hurley" returns six registrants, five of whom
-- are people named Hurley; HURLEY INTERNATIONAL LLC is the only company and the
-- only one carrying SPORTSWEAR. "Noah" returns nineteen, and NOAH CLOTHING LLC
-- is the only one whose product line is the menswear this label actually makes
-- -- NOAH SPORTSWEAR, the nearest rival, lists no product line at all and so
-- cannot win a tie-break it never entered.
--
-- -- TEN REFUSED, AND THE REGISTER SAYS WHY ----------------------------------
--
-- Etnies, HUF, Obey, Quiksilver, Polar Skate and Theories of Atlantis return
-- NOTHING. That is a legitimate absence, not a failed lookup.
--
-- Emerica and Roxy are the SUBSTRING TRAP, now seen eight times and still the
-- strongest argument against ever automating this step. The register matches on
-- substring, so "Emerica" pulls LE-EMERICA-NA TRADING CO. and "Roxy" pulls
-- P-ROXY- APPAREL, ROXY RUG CORP, ROXY HOSIERY and RoxyNell llc. Every one is a
-- confident-looking hit for a brand that has no registration at all.
--
-- Billabong returns BURLEIGH POINT, LTD., whose product line ("MEN'S WOMEN'S AND
-- CHILDREN'S SURF LIFESTYLE APPAREL") fits perfectly and is very probably the
-- operating company. It is still refused: the name shares no token with the
-- label, and a matching product line can BREAK a tie between same-name
-- registrants, never stand in for a name. That distinction is the whole rule.
--
-- Primitive is refused for the opposite reason -- not too few candidates but two
-- equally good ones. PRIMITIVE, INC. (hats, jackets, pants) and Primitive
-- Company (unisex, men's, women's, children's apparel) both pass the name test
-- and neither product line rules the other out. Picking either would be a coin
-- flip wearing a citation.
--
-- -- COLOURS ----------------------------------------------------------------
--
-- Seeded: aimeleondore (26), billabong (118), dcshoes (8), hurley (95), obey (19), quiksilver (44), roxy (89).
-- Palette refused, too few or too plain: emerica (3), etnies (5), huf (23, 52% plain), lakai (4), noahny (33, 67% plain), primitiveskate (39, 59% plain), stussy (28, 57% plain).
-- No colour survives the filter: polarskate (0 raw), ripcurl (0 raw), theoriesofatlantis (8 raw).
--
-- polarskate and ripcurl publish a size option and NO colour option at all;
-- theoriesofatlantis publishes eight colours that never recur across products.
--
-- Those last brands still get a KB row, because the brand is worth knowing. An
-- empty colorway set for them means the feed does not say, never that the brand
-- has one colour.
--
insert into public.brand_knowledge
  (brand_key, canonical_brand, aliases, category_focus, registered_numbers,
   notes, source_url, confidence, verified, updated_by)
values

  ('aimeleondore', 'Aime Leon Dore', ARRAY['aime leon dore','aimeleondore','ald']::text[], ARRAY['streetwear','menswear','new york','luxury casual']::text[], ARRAY['RN 142781']::text[],
   'RN 142781 is FTC-record sourced -- registrant "AIME LEON DORE INC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://aimeleondore.com/', 0.60, false, 'migration:00747'),
  ('billabong', 'Billabong', ARRAY['billabong']::text[], ARRAY['surf','boardshorts','menswear','womenswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.billabong.com/', 0.60, false, 'migration:00747'),
  ('dcshoes', 'DC Shoes', ARRAY['dc shoes','dcshoes','dc']::text[], ARRAY['skate','footwear','snow','menswear']::text[], ARRAY['RN 134459']::text[],
   'RN 134459 is FTC-record sourced -- registrant "DC SHOES INC.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.dcshoes.com/', 0.60, false, 'migration:00747'),
  ('emerica', 'Emerica', ARRAY['emerica']::text[], ARRAY['skate','footwear','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://emerica.com/', 0.60, false, 'migration:00747'),
  ('etnies', 'etnies', ARRAY['etnies','etnies skateboarding']::text[], ARRAY['skate','footwear','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://etnies.com/', 0.60, false, 'migration:00747'),
  ('huf', 'HUF', ARRAY['huf','huf worldwide']::text[], ARRAY['skate','streetwear','socks','san francisco']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://hufworldwide.com/', 0.60, false, 'migration:00747'),
  ('hurley', 'Hurley', ARRAY['hurley']::text[], ARRAY['surf','boardshorts','menswear','california']::text[], ARRAY['RN 100691']::text[],
   'RN 100691 is FTC-record sourced -- registrant "HURLEY INTERNATIONAL LLC, AN OREGON LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.hurley.com/', 0.60, false, 'migration:00747'),
  ('lakai', 'Lakai', ARRAY['lakai','lakai limited footwear']::text[], ARRAY['skate','footwear','menswear']::text[], ARRAY['RN 102370']::text[],
   'RN 102370 is FTC-record sourced -- registrant "LAKAI, LTD.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://lakai.com/', 0.60, false, 'migration:00747'),
  ('noahny', 'Noah', ARRAY['noah','noah ny','noahny']::text[], ARRAY['streetwear','menswear','new york','surf']::text[], ARRAY['RN 150322']::text[],
   'RN 150322 is FTC-record sourced -- registrant "NOAH CLOTHING LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://noahny.com/', 0.60, false, 'migration:00747'),
  ('obey', 'OBEY Clothing', ARRAY['obey','obey clothing','obey giant']::text[], ARRAY['streetwear','graphic','art','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.obeyclothing.com/', 0.60, false, 'migration:00747'),
  ('polarskate', 'Polar Skate Co', ARRAY['polar','polar skate','polar skate co']::text[], ARRAY['skate','streetwear','sweden']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://polarskateco.com/', 0.60, false, 'migration:00747'),
  ('primitiveskate', 'Primitive Skateboarding', ARRAY['primitive','primitive skate','primitive skateboarding']::text[], ARRAY['skate','streetwear','collabs']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.primitiveskate.com/', 0.60, false, 'migration:00747'),
  ('quiksilver', 'Quiksilver', ARRAY['quiksilver','quicksilver']::text[], ARRAY['surf','boardshorts','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.quiksilver.com/', 0.60, false, 'migration:00747'),
  ('ripcurl', 'Rip Curl', ARRAY['rip curl','ripcurl']::text[], ARRAY['surf','wetsuits','boardshorts','australia']::text[], ARRAY['RN 61744']::text[],
   'RN 61744 is FTC-record sourced -- registrant "RIP CURL, INC.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.ripcurl.com/', 0.60, false, 'migration:00747'),
  ('roxy', 'Roxy', ARRAY['roxy']::text[], ARRAY['surf','womenswear','swim','boardshorts']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.roxy.com/', 0.60, false, 'migration:00747'),
  ('stussy', 'Stussy', ARRAY['stussy','stÃ¼ssy']::text[], ARRAY['streetwear','surf','graphic','california']::text[], ARRAY['RN 94974']::text[],
   'RN 94974 is FTC-record sourced -- registrant "STUSSY INCORPORATED". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.stussy.com/', 0.60, false, 'migration:00747'),
  ('theoriesofatlantis', 'Theories of Atlantis', ARRAY['theories','theories of atlantis','theories brand']::text[], ARRAY['skate','streetwear','graphic']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://theoriesofatlantis.com/', 0.60, false, 'migration:00747')
on conflict (brand_key) do nothing;

insert into public.brand_colorways
  (brand_key, color_name, aliases, hex, years, base_color, shade,
   source_url, confidence, verified, updated_by)
values

  ('aimeleondore', '14k Gold', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'BRIGHT WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Botanical Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'CROWN BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Chocolate Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Coconut Milk', ARRAY[]::text[], NULL, NULL, null, null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Coffee Bean', ARRAY[]::text[], NULL, NULL, null, null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Cordovan', ARRAY[]::text[], NULL, NULL, null, null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'DARK GREEN', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Equestrian Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Evening Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'GOLD', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'JET BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Kalamata', ARRAY[]::text[], NULL, NULL, null, null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'MID WASH', ARRAY[]::text[], NULL, NULL, null, 'Medium', 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'NAVY BLAZER', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Naval Academy', ARRAY[]::text[], NULL, NULL, null, null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Oatmeal', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'PRISTINE', ARRAY[]::text[], NULL, NULL, null, null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Pine Grove', ARRAY[]::text[], NULL, NULL, null, null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'SKY CAPTAIN', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'Silver Mix', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('aimeleondore', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://aimeleondore.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'AGAVE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'ALLOY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'ARMY GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'ASH ROSE', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Ashleigh Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BAY BLUE', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLACK MULTI', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLACK PEBBLE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLACK SANDS', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLUE BELL', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLUE FOG', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLUE HORIZON', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLUE MIST', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLUE MULTI', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BLUE SMOKE', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BRIGHT MARINE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'BROWN STONE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'CACTUS', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'CANTEEN', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'CARAMEL CAFE', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'CEDAR', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'CHINA BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'CLEARWATER', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'CLIMBING IVY', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'COASTAL BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'COBBLESTONE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'CURRY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Carolina Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Chino', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Coral Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'DARK BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'DARK DENIM', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'DARK OLIVE', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'DEEP LAGOON', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'DEEP SEA', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'DOVE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'DREAM BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'DUTCH BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Dusty Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'ESPRESSO', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Emerald Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Evergreen', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'FIESTA RED', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'FOG GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'GRAYSTONE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'GREEN GLOW', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'GREEN TROPICS', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'GUAVA', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Gravel', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Gray Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Green Ash', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Green Tea', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'HEATHER GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'HEDGE GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'HOT CORAL', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'INCENSE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'KHAKI', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'LIGHT GRAY HEATHER', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'LIGHT PEACH', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Midnight', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Midnight Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Military', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Mineral Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Misty Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Moss', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'NATURAL', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'OATMEAL', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'OCEAN SPRAY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'OFF BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'OFF WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'ORANGE MULTI', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Ocean Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'PALE PEACH', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'PARTY PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'PINK SUNSET', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'PURPLE ASH', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'RAVEN', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'RED DAHLIA', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'RIFLE GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Real Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Red Aloha', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Rose Brown', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'SALT CRYSTAL', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'SAND KHAKI', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'SMOKE GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'STONE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'SUGAR ALMOND', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'SUMMER GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'SUNDRESS', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'SWEET LILAC', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Sage Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Sandy Tan', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Sea Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Sedona', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Slate Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Soft Peach', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Spruce Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Stealth', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Steel Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Stone Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Sunburnt', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'TANGERINE', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'TEAK', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'TRUE BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'TRUE NAVY', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'TWILIGHT BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'VINTAGE KHAKI', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'VINTAGE VIOLET', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'WATERFALL', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'WHITE CAP', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'WHITE MULTI', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Washed Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Washed Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('billabong', 'Whitecap', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.billabong.com/products.json', 0.75, false, 'migration:00747'),
  ('dcshoes', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.dcshoes.com/products.json', 0.75, false, 'migration:00747'),
  ('dcshoes', 'Black/Black/Black (3Bk)', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.dcshoes.com/products.json', 0.75, false, 'migration:00747'),
  ('dcshoes', 'Black/Gum (Bgm)', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.dcshoes.com/products.json', 0.75, false, 'migration:00747'),
  ('dcshoes', 'Black/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.dcshoes.com/products.json', 0.75, false, 'migration:00747'),
  ('dcshoes', 'Black/White (Bkw)', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.dcshoes.com/products.json', 0.75, false, 'migration:00747'),
  ('dcshoes', 'Oatmeal', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.dcshoes.com/products.json', 0.75, false, 'migration:00747'),
  ('dcshoes', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.dcshoes.com/products.json', 0.75, false, 'migration:00747'),
  ('dcshoes', 'White/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.dcshoes.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'AQUIFER HEATHER', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Abyss', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Armored Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Army', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Aster', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Aster / Mimosa', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Barely Bone', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Black Floral', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Black Heather', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Blue Dream', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Bone', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Bristlecone', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Cargo', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Charcoal Fern', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Chocolate', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Coconut', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Coral Blossom', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Dark Grey Heather', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Dark Stone Grey', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Denim', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Destroyer', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Disco Pink/Maraschino', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Dover', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'EDEN', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Egret', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Fern', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Floral Chamomile', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Gingko Cloud / Terracotta', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Grass', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Great White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Grey Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Hazelnut', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Heavy Meadow', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Hydro', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Iceland', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Ion Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Iron Ore', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Island Time', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Kelp Ombre', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Light Asteroid', ARRAY[]::text[], NULL, NULL, null, 'Light', 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Light Stone Grey', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'MALVERDE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'MIDNIGHT AQUA', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Maraschino', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Matte Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Maui Mango / Mimosa', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Melon', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Miami Garden / Mole', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Mole', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Monsoon', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Nightforce', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Obsidian', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Off Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Off White', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Opal', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Orchid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Particle', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Phantom Rose', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Poppy', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Ranger', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Riviera', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Rococco Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Rose Tan', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'STARLIGHT BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Sailing', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Sandstorm', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Scenic Sunset / Mystic Dawn', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Seashore Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Soft Spot / Mole / Black', ARRAY[]::text[], NULL, NULL, 'Black', 'Light', 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Sorbet', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Sour Apple', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Spray', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Stone Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Submarine', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Sunrise Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Surf Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Surf Blue / Beach Glass', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Tan', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Terracotta Ombre', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Tofu', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Tropical Geo', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Tropical Mist', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Vacay Plaid / Electric Lime', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Washed Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Willow', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Windward Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Woodside', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('hurley', 'Worker Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hurley.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'ASH GREY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'BLACK MULTI', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'DIGITAL BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'DUSTY BLACK LIMO', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'DUSTY VINTAGE WOOD CAMO', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'FADED BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'FENCE CAMO MULTI', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'HEATHER GREY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'LIGHT INDIGO', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'PAGEANT BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'PIGMENT BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'PIGMENT BLACK OLIVE', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'PIGMENT DARK SAPPHIRE', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'RINSE INDIGO', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'VINTAGE BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('obey', 'WHITE MULTI', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.obeyclothing.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'ANTHRACITE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'AQUA', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'BLUE CORAL', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'BLUE HAZE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'BONE WHITE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'CAMO', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'DARK DENIM', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'DARK SLATE', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'DUSTY BLUE', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'GRAPE LEAF', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'HIGH RISE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'ICEBERG GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'INFINITY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'IRON GATE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'LIGHT GREY HTH', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'LILY PAD', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'MARSALA', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'MEDITERRANEA', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'MICRO CHIP', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'MOONBEAM', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'MOONSTRUCK', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'Off White', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'PEYOTE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'PHANTOM', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'PINE BARK', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'PLAZA TAUPE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'Palace Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'QUARRY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'QUIET HARBOR', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'RIVIERA', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'SALSA', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'SENECA ROCK', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'SILVER BIRCH', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'SKYWAY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'SKYWAY HEATHER', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'SNOW WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'SUNSHINE COAST TILE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'THYME', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'TWILL', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('quiksilver', 'WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.quiksilver.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Adobe Rose', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Airy Blue Solid', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Amber Gold Solid', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Animal Print', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Anthracite', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Anthracite Island Escape', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Anthracite Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Aqua Bliss', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Aquamult', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Azure Blue Solid', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Bijou Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Biking Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Black Combo', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Black Multi', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Black/Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Black/Ivory', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Blkcoral', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Blue Combo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Blue Haze Hibiscus', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Blue Horizon Solid', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Blue Multi', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Blugreen', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Bright White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Brown Multi', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Brown Tile Multi', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Brownie Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Captains Blue Solid', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cinnebar', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cloud Dancer Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cobalt', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Coconut Milk', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Coconut Milk Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cool Surf Baltic', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cool Surf Chutney', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cool Surf Oil Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Coral Palm Haze', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Coral Punch', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Coralmul', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cornflower', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cornflower Blue Solid', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Cross Your Heart', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Deep Lagoon', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Deepoliv', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Dew Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Dragonfly Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Dutch Blue Solid', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Dutchblu', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Egret', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Four Leaf Clover Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Golden Rod', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Gray Combo', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Holly Berry', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Hot Coral Solid', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Hotcoral', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Ivoryred', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Lilac Sachet', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Mood Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Neutral Combo', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Ocean Spray', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Oceanside', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Oil Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Open Air', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Parchment', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Parchment Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Peach Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Petal Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Phantom', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Phantom Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Pink Combo', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Pinkwht', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Plumeria', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Popcorn Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Port Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Pumice Stone', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Raspberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Red Hot', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Red/Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Rust Multi', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Sage Solid', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Shocking Pink Solid', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Snow White Solid', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Tarragon Solid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'Vintage Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747'),
  ('roxy', 'White/Light Multi', ARRAY[]::text[], NULL, NULL, 'White', 'Light', 'https://www.roxy.com/products.json', 0.75, false, 'migration:00747')
on conflict do nothing;

-- US-1108 self-record footer.
insert into public.applied_migrations (version) values ('00747') on conflict do nothing;
