-- US-3125: nineteen more brands, and colorways for the 12 whose palettes earn it.
--
-- Catalogues read 2026-09-06 with scripts/ops/shopify-brand-harvest.mjs. Same
-- rules as 00734 and 00739 throughout: a colour on five or more products, a
-- brand with at least eight such colours and no more than 35%% plain colour
-- words, base_color and shade from the brand's own facet where it publishes one
-- and aspect-normalize's family table otherwise.
--
-- -- REGISTERED NUMBERS: FIVE OF NINETEEN -----------------------------------
--
--     Duck Camp           RN 167300   Duck Camp LLC
--     Katin               RN 92787    KATIN USA, INC.
--     Marine Layer        RN 140892   MARINE LAYER INC
--     Ministry of Supply  RN 160361   Ministry of Supply
--     Outerknown          RN 144067   OUTERKNOWN LLC
--
-- The other fourteen are REFUSED rather than guessed, and the register makes the
-- reason plain each time. Darn Tough, OluKai and Rothy's return NOTHING, which
-- is a legitimate absence. The rest return a registrant that is not the label:
--
--     Howler Brothers  ->  HEARD DESIGN LLC
--     Linksoul         ->  TEEDUP DF, LLC
--     Mack Weldon      ->  BDB VENTURES, INC.
--     Psycho Bunny     ->  GOD AND GOLD
--     Roark            ->  three hits, none of them the travel label
--
-- Each is probably the operating company. "Probably" is what the Longchamp trap
-- is made of, so each waits for a source that says so.
--
-- -- SIX BRANDS PUBLISH NO COLOUR OPTION AT ALL ------------------------------
--
-- everlane, myles, vollebak carry sizes and NO Color option at all.
-- richerpoorer (12 colours, none on 5+ products) publish colours that never recur. They
-- still get a brand row -- the brand is worth knowing -- and their colorways
-- wait for a different source. An empty colorway table for them means the feed
-- does not say, not that the brand has one colour.
--
-- Seeded colours: carbon38 (128), feetures (24), flylow (25), ibex (14), janji (12), minus33 (26), naadam (41), ridgemerino (17), splits59 (99), stio (61), topodesigns (33), trew (9).
-- Palette refused: bn3th (4 colours).
-- Palette refused: pathprojects (14 colours, 36%% plain).
-- Palette refused: stance (60 colours, 40%% plain).
--

insert into public.brand_knowledge
  (brand_key, canonical_brand, aliases, category_focus, registered_numbers,
   notes, source_url, confidence, verified, updated_by)
values

  ('bn3th', 'BN3TH', ARRAY['bn3th','bn3th apparel','myPakage']::text[], ARRAY['menswear','underwear','pouch','activewear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://bn3th.com/', 0.60, false, 'migration:00742'),
  ('carbon38', 'Carbon38', ARRAY['carbon38','carbon 38']::text[], ARRAY['activewear','womenswear','leggings','studio']::text[], ARRAY['RN 147957']::text[],
   'RN 147957 is FTC-record sourced -- registrant "CARBON 38, INC.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://carbon38.com/', 0.60, false, 'migration:00742'),
  ('everlane', 'Everlane', ARRAY['everlane']::text[], ARRAY['basics','transparent pricing','menswear','womenswear']::text[], ARRAY['RN 139393']::text[],
   'RN 139393 is FTC-record sourced -- registrant "EVERLANE INC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.everlane.com/', 0.60, false, 'migration:00742'),
  ('feetures', 'Feetures', ARRAY['feetures']::text[], ARRAY['socks','running','targeted compression']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://feetures.com/', 0.60, false, 'migration:00742'),
  ('flylow', 'Flylow', ARRAY['flylow','flylow gear']::text[], ARRAY['ski','outerwear','freeride','technical']::text[], ARRAY['RN 148964']::text[],
   'RN 148964 is FTC-record sourced -- registrant "FLYLOW SPORTS LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://flylowgear.com/', 0.60, false, 'migration:00742'),
  ('ibex', 'Ibex', ARRAY['ibex','ibex outdoor clothing']::text[], ARRAY['merino wool','outdoor','baselayer']::text[], ARRAY['RN 115719']::text[],
   'RN 115719 is FTC-record sourced -- registrant "IBEX OUTDOOR CLOTHING LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://ibex.com/', 0.60, false, 'migration:00742'),
  ('janji', 'Janji', ARRAY['janji']::text[], ARRAY['running','apparel','global prints','water']::text[], ARRAY['RN 137549']::text[],
   'RN 137549 is FTC-record sourced -- registrant "JANJI LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://janji.com/', 0.60, false, 'migration:00742'),
  ('minus33', 'Minus33', ARRAY['minus33','minus 33','minus33 merino']::text[], ARRAY['merino wool','baselayer','outdoor','made in usa']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://minus33.com/', 0.60, false, 'migration:00742'),
  ('myles', 'Myles Apparel', ARRAY['myles','myles apparel']::text[], ARRAY['menswear','versatile','travel','performance']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://mylesapparel.com/', 0.60, false, 'migration:00742'),
  ('naadam', 'NAADAM', ARRAY['naadam']::text[], ARRAY['cashmere','mongolia','knitwear','sustainable']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://naadam.co/', 0.60, false, 'migration:00742'),
  ('pathprojects', 'PATH projects', ARRAY['path projects','pathprojects','path']::text[], ARRAY['running','trail','modular layering']::text[], ARRAY['RN 150240']::text[],
   'RN 150240 is FTC-record sourced -- registrant "PATH PROJECTS LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://pathprojects.com/', 0.60, false, 'migration:00742'),
  ('richerpoorer', 'Richer Poorer', ARRAY['richer poorer','richer-poorer','richerpoorer']::text[], ARRAY['basics','socks','loungewear','tees']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://richer-poorer.com/', 0.60, false, 'migration:00742'),
  ('ridgemerino', 'Ridge Merino', ARRAY['ridge merino','ridgemerino']::text[], ARRAY['merino wool','baselayer','outdoor']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://ridgemerino.com/', 0.60, false, 'migration:00742'),
  ('splits59', 'Splits59', ARRAY['splits59','splits 59']::text[], ARRAY['activewear','womenswear','studio','leggings']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://splits59.com/', 0.60, false, 'migration:00742'),
  ('stance', 'Stance', ARRAY['stance','stance socks']::text[], ARRAY['socks','underwear','graphic','performance']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.stance.com/', 0.60, false, 'migration:00742'),
  ('stio', 'Stio', ARRAY['stio']::text[], ARRAY['outdoor','mountain','jackson hole','technical']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.stio.com/', 0.60, false, 'migration:00742'),
  ('topodesigns', 'Topo Designs', ARRAY['topo designs','topodesigns','topo']::text[], ARRAY['outdoor','packs','apparel','colorado']::text[], ARRAY['RN 149191']::text[],
   'RN 149191 is FTC-record sourced -- registrant "TOPO DESIGNS LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://topodesigns.com/', 0.60, false, 'migration:00742'),
  ('trew', 'TREW Gear', ARRAY['trew','trew gear','trewgear']::text[], ARRAY['ski','outerwear','technical','oregon']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://trewgear.com/', 0.60, false, 'migration:00742'),
  ('vollebak', 'Vollebak', ARRAY['vollebak']::text[], ARRAY['experimental','technical','outerwear','materials']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://vollebak.com/', 0.60, false, 'migration:00742')
on conflict (brand_key) do nothing;

insert into public.brand_colorways
  (brand_key, color_name, aliases, hex, years, base_color, shade,
   source_url, confidence, verified, updated_by)
values

  ('carbon38', 'ALMOND', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Abstract', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Acid Lime', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Animal', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'BLACK-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'BLACK/BLACK/WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'BLUSH', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'BONE', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'BRIGHT WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'BROWN', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Banana', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Bark', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Beige', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Bittersweet', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Black/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Blue Horizon', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Burgundy', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Burnt Sienna', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'CAPPUCCINO', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'CARAMEL', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'CARAMEL CAFE', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'CHAI', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'CLOUD WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'CREME', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Camel', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Caribou', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Champagne', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Chantilly', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Charcoal Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Check', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Chocolate', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Chocolate Torte', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Cloud Dancer', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Coffee Bean', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Crimson Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'DARK TEAL', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'DARKEST NIGHT', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'DENIM', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Dark Oak', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Deep Lagoon', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Digital Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Dove', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'ECRU', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'EGRET', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Espresso', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Evening Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'FADED NIGHT', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Fig', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Fig Toile', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Formal Garden', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'French Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'GOLD', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Gardenia', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Granite Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Haute Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Honeydew', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Ivory', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Ivory / Faded Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Ivory Marl', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'LATTE', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'LAVENDER', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Lavender Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Leopard', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Leopard Print', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Light Gold', ARRAY[]::text[], NULL, NULL, 'Gold', 'Light', 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Light Grey', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Light Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Lotus', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Malachite', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Maltese Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Medium Wash', ARRAY[]::text[], NULL, NULL, null, 'Medium', 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Merlot', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Moonbeam Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Multicolor', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'NOCTURNAL NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'NOIR', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Navy Blazer', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Navy Toile', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Novelty', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Nude', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Off White', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Onyx', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Pickled Beet', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Ponderosa Pine', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Quiet Harbor', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'ROOTS', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'RUM WINE', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'RUST', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Red Dahlia', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Red Leopard', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Rose Cloud', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'SOFT WHITE', ARRAY[]::text[], NULL, NULL, 'White', 'Light', 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'STONE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Sandy Tan', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Serenity', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Silver Heather', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Silversage', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Silversage / Acid Lime', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Sky Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Snow Leopard', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Snow White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Steel Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'TAN', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Taupe', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Terracotta', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Tomato', ARRAY[]::text[], NULL, NULL, null, null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'True Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'White/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('carbon38', 'Winter White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://carbon38.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Arctic Blue Mix', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Basic Mix', ARRAY[]::text[], NULL, NULL, null, null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Black Mix', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Blue Wave Mix', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Essentials Mix', ARRAY[]::text[], NULL, NULL, null, null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Glacier Mist Mix', ARRAY[]::text[], NULL, NULL, null, null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Gray Mix', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Light Gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Light Gray Mix', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Lilac Breeze Mix', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Mint Chip Mix', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Pink Salt Mix', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Stone Ivy Mix', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'White Ivy Mix', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'White Mix', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'White Rose Mix', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'White Tide Mix', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Wild Bloom Mix', ARRAY[]::text[], NULL, NULL, null, null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Wild Mist Mix', ARRAY[]::text[], NULL, NULL, null, null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('feetures', 'Woodland Forest Mix', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://feetures.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Abyss', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Amaro', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Aurora', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Bark', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Black/Dragonfruit', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Black/Rye', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Currant', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Dragonfruit', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Dune', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Evergreen', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Jasper', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Leaf', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Leaf/Evergreen', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Magma', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Mist', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Night', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Ocean', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Ocean/Abyss', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Rose', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Rye', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Sea', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Twig', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('flylow', 'Vine', ARRAY[]::text[], NULL, NULL, null, null, 'https://flylowgear.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Admiral', ARRAY[]::text[], NULL, NULL, null, null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Anthracite', ARRAY[]::text[], NULL, NULL, null, null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Black Grey Stripe', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Dark Pewter', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Deep Navy', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Evergreen', ARRAY[]::text[], NULL, NULL, null, null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Harvest Melange', ARRAY[]::text[], NULL, NULL, null, null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Lake Effect', ARRAY[]::text[], NULL, NULL, null, null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Midnight Navy', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Oceanic', ARRAY[]::text[], NULL, NULL, null, null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Olive Drab', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('ibex', 'Resin', ARRAY[]::text[], NULL, NULL, null, null, 'https://ibex.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Andromeda', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Arctic', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Carbon', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Chalk', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Cherry Funk', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Conifer', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Midnight', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Mist', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Sea Change', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Slipstream', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Supernova', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('janji', 'Tidal', ARRAY[]::text[], NULL, NULL, null, null, 'https://janji.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Ash Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Blaze Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Burgundy', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Charcoal Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Coffee', ARRAY[]::text[], NULL, NULL, null, null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Dark Brown', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Desert Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Emerald Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Forest Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Mossy Oak Country Roots', ARRAY[]::text[], NULL, NULL, null, null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Natural Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Oatmeal', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Olive Drab', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Olive Drab Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Patriot', ARRAY[]::text[], NULL, NULL, null, null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Radiant Violet', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Royal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Slate Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Tan 499', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'Teal Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('minus33', 'True Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://minus33.com/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Blue Denim', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Bright Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Brown Sugar', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Bubblegum Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Cacao', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Camel', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Caramel', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Cement', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Chocolate', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Dark Camel', ARRAY[]::text[], NULL, NULL, 'Beige', 'Dark', 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Dark Granite', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Fig', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Forest Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Granite', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Heather Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Invisible Dark Camel', ARRAY[]::text[], NULL, NULL, 'Beige', 'Dark', 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Invisible Granite', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Invisible Heathered Sea Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Invisible Timber', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Ivory', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Lavender', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Mist', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Oat', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Oatmeal', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Pure White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Red Apple', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Scarlet Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Shell', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Sky', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Smoke', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Steel Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Timber', ARRAY[]::text[], NULL, NULL, null, null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Washed Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('naadam', 'Wine', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://naadam.co/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Agave Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Backpacker Print', ARRAY[]::text[], NULL, NULL, null, null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Charcoal Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Cinnamon', ARRAY[]::text[], NULL, NULL, null, null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Dusty Lilac', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Gunmetal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Ice Flow', ARRAY[]::text[], NULL, NULL, null, null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Lagoon', ARRAY[]::text[], NULL, NULL, null, null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Mineral Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Overcast Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Rock Ridge', ARRAY[]::text[], NULL, NULL, null, null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Rum Raisin', ARRAY[]::text[], NULL, NULL, null, null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Sierra Cement', ARRAY[]::text[], NULL, NULL, null, null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Surplus Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('ridgemerino', 'Treetop', ARRAY[]::text[], NULL, NULL, null, null, 'https://ridgemerino.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Arugula', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Arugula/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/59', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Classic Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Cobalt', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Creme', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Dark Chocolate', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Grass', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Ice', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Lentil', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Military', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Purple Haze', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/Skylight', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Black/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Blush', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Bright Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Bright Yellow/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Classic Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Classic Blue/Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Classic Blue/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Cobalt/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Cobalt/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Creme/Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Dark Cherry', ARRAY[]::text[], NULL, NULL, 'Red', 'Dark', 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Dark Cherry/Creme', ARRAY[]::text[], NULL, NULL, 'Red', 'Dark', 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Dark Cherry/Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Dark Cherry/White', ARRAY[]::text[], NULL, NULL, 'White', 'Dark', 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Dark Chocolate', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Dark Chocolate/Black', ARRAY[]::text[], NULL, NULL, 'Black', 'Dark', 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Dark Chocolate/White', ARRAY[]::text[], NULL, NULL, 'White', 'Dark', 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Dove Grey/Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Graphite', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Graphite/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Grass', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Grass/Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Heather Dark Chocolate', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Heather Graphite', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Heather Grey/59', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Heather Grey/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Heather Grey/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Heather Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Heather Military', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/59', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/Bright Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/Creme', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/Dove Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/Limeade', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/Lotus Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/Pirate Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/Spearmint', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/Splits59 Los Angeles', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Indigo/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Latte', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Latte/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Lentil', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Lentil/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Lentil/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Limeade', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Limeade/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Lotus Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Lotus Red/Cobalt', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Lotus Red/Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Lt Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Military', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Military/Blush', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Military/Spearmint', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Nude', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Pirate Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Pirate Red/Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Purple Haze', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Purple Haze/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Purple Haze/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Sangria', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Sangria/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Skylight', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Skylight/Cobalt', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Skylight/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Spearmint', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Spearmint/Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Spearmint/Military', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Stone Blue/Graphite', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Strawberry/Lotus Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'Valencia', ARRAY[]::text[], NULL, NULL, null, null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/59', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Arugula', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Cobalt', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Grass', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Indigo Stripe', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Lotus Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Military', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Pirate Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Skylight', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('splits59', 'White/Spearmint', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://splits59.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Abyss', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Abyss Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Alloy', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Alloy Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Atmosphere', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Aubergine', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Blue Heron', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Blue Heron Heather', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Bold Bloom', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Bold Bloom Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Boundary Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Boundless', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Boundless Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Canyon Rock', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Canyon Rock Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Castlerock', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Cloudless', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Cowboy Coffee', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Deep Shade', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Denim', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Droplet', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Faded Oak', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Forage', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Forestline', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Forestline Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Grizzly Paw', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Horizon', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Hot Sauce', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Huckleberry Jam', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Lavender Haze', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Magnet', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Magnet Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Morning Frost', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Mountain Goat', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Mountain Goat Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Mountain Shadow', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Mountain Shadow Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Mudslide', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Mustang', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Nightshade', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Pebble', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Quiet Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Quiet Gray Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Raven', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Redrock', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Rosin', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Sage Flats', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Seedling', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Sierra Mauve', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Stormy Weather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Sun Valley', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Switchback', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Talus', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Terrain', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Trailblazer', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Vintage Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Vintage Indigo Heather', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Windchill', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('stio', 'Windchill Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.stio.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Beetle', ARRAY[]::text[], NULL, NULL, null, null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Black / Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Black / Neutral', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Black / White Grid', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Bone White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Classic Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Classic Blue / Bone White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Cobblestone', ARRAY[]::text[], NULL, NULL, null, null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Dark Brown', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Dark Pine', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Desert Palm', ARRAY[]::text[], NULL, NULL, null, null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Duck Camo', ARRAY[]::text[], NULL, NULL, null, null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Evergreen', ARRAY[]::text[], NULL, NULL, null, null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Forest / Bone White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Grid / Very Peri', ARRAY[]::text[], NULL, NULL, null, null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Huckleberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Maroon / Salsa', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Midnight', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Navy / Sahara', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Oil Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Oil Green / Dark Pine', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Olive / Dark Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', 'Dark', 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'River Blue / Brown Oak', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Spruce', ARRAY[]::text[], NULL, NULL, null, null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Stone Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Undyed', ARRAY[]::text[], NULL, NULL, null, null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Very Peri / Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Woodland / Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('topodesigns', 'Woodland / Terracotta', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://topodesigns.com/products.json', 0.75, false, 'migration:00742'),
  ('trew', 'Alpine Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://trewgear.com/products.json', 0.75, false, 'migration:00742'),
  ('trew', 'Anthracite', ARRAY[]::text[], NULL, NULL, null, null, 'https://trewgear.com/products.json', 0.75, false, 'migration:00742'),
  ('trew', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://trewgear.com/products.json', 0.75, false, 'migration:00742'),
  ('trew', 'Black Plum', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://trewgear.com/products.json', 0.75, false, 'migration:00742'),
  ('trew', 'Blackout', ARRAY[]::text[], NULL, NULL, null, null, 'https://trewgear.com/products.json', 0.75, false, 'migration:00742'),
  ('trew', 'Dust Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://trewgear.com/products.json', 0.75, false, 'migration:00742'),
  ('trew', 'Grangers', ARRAY[]::text[], NULL, NULL, null, null, 'https://trewgear.com/products.json', 0.75, false, 'migration:00742'),
  ('trew', 'Mighty Pine', ARRAY[]::text[], NULL, NULL, null, null, 'https://trewgear.com/products.json', 0.75, false, 'migration:00742'),
  ('trew', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://trewgear.com/products.json', 0.75, false, 'migration:00742')
on conflict do nothing;

-- US-1108 self-record footer.
insert into public.applied_migrations (version) values ('00742') on conflict do nothing;
