-- US-3125: twenty-three hunting, fishing, equestrian, formal and jewellery brands.
--
-- Catalogues read 2026-09-07 with scripts/ops/shopify-brand-harvest.mjs. Same
-- rules as 00734 and 00739: a colour on five or more products, a brand with at
-- least eight such colours and no more than 35% plain colour words, base_color
-- and shade from the brand's own facet where it publishes one and
-- aspect-normalize's family table otherwise.
--
-- NOBULL appears here for its COLOURS only. 00748 seeded the brand row and its
-- registered number, but the feed answered 503 on every attempt that day and
-- today it answered. The brand insert is a no-op; the 40 colours are the point.
--
-- -- REGISTERED NUMBERS: ELEVEN OF TWENTY-THREE ------------------------------
--
--     AFTCO             RN 77697    AFTCO MFG. CO., INC.
--     American Giant    RN 136653   AMERICAN GIANT INC.                   [APPAREL AND ACCESSORIES]
--     First Lite        RN 124933   FIRST LITE, LLC                       [WOOL GARMENTS]
--     Grundens          RN 119496   GRUNDENS USA LTD.                     [PANTS SOCKS HATS JACKETS]
--     Jones Snowboards  RN 160291   Jones Snowboards LLC                  [Men's Women's Children's apparel]
--     Kerrits           RN 107970   KERRITS ACTIVEWEAR INC.               [EQUESTRIAN APPAREL]
--     Radmor            RN 161432   Radmor Inc.                           [Men's apparel]
--     Simms             RN 103631   SIMMS FISHING PRODUCTS CORPORATION    [APPAREL]
--     Snow Peak         RN 171973   Snow Peak USA
--     The Black Tux     RN 143306   THE BLACK TUX, INC                    [TAILORED CLOTHING; TUXEDOS SUITS]
--     Ulla Johnson      RN 105177   ULLA VASILIA JOHNSON                  [LADIES GARMENTS]
--
-- Ulla Johnson is the first PERSONAL-NAME acceptance. The registrant is the
-- designer the label is named after, with a middle name the label drops. Adding
-- a middle name is an addition, not the replacement of a distinctive token, and
-- LADIES GARMENTS is the business. Simms is the Ibex tie-break again: five
-- registrants share the surname and only SIMMS FISHING PRODUCTS is a company in
-- the business the label is in.
--
-- AFTCO's product line reads "SYS_LIST_PROD", which is the register printing a
-- database placeholder rather than a category. Recorded as seen.
--
-- -- TWELVE REFUSED ----------------------------------------------------------
--
-- gorjana, KREWE, KUIU, Mejuri, Norse Projects and Private White V.C. return
-- NOTHING -- a legitimate absence.
--
-- Huk and Rouje are the substring trap, now nine and ten. "Huk" pulls three
-- HUK-A-POO companies and SHUKR LLC; "Rouje" pulls HASSAN BO-ROUJE-R DI. Both
-- look like clean hits and neither is the brand.
--
-- Dovetail Workwear (Portland Product Werks), POPFLEX (oGorgeous Inc) and
-- Truewerk (BAREROOT GROUP, INC) each return a registrant sharing no token with
-- the label.
--
-- Monos is the interesting refusal, and the reason is worth keeping. The
-- register holds an exact "Monos" -- but its product line is WOMEN'S APPAREL,
-- and Monos makes luggage. Compare CINCH, LLC in 00748, which was ACCEPTED on a
-- product-line mismatch: there the mismatch was inside apparel (activewear
-- against western denim), where the register is often narrow or stale. Here the
-- mismatch crosses industries, and a luggage maker has no reason to register
-- women's apparel. An exact name is not enough when the business is wrong.
--
-- -- COLOURS ----------------------------------------------------------------
--
-- Seeded: aftco (66), dovetailworkwear (19), firstlite (27), grundens (28), huk (61), jonessnowboards (18), kerrits (39), monos (34), radmor (11), simms (52), ullajohnson (46), nobull (40).
-- Palette refused, too few or too plain: gorjana (6), privatewhite (1), snowpeak (30, 60% plain), truewerk (17, 41% plain).
-- No colour survives the filter: americangiant (0 raw), krewe (1 raw), kuiu (0 raw), mejuri (0 raw), norseprojects (0 raw), popflex (32 raw), rouje (9 raw), theblacktux (0 raw).
--
-- Those brands still get a KB row, because the brand is worth knowing. An empty
-- colorway set means the feed does not say, never that the brand has one colour.
--
insert into public.brand_knowledge
  (brand_key, canonical_brand, aliases, category_focus, registered_numbers,
   notes, source_url, confidence, verified, updated_by)
values

  ('aftco', 'AFTCO', ARRAY['aftco','american fishing tackle co']::text[], ARRAY['fishing','outdoor','menswear','performance']::text[], ARRAY['RN 77697']::text[],
   'RN 77697 is FTC-record sourced -- registrant "AFTCO MFG. CO., INC.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.aftco.com/', 0.60, false, 'migration:00749'),
  ('americangiant', 'American Giant', ARRAY['american giant','americangiant']::text[], ARRAY['basics','heavyweight fleece','made in usa','menswear']::text[], ARRAY['RN 136653']::text[],
   'RN 136653 is FTC-record sourced -- registrant "AMERICAN GIANT INC.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.american-giant.com/', 0.60, false, 'migration:00749'),
  ('dovetailworkwear', 'Dovetail Workwear', ARRAY['dovetail','dovetail workwear']::text[], ARRAY['workwear','womenswear','trades','utility']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.dovetailworkwear.com/', 0.60, false, 'migration:00749'),
  ('firstlite', 'First Lite', ARRAY['first lite','firstlite']::text[], ARRAY['hunting','merino','camo','outdoor']::text[], ARRAY['RN 124933']::text[],
   'RN 124933 is FTC-record sourced -- registrant "FIRST LITE, LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.firstlite.com/', 0.60, false, 'migration:00749'),
  ('gorjana', 'Gorjana', ARRAY['gorjana','gorjana griffin']::text[], ARRAY['jewelry','accessories','layering']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.gorjana.com/', 0.60, false, 'migration:00749'),
  ('grundens', 'Grundens', ARRAY['grundens','grundén','grundens usa']::text[], ARRAY['fishing','foul weather gear','commercial','outdoor']::text[], ARRAY['RN 119496']::text[],
   'RN 119496 is FTC-record sourced -- registrant "GRUNDENS USA LTD.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.grundens.com/', 0.60, false, 'migration:00749'),
  ('huk', 'Huk', ARRAY['huk','huk gear','huk performance fishing']::text[], ARRAY['fishing','performance','menswear','outdoor']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.hukgear.com/', 0.60, false, 'migration:00749'),
  ('jonessnowboards', 'Jones Snowboards', ARRAY['jones','jones snowboards','jeremy jones']::text[], ARRAY['snowboard','outerwear','splitboard','outdoor']::text[], ARRAY['RN 160291']::text[],
   'RN 160291 is FTC-record sourced -- registrant "Jones Snowboards LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.jonessnowboards.com/', 0.60, false, 'migration:00749'),
  ('kerrits', 'Kerrits', ARRAY['kerrits','kerrits equestrian']::text[], ARRAY['equestrian','riding tights','womenswear','performance']::text[], ARRAY['RN 107970']::text[],
   'RN 107970 is FTC-record sourced -- registrant "KERRITS ACTIVEWEAR INC.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.kerrits.com/', 0.60, false, 'migration:00749'),
  ('krewe', 'KREWE', ARRAY['krewe','krewe eyewear']::text[], ARRAY['eyewear','sunglasses','new orleans','accessories']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.krewe.com/', 0.60, false, 'migration:00749'),
  ('kuiu', 'KUIU', ARRAY['kuiu']::text[], ARRAY['hunting','ultralight','camo','outdoor']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.kuiu.com/', 0.60, false, 'migration:00749'),
  ('mejuri', 'Mejuri', ARRAY['mejuri']::text[], ARRAY['jewelry','fine jewelry','accessories','everyday']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.mejuri.com/', 0.60, false, 'migration:00749'),
  ('monos', 'Monos', ARRAY['monos','monos luggage']::text[], ARRAY['luggage','travel','bags','accessories']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.monos.com/', 0.60, false, 'migration:00749'),
  ('norseprojects', 'Norse Projects', ARRAY['norse projects','norseprojects']::text[], ARRAY['menswear','scandinavian','utility','minimal']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.norseprojects.com/', 0.60, false, 'migration:00749'),
  ('popflex', 'POPFLEX', ARRAY['popflex','popflex active','blogilates']::text[], ARRAY['activewear','womenswear','leggings']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.popflexactive.com/', 0.60, false, 'migration:00749'),
  ('privatewhite', 'Private White V.C.', ARRAY['private white','private white vc','privatewhite']::text[], ARRAY['menswear','outerwear','british','made in manchester']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.privatewhitevc.com/', 0.60, false, 'migration:00749'),
  ('radmor', 'Radmor', ARRAY['radmor','radmor golf']::text[], ARRAY['golf','menswear','sustainable','polo']::text[], ARRAY['RN 161432']::text[],
   'RN 161432 is FTC-record sourced -- registrant "Radmor Inc.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.radmorgolf.com/', 0.60, false, 'migration:00749'),
  ('rouje', 'Rouje', ARRAY['rouje','rouje paris','jeanne damas']::text[], ARRAY['womenswear','french','dresses','parisian']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.rouje.com/', 0.60, false, 'migration:00749'),
  ('simms', 'Simms', ARRAY['simms','simms fishing','simms fishing products']::text[], ARRAY['fishing','waders','outdoor','performance']::text[], ARRAY['RN 103631']::text[],
   'RN 103631 is FTC-record sourced -- registrant "SIMMS FISHING PRODUCTS CORPORATION". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.simmsfishing.com/', 0.60, false, 'migration:00749'),
  ('snowpeak', 'Snow Peak', ARRAY['snow peak','snowpeak']::text[], ARRAY['outdoor','camping','japanese','apparel']::text[], ARRAY['RN 171973']::text[],
   'RN 171973 is FTC-record sourced -- registrant "Snow Peak USA". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.snowpeak.com/', 0.60, false, 'migration:00749'),
  ('theblacktux', 'The Black Tux', ARRAY['the black tux','theblacktux','black tux']::text[], ARRAY['formalwear','tuxedos','suits','menswear']::text[], ARRAY['RN 143306']::text[],
   'RN 143306 is FTC-record sourced -- registrant "THE BLACK TUX, INC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.theblacktux.com/', 0.60, false, 'migration:00749'),
  ('truewerk', 'Truewerk', ARRAY['truewerk','true werk']::text[], ARRAY['workwear','technical','trades','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.truewerk.com/', 0.60, false, 'migration:00749'),
  ('ullajohnson', 'Ulla Johnson', ARRAY['ulla johnson','ullajohnson']::text[], ARRAY['womenswear','dresses','contemporary','artisanal']::text[], ARRAY['RN 105177']::text[],
   'RN 105177 is FTC-record sourced -- registrant "ULLA VASILIA JOHNSON". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.ullajohnson.com/', 0.60, false, 'migration:00749'),
  ('nobull', 'NOBULL', ARRAY['nobull','no bull','nobull project']::text[], ARRAY['training','footwear','activewear','crossfit']::text[], ARRAY['RN 151714']::text[],
   'RN 151714 is FTC-record sourced -- registrant "NOBULL, INC.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.nobullproject.com/', 0.60, false, 'migration:00749')
on conflict (brand_key) do nothing;

insert into public.brand_colorways
  (brand_key, color_name, aliases, hex, years, base_color, shade,
   source_url, confidence, verified, updated_by)
values

  ('aftco', 'Airy Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Airy Blue Heather', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Aqua Glass', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Assortment', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Athletic Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Azure Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Bay Leaf Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Bering Sea', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Bering Sea Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Black Camo', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Black Current Camo', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Black Heather', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Black Storm Camo', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Blue Mack', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Blue Shadow', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Bungee Cord', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Burnt Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Celestial', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Cement', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Charcoal Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Chrome', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Clearwater', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Corsair Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Dark Sand', ARRAY[]::text[], NULL, NULL, 'Beige', 'Dark', 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Dark Sea Heather', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Dusk', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Dusk Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Forest Camo', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Forest Grouper Camo', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Gold', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Green Mack', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Green OG Camo', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Gun Metal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Harbor Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Harbor Gray Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Ink', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Light Blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Midnight Heather', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Milky Blue Heather', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Naval', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Navy Grander Camo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Navy Heather', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'OG Bottomland', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Olive Current Camo', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Oyster Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Oyster Gray Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Pastel Turquoise', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Pelican', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Seafoam Heather', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Splish Splash', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Splish Splash Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Stargazer Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Steel', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'Steel Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('aftco', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.aftco.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Atlantic Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Carbon Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Cement Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Dovetail Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Elderberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Elderberry (Maroon)', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Indigo Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Kelp Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Khaki Canvas', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Kodiak Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Moss Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'No Fade Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Paprika Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Saddle Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Sawdust Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('dovetailworkwear', 'Uniform Navy Canvas', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.dovetailworkwear.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Army', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Ash Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Athletic Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Charcoal Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Conifer', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Coyote Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Dark Moss', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Dry Earth', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'First Lite Cerca', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'First Lite Cipher', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'First Lite Darkwater', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'First Lite Fusion', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'First Lite Specter', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'First Lite Typha', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Grey Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Hunters Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Military Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Military Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Saddle', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Tan', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Terra', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('firstlite', 'Walnut', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.firstlite.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Anchor', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Athletic Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Blue Abyss', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Coastal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Dark Navy', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Dark Slate', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Deep Depths', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Deep Lichen Green', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Grey Mist', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Heather Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Hi-Vis Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Loden', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Metal', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Otter', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Oyster', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Red Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Surf', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Turtle Grass', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Whiskey', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('grundens', 'Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.grundens.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Anchor Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Aqua Haze Heather', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Black Heather', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Black Tideloom Camo', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Blue Shadow', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Bright Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Caicos', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Cerulean', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Coastal Drift', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Coastal Drift Camo', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Coral Reef', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Dark Shadow', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Egret', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Egret Tideloom Camo', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Harbor Mist', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Heron Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'KC Army Camo', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Marine Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Marine Blue Heather', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Marolina Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Mineral Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Moss', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Moss Heather', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Mossy Oak Bottomland', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Mossy Oak Regatta', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Mossy Oak Seagrass', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Mossy Oak Seagull', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Mud', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Mudminnow', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Naval Academy', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Navy Stars', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Neon Coral', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Night Owl', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'North Atlantic', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Oleander', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Oleander Ombre', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Pale Algae', ARRAY[]::text[], NULL, NULL, null, 'Light', 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Reefline', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Regatta', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'River Rock Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Sea Storm', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Sea Storm Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Seagrass', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Seagull', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Seagull Camo', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Sharkskin', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Sharkskin Estuary Camo', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Sharkskin Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Silver Birch Palm', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Spanish Moss', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Starfish', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Starfish Tideloom Camo', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Stormy Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Stormy Blue Heather', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Stormy Blue Tideloom Camo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Vintage Chartreuse', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'Volcanic Ash', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('huk', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.hukgear.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'ARCTIC BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'Atlantic Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'Cloud White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'Coffee Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'Deep Coral', ARRAY[]::text[], NULL, NULL, 'Pink', 'Dark', 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'ECLIPSE BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'Eclipse Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'GLACIER GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'LAVA RED', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'Lime Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'MIDNIGHT GREEN', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'MOSS GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'None', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'Peak Camo', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'SMOKE GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'STEALTH BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('jonessnowboards', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.jonessnowboards.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'AMBERSPICE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'BERRY BLAST', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'BERRY BRUSHSTROKES', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'BLACK CHEVRON BITS', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'BLACK SOLID', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'BLACK/ BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'BLUSH LUCKY CASCADE', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'BURGUNDY CHEVRON BITS', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'CARBON', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'CAROLINA BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'DUSTY BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'ELDERBERRY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'ELDERBERRY FANTASY FILLIES', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'GALAXYBLUE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'JASPER', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'JASPER HORSESHOE HONEYCOMB', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'LAPIS', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'MIST BRUSHSTROKES', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'MOCHA', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'NAVY CHEVRON BITS', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'NIGHTFALL', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'NIGHTSKY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'OASIS LUCKY CASCADE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'PINE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'PLUMNOIR', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'PURPLE', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'SAGE CHEVRON BITS', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'SAND', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'SHORELINE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'SOFT WHITE POSH PAISLEY', ARRAY[]::text[], NULL, NULL, 'White', 'Light', 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'TAN', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'THISTLE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'TURQUOISE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'VELVET PLUM', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'WHITE/ BIT OF LUCK', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('kerrits', 'WILDORCHID', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.kerrits.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Adobe Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Arles Blue (Glossy)', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Aspen Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Blue Haze', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Carbon Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Carbon Black (Vegan Leather)', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Caviar Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Champagne', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Champagne Gold', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Citrus (Glossy)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Desert Taupe', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Dover Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Elemental Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Ivory (Vegan Leather)', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Juniper Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Mahogany (Vegan Leather)', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Midnight Black', ARRAY[]::text[], NULL, NULL, 'Black', 'Dark', 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Mint', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Mulberry (Glossy)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Obsidian', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Ocean Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Olive Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Orchid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Oxford Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Rose Quartz', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Saddle Tan (Vegan Leather)', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Sage Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Stellar White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Storm Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Terracotta', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('monos', 'Terrazzo Graphite', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.monos.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'Baltic', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'Birch', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'Blue Graphite', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'Dark Navy', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'Sky', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'Snow White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'True Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('radmor', 'White Out', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.radmorgolf.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Albacore', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Aspen', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Baltic Amber', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Basalt', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Bay Leaf', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Bimini Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Bistre', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Black Heather', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Bronzeback', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Burnished Clay', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Carbon', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Charcoal Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Cinder', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Cobia', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Colorless', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Dark Stone', ARRAY[]::text[], NULL, NULL, 'Beige', 'Dark', 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Dolomite', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Driftwood', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Earthenware', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Gunmetal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Hickory', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Jasper', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Loden', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Loden Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Lunar Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Military Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Overcast', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Pale Pine', ARRAY[]::text[], NULL, NULL, null, 'Light', 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Pebble Steel', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Pewter', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Roses', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Selvedge', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Sepia', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Shale', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Silt', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Simms Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Sky Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Slate', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Smokey Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Steel', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Steel Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Steel Blue Heather', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Sterling', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Stone', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Stonefly', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Sturgeon', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Tahitian Pearl', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Tallow', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('simms', 'Willow', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.simmsfishing.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Abalone', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Agate', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Almond', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Beryl', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Bisque', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Blush', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Cerise', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Chamomile', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Ciel', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Clove', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Cognac', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Cowrie', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Creme', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Danube', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Dusk', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Evening Bloom', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Gold', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Heron', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Ivory', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Lapis', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Leopard', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Lichen', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Light Gold', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Loden', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Midnight', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Miele', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Militaire', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Moon Petal', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Moontide', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Natural', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Nature Abhors A Vacuum', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Nile', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Noir', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Oasis', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Orchid', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Pearl', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Pearled Ivory', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Powder', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Pristine', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Prussian', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Shibori Wave', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Sierra', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Summer Garden', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Tigris', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('ullajohnson', 'Western Dream', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.ullajohnson.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Acorn', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Aqua Wash', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Black Gum', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Blue Haze', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Cayenne', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Charcoal Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Classic White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Classic White Gum', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Classic White Zest', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Coastal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Crimson', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Dark Army', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Equestrian Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Fallen Rock', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Flare', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Fog', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Gray Jungle Camo', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Harbor', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Heather Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Jet Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Light Blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Light Gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Lunar Rock', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Midnight', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Night Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Pear', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Punch', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Silver Pine', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Soft Pink', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Surf', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Tactical Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Taupe', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Triple Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Vivid Fuchsia', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'White Gum', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749'),
  ('nobull', 'Zest', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nobullproject.com/products.json', 0.75, false, 'migration:00749')
on conflict do nothing;

-- US-1108 self-record footer.
insert into public.applied_migrations (version) values ('00749') on conflict do nothing;
