-- US-3125: fifteen more brands, and colorways for the 5 whose palettes earn it.
--
-- Catalogues read 2026-09-06 with scripts/ops/shopify-brand-harvest.mjs. Same
-- rules as 00734 and 00739 throughout: a colour on five or more products, a
-- brand with at least eight such colours and no more than 35%% plain colour
-- words, base_color and shade from the brand's own facet where it publishes one
-- and aspect-normalize's family table otherwise.
--
-- -- REGISTERED NUMBERS: FIVE OF NINETEEN -----------------------------------
--
--     Duck Camp           RN 167300   Duck Camp LLC
--     Katin               RN 92787    KATIN USA, INC.
--     Marine Layer        RN 140892   MARINE LAYER INC
--     Ministry of Supply  RN 160361   Ministry of Supply
--     Outerknown          RN 144067   OUTERKNOWN LLC
--
-- The other fourteen are REFUSED rather than guessed, and the register makes the
-- reason plain each time. Darn Tough, OluKai and Rothy's return NOTHING, which
-- is a legitimate absence. The rest return a registrant that is not the label:
--
--     Howler Brothers  ->  HEARD DESIGN LLC
--     Linksoul         ->  TEEDUP DF, LLC
--     Mack Weldon      ->  BDB VENTURES, INC.
--     Psycho Bunny     ->  GOD AND GOLD
--     Roark            ->  three hits, none of them the travel label
--
-- Each is probably the operating company. "Probably" is what the Longchamp trap
-- is made of, so each waits for a source that says so.
--
-- -- SIX BRANDS PUBLISH NO COLOUR OPTION AT ALL ------------------------------
--
-- dagnedover, girlfriendcollective, jennikayne, koio carry sizes and NO Color option at all.
-- cuyana (10 colours, none on 5+ products), dl1961 (17 colours, none on 5+ products) publish colours that never recur. They
-- still get a brand row -- the brand is worth knowing -- and their colorways
-- wait for a different source. An empty colorway table for them means the feed
-- does not say, not that the brand has one colour.
--
-- Seeded colours: away (140), cultgaia (61), goodamerican (29), setactive (68), staud (94).
-- Palette refused: alexmill (19 colours, 47%% plain).
-- Palette refused: grayers (14 colours, 43%% plain).
-- Palette refused: olivercabell (2 colours).
-- Palette refused: statebags (14 colours, 50%% plain).
--

insert into public.brand_knowledge
  (brand_key, canonical_brand, aliases, category_focus, registered_numbers,
   notes, source_url, confidence, verified, updated_by)
values

  ('alexmill', 'Alex Mill', ARRAY['alex mill','alexmill']::text[], ARRAY['menswear','womenswear','chore coat','casual']::text[], ARRAY['RN 140714']::text[],
   'RN 140714 is FTC-record sourced -- registrant "ALEX MILL COMPANY LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.alexmill.com/', 0.60, false, 'migration:00741'),
  ('away', 'Away', ARRAY['away','away travel','awaytravel']::text[], ARRAY['luggage','travel','suitcase','bags']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.awaytravel.com/', 0.60, false, 'migration:00741'),
  ('cultgaia', 'Cult Gaia', ARRAY['cult gaia','cultgaia']::text[], ARRAY['womenswear','sculptural','bags','resort']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://cultgaia.com/', 0.60, false, 'migration:00741'),
  ('cuyana', 'Cuyana', ARRAY['cuyana']::text[], ARRAY['womenswear','leather','bags','fewer better']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.cuyana.com/', 0.60, false, 'migration:00741'),
  ('dagnedover', 'Dagne Dover', ARRAY['dagne dover','dagnedover']::text[], ARRAY['bags','neoprene','work bags','travel']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.dagnedover.com/', 0.60, false, 'migration:00741'),
  ('dl1961', 'DL1961', ARRAY['dl1961','dl 1961']::text[], ARRAY['denim','sustainable','womenswear','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.dl1961.com/', 0.60, false, 'migration:00741'),
  ('girlfriendcollective', 'Girlfriend Collective', ARRAY['girlfriend collective','girlfriend','girlfriendcollective']::text[], ARRAY['activewear','recycled','leggings','inclusive sizing']::text[], ARRAY['RN 149694']::text[],
   'RN 149694 is FTC-record sourced -- registrant "GIRLFRIEND COLLECTIVE, LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://girlfriend.com/', 0.60, false, 'migration:00741'),
  ('goodamerican', 'Good American', ARRAY['good american','goodamerican']::text[], ARRAY['denim','womenswear','inclusive sizing']::text[], ARRAY['RN 151301']::text[],
   'RN 151301 is FTC-record sourced -- registrant "GOOD AMERICAN, LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.goodamerican.com/', 0.60, false, 'migration:00741'),
  ('grayers', 'Grayers', ARRAY['grayers']::text[], ARRAY['menswear','shirts','washed cotton','casual']::text[], ARRAY['RN 139535','RN 136782']::text[],
   'RN 139535 is FTC-record sourced -- registrant "GRAYERS AMERICA INC / GRAYERS USA, LTD". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://grayers.com/', 0.60, false, 'migration:00741'),
  ('jennikayne', 'Jenni Kayne', ARRAY['jenni kayne','jennikayne']::text[], ARRAY['womenswear','california','knitwear','home']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://jennikayne.com/', 0.60, false, 'migration:00741'),
  ('koio', 'KOIO', ARRAY['koio']::text[], ARRAY['footwear','sneakers','italian leather']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://koio.co/', 0.60, false, 'migration:00741'),
  ('olivercabell', 'Oliver Cabell', ARRAY['oliver cabell','olivercabell']::text[], ARRAY['footwear','sneakers','transparent pricing']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://olivercabell.com/', 0.60, false, 'migration:00741'),
  ('setactive', 'Set Active', ARRAY['set active','setactive']::text[], ARRAY['activewear','womenswear','setsculpt','loungewear']::text[], ARRAY['RN 172110']::text[],
   'RN 172110 is FTC-record sourced -- registrant "Set active llc". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://setactive.co/', 0.60, false, 'migration:00741'),
  ('statebags', 'STATE Bags', ARRAY['state bags','statebags','state']::text[], ARRAY['bags','backpacks','give-back']::text[], ARRAY['RN 144461']::text[],
   'RN 144461 is FTC-record sourced -- registrant "STATE BAGS PUBLIC BENEFIT CORP.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://statebags.com/', 0.60, false, 'migration:00741'),
  ('staud', 'STAUD', ARRAY['staud']::text[], ARRAY['womenswear','dresses','bags','contemporary']::text[], ARRAY['RN 154138']::text[],
   'RN 154138 is FTC-record sourced -- registrant "Staud Inc.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://staud.clothing/', 0.60, false, 'migration:00741')
on conflict (brand_key) do nothing;

insert into public.brand_colorways
  (brand_key, color_name, aliases, hex, years, base_color, shade,
   source_url, confidence, verified, updated_by)
values

  ('away', '6-9 Looks', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'ASU ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Alien Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Amaro Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Arctic Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Argentina (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Atomic Celery', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Auburn University ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Berry Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Black Seagrass', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Black Tie', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Blush Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Brazil (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Burgundy Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Butterfly Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Buzz Lightyear', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Buzz Lightyear Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Camel Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Canada', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Canada (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Chase Badge Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Cherry Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Cherry Red (Gloss)', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Clay Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Clear/Cherry Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Clear/Island Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Clear/Jet Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Clear/Navy Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Clear/Salt White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Clemson ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Cloud Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Clubhouse Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Coast Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Cognac Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Cotton Candy Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Cream White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Cruise', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Desert Tan', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Dragonfly Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Duke ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'England (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Espresso Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'FSU ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Flamingo Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Forest Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Forever', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'France (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Froggy Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Fruit Punch', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Galaxy Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Garden Mix', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Germany (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Glacial Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Glazed Lavender Haze Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Glazed Matcha Milk Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Glazed Opal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Golden Hour Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Honeydew Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Honeymoon', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Hot Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Howard University ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Island Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Ivy Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Japan (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Jessie', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Jessie Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Jet Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'LSU ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Lavender Haze Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Lilypad', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Marigold Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Marshmallow White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Matcha Milk Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Mexico', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Misty Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'My Baggage', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'My Baggage (Jet Black)', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Nautical', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Navy Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Nordic Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Ole Miss ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Olive Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'On Tour', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Onyx Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Opal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Oxblood Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Pearl White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Penn State University ™', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Peony Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Pink Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Poppy Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Portugal (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Rose Gold', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Ruby Haze', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Ruby Haze & Glacial Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Saddle Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Sage Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Salt White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Salt White (Gloss)', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Salt White (Textured Nylon)', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Scenic Route', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Sea Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Seaside Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Skye Pilot Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Something Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Sorbet Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'South Korea (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Space Ranger White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Spain (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Splash Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Spring Mix', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Stormy Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Stormy Teal & Arctic Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Sunshine Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Tango Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'The University of Alabama ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'The University of Arizona ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'The University of Texas', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'The Words', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Tidal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Tide Line Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Toy Story 5', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Transit Canvas Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Transit Canvas Tan', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Translucent Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Translucent Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'UCLA ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'UConn ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'USA', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'USA (Flag)', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'University of Colorado ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'University of Florida ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'University of Maryland ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'University of Michigan ™', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'University of North Carolina ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'University of Washington ®', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Vivid Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'White Seagrass', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('away', 'Woody Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.awaytravel.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'ANTIQUE BRASS', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'ANTIQUE SILVER', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'ANTIQUE WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'BEACH', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'BRASS', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'BRUSHED BRASS', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'CANYON', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'CHEETAH', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'CHIVE', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'CLEAR', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'COASTAL', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'DAFFODIL', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'DEEP LAKE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'DEEP PASTURE', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'DOMINGA', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'DOVE', ARRAY[]::text[], NULL, NULL, null, null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'ETCHED FLORAL', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'GHERMEZ', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'GOLD', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'GOLD FOILED WOOD', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'IBIZA', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'IBIZA TURQUOISE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'IVORY', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'JAVA', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'LARGE SADDLE STRIPE', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'LIGHT GOLD', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'LUWAK', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'LUWAK MULTI', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'MARIGOLD', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'MERLOT', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'MOTHER OF PEARL', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'NATURAL', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'NYMPH', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'OFF WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'PEARL', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'PEPPER', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'PETAL PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'PINK MULTI', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'RICH CLAY', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'RIO BEACH PRINT', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'ROSEMARY', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'ROSEMARY MULTI', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'SADDLE', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'SAND', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'SAND DOLLAR', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'SESAME', ARRAY[]::text[], NULL, NULL, null, null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'SESAME MULTI', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'SMALL DOT DEEP LAKE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'SMALL SADDLE STRIPE', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'STONE WASH', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'SWEET PEA', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'TANGELO', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'TIDE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'TOASTED CARAMEL', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'TURQUOISE MULTI', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'VERMILION', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'VINTAGE BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'WALNUT', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'WARM HAZE', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('cultgaia', 'WILD DAHLIA', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://cultgaia.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'BARK003', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'BERRY NOIR', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'BLACK001', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'BLUE004', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'BROWN TIGER', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'CAFE CLAY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'CHALK', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'CLOUD WHITE001', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'ESPRESSO', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'FIG007', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'FOREST GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'HEATHER GREY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'HORIZON INK', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'INDIGO1153', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'INDIGO1187', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'INDIGO1233', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'INDIGO316', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'INDIGO446', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'INDIGO511', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'LUCKY LEOPARD001', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'MOSSWELL', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'NEW NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'NEW NAVY002', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'RINSE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'SKY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'SOFT SHELL', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('goodamerican', 'WHITE001', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.goodamerican.com/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Analog', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Aqua', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'BOARDWALK', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Beetle', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Betta', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Blanc', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Bloom', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Butter', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Buttercream', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'COASTER', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Confetti', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'DOT', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'DRIFTWOOD', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Espresso', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'FERRIS', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'FRECKLE', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Firework', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Fog Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Grain', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'HAMMOCK', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'HEATWAVE', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Haven', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Hibiscus', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'IBIZA', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Icing', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Julep', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'LISBON', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Ladybug', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Lagoon', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Lawn', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Lo-fi', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Maraschino', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Marlin', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Maui', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'OLE', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Onyx', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Orange Soda', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Orca', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Otter', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'PALMA', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'PALMETTO', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'POPCORN', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'POPSICLE', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Peach', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Piña', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'REEF', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'RIBBON', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'RODEO', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'ROMA', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'SAINT TROPEZ', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'SPECKLE', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'SUNRISE', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'SWEET TEA', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Sepia', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Shoreline', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Spades', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Sparkler', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Spearmint', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Swirl', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'TOUCAN', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Taffy', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Tropics', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'VESPA', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Vista', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Washed', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('setactive', 'Worn', ARRAY[]::text[], NULL, NULL, null, null, 'https://setactive.co/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ARTIST STRIPE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLACK CROCO', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLACK SATIN', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLACK SNAKE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLACK SUEDE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLACK WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLUE HAZE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLUE HAZE MULTI', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLUE TOILE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BLUSH', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BRONZE', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BUTTER', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BUTTER STUDS', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'BUTTERFLY SKY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CAMEL', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CARDINAL', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CASHEW', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CHARTREUSE', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CHEETAH', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CHERRY', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CIELO', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CIGAR', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CITRON', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CLIFFSIDE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'COBALT', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'CREAM', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'DARK CHOCOLATE', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'DARK OAK', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'DESERT', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'EARTH', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ENDLESS SUMMER', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ESPRESSO', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ESPRESSO BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ESPRESSO CROCO', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ESPRESSO DISTRESSED', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ESPRESSO SNAKE', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ESPRESSO STUDS', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ESPRESSO SUEDE', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'FAWN', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'FAWN HAIRCALF', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'FLAME', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'GLASSWORK', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'HAPPY SACK', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'HEATHER GREY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'HOUNDSTOOTH', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'HUNTINGTON STRIPE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'INDIGO', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'IVORY', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'JAVA', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'LEOPARD', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'MILLEFIORE 2.0', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'MONDAY STRIPE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'NATURAL', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'NATURAL TAN', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ORCHID', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'PAINTED FOULARD', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'PEAR', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'PORCINI', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'RED ROSE', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'RED ZONE', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'REDONDO STRIPE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'ROUGE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SANDROSE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SEAPORT STRIPE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SERRE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SILVER', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SKATE STRIPE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SKY TOILE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SNAKE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SPROUT', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'STATIC', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'STONE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SUNSHINE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SUPERBLOOM', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SUPERBLOOM SCARF', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SWEETHEART', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'SYRAH', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TABAC', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TABAC SUEDE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TAN', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TAN SUEDE', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TANGELO', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TAUPE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TIDAL SHELL', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TOMATO', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TORTOISE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TRUFFLE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'TRUFFLE SUEDE', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'VINTAGE WASH', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'WHITE SNAKE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741'),
  ('staud', 'WISTERIA', ARRAY[]::text[], NULL, NULL, null, null, 'https://staud.clothing/products.json', 0.75, false, 'migration:00741')
on conflict do nothing;

-- US-1108 self-record footer.
insert into public.applied_migrations (version) values ('00741') on conflict do nothing;
