-- US-3125: seventeen DTC womenswear, training and footwear brands.
--
-- Catalogues read 2026-09-07 with scripts/ops/shopify-brand-harvest.mjs. Same
-- rules as 00734 and 00739: a colour on five or more products, a brand with at
-- least eight such colours and no more than 35% plain colour words, base_color
-- and shade from the brand's own facet where it publishes one and
-- aspect-normalize's family table otherwise.
--
-- Alala also returned a feed and is NOT here: it answered 200 with ZERO
-- products, which is a live storefront with nothing published rather than a
-- catalogue. No products means no evidence, so no row.
--
-- -- REGISTERED NUMBERS: TWO OF SEVENTEEN, AND THAT IS THE FINDING -----------
--
--     Hill House Home   RN 177847   Hill House Home Inc
--     Terez             RN 148284   TEREZ UNIVERSE LLC   [LEGGINGS BOTTOMS SKIRTS TOPS DRESSES]
--
-- Thirteen of the other fifteen return NOTHING AT ALL -- Born Primitive, Dissh,
-- Edikted, GREATS, MESHKI, NVGTN, Ryderwear, Selkie, SIR., Velasca, Virus
-- International, WOLACO and Year of Ours.
--
-- That is not a bad batch, it is a property of the batch. Every previous run
-- drew on heritage and outdoor labels, where registration is old and normal, and
-- returned RNs for roughly half. This run is social-first DTC brands, most of
-- them founded after 2015 and several selling from outside the US, and the hit
-- rate collapses to two in seventeen. An absent RN says something about the
-- brand's AGE and SUPPLY CHAIN, not about whether it is real.
--
-- Hill House Home's RN 177847 is the highest number this corpus has seen, which
-- is consistent: a 2016 brand that registered recently sits at the top of the
-- sequence. That is the 00750 vintage rule running in the other direction, and
-- it is the reassuring case rather than the suspicious one.
--
-- -- TWO REFUSED -------------------------------------------------------------
--
-- Darc Sport is the substring trap, fifteen: DARCEL SPORTSWEAR INC, and a WPL
-- number rather than an RN at that.
--
-- POSSE refines the Cinch rule from 00748 rather than repeating it. The register
-- holds Posse Apparel LLC, an exact name plus a generic word and the only exact
-- match among four substring hits. Its product line is Men's apparel; POSSE is
-- an Australian womenswear label that makes no menswear. 00748 ACCEPTED a
-- product-line mismatch for Cinch because "women's activewear" NARROWS a brand
-- that does make womenswear. Men's-only for a womenswear-only label is not a
-- narrowing, it is a contradiction.
--
-- -- COLOURS ----------------------------------------------------------------
--
-- Seeded: edikted (106), hillhouse (65), sirthelabel (21), terez (17), velasca (47), virusintl (28), wolaco (9).
-- Palette refused, too few or too plain: greats (3), yearofours (7).
-- No colour survives the filter: bornprimitive (0 raw), darcsport (0 raw), dissh (0 raw), meshki (0 raw), nvgtn (0 raw), posse (0 raw), ryderwear (0 raw), selkie (6 raw).
--
insert into public.brand_knowledge
  (brand_key, canonical_brand, aliases, category_focus, registered_numbers,
   notes, source_url, confidence, verified, updated_by)
values

  ('bornprimitive', 'Born Primitive', ARRAY['born primitive','bornprimitive']::text[], ARRAY['training','crossfit','activewear','veteran-owned']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://bornprimitive.com/', 0.60, false, 'migration:00752'),
  ('darcsport', 'Darc Sport', ARRAY['darc sport','darcsport','darc']::text[], ARRAY['training','streetwear','bodybuilding','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://darcsport.com/', 0.60, false, 'migration:00752'),
  ('dissh', 'Dissh', ARRAY['dissh']::text[], ARRAY['womenswear','australian','linen','contemporary']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://dissh.com/', 0.60, false, 'migration:00752'),
  ('edikted', 'Edikted', ARRAY['edikted']::text[], ARRAY['womenswear','fast fashion','denim','going out']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://edikted.com/', 0.60, false, 'migration:00752'),
  ('greats', 'GREATS', ARRAY['greats','greats brand']::text[], ARRAY['sneakers','footwear','leather','brooklyn']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.greats.com/', 0.60, false, 'migration:00752'),
  ('hillhouse', 'Hill House Home', ARRAY['hill house','hill house home','hillhouse','nap dress']::text[], ARRAY['womenswear','nap dress','home','cotton']::text[], ARRAY['RN 177847']::text[],
   'RN 177847 is FTC-record sourced -- registrant "Hill House Home Inc". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://hillhousehome.com/', 0.60, false, 'migration:00752'),
  ('meshki', 'MESHKI', ARRAY['meshki']::text[], ARRAY['womenswear','going out','bodycon','australian']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://meshki.us/', 0.60, false, 'migration:00752'),
  ('nvgtn', 'NVGTN', ARRAY['nvgtn','navigation']::text[], ARRAY['activewear','leggings','womenswear','seamless']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://nvgtn.com/', 0.60, false, 'migration:00752'),
  ('posse', 'POSSE', ARRAY['posse','posse store']::text[], ARRAY['womenswear','australian','linen','resort']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://posse.com/', 0.60, false, 'migration:00752'),
  ('ryderwear', 'Ryderwear', ARRAY['ryderwear','ryder wear']::text[], ARRAY['training','bodybuilding','footwear','activewear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.ryderwear.com/', 0.60, false, 'migration:00752'),
  ('selkie', 'Selkie', ARRAY['selkie','selkie collection','puff dress']::text[], ARRAY['womenswear','puff dress','whimsical','size inclusive']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://selkiecollection.com/', 0.60, false, 'migration:00752'),
  ('sirthelabel', 'SIR.', ARRAY['sir','sir the label','sirthelabel']::text[], ARRAY['womenswear','australian','linen','contemporary']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.sirthelabel.com/', 0.60, false, 'migration:00752'),
  ('terez', 'Terez', ARRAY['terez']::text[], ARRAY['activewear','leggings','prints','kids']::text[], ARRAY['RN 148284']::text[],
   'RN 148284 is FTC-record sourced -- registrant "TEREZ UNIVERSE LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://terez.com/', 0.60, false, 'migration:00752'),
  ('velasca', 'Velasca', ARRAY['velasca']::text[], ARRAY['footwear','italian','leather','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.velasca.com/', 0.60, false, 'migration:00752'),
  ('virusintl', 'Virus International', ARRAY['virus','virus intl','virus international']::text[], ARRAY['compression','training','recovery','activewear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.virusintl.com/', 0.60, false, 'migration:00752'),
  ('wolaco', 'WOLACO', ARRAY['wolaco','wo la co']::text[], ARRAY['activewear','menswear','pocketed shorts','new york']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://wolaco.com/', 0.60, false, 'migration:00752'),
  ('yearofours', 'Year of Ours', ARRAY['year of ours','yearofours','yoo']::text[], ARRAY['activewear','womenswear','ribbed','athleisure']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://yearofours.com/', 0.60, false, 'migration:00752')
on conflict (brand_key) do nothing;

insert into public.brand_colorways
  (brand_key, color_name, aliases, hex, years, base_color, shade,
   source_url, confidence, verified, updated_by)
values

  ('edikted', 'AQUA', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BEIGE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLACK AND GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLACK AND WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLACK WASHED', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLACK-AND-GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLACK-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLACK-WASHED', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLUE AND WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLUE VINTAGE WASHED', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLUE WASHED', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLUE-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLUE-VINTAGE-WASHED', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BLUE-WASHED', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BORDU', ARRAY[]::text[], NULL, NULL, null, null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BROWN', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BROWN WASHED', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BROWN-AND-PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BROWN-WASHED', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BURGUNDY', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BURGUNDY-AND-PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'BURGUNDY-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'CAMEL', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'CHARCOAL', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'CORAL', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'CREAM', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'CREAM AND NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'DARK BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'DARK BROWN', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'DARK GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'DARK-BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'DARK-BLUE-WASHED', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'DARK-BROWN', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'DARK-GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'DARK-GRAY-MELANGE', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'FUCHSIA', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'GOLD', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'GRAY MELANGE', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'GRAY WASHED', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'GRAY-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'GRAY-MELANGE', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'GRAY-MELANGE-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'HAMRA', ARRAY[]::text[], NULL, NULL, null, null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'HOT-PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'INDIGO BLUE RAW WASHED', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'INDIGO-BLUE-RAW-WASHED', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'IVORY', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LEOPARD', ARRAY[]::text[], NULL, NULL, null, null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT GRAY MELANGE', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT PINK', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT-BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT-BLUE-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT-BLUE-WASHED', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT-GRAY', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT-GRAY-MELANGE', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT-GRAY-MELANGE-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT-PINK', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT-PINK-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LIGHT-YELLOW', ARRAY[]::text[], NULL, NULL, 'Yellow', 'Light', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'LILAC', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'MAROON', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'MAUVE', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'MEDIUM-BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', 'Medium', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'MEDIUM-BLUE-WASHED', ARRAY[]::text[], NULL, NULL, 'Blue', 'Medium', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'MEDIUM-VINTAGE-INDIGO', ARRAY[]::text[], NULL, NULL, 'Blue', 'Medium', 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'MINT', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'MIX', ARRAY[]::text[], NULL, NULL, null, null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'MOCHA', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'NAVY AND CREAM', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'NAVY AND WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'NAVY-AND-CREAM', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'NAVY-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'NUDE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'OLIVE', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'ORANGE', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'OXFORD', ARRAY[]::text[], NULL, NULL, null, null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'PINK AND WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'PINK-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'PLUM', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'PURPLE', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'RED', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'RED AND WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'RED-AND-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'SAGE', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'SILVER', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'STONE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'TAN', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'TAUPE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'TORTOISE', ARRAY[]::text[], NULL, NULL, null, null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'TURQUOISE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'WHITE AND BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'WHITE AND PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'WHITE-AND-BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'WHITE-AND-BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'WHITE-AND-PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'WINE', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('edikted', 'YELLOW', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://edikted.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Alphabet', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Berry Paisley Scarf', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Black Tonal Seersucker', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Black/Sand Gingham', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Arcadia Border', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Botanical', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Corsica Paisley', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Floral Monkey Trellis', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Petal Stripe', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Rainbow Fish', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Sherwood Forest Monkey', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Stripe', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Trellis', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue Vine Stripe', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue/Green Stripe', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue/Red Gingham', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Blue/White Stripe', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Bluebell Waltz', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Bluebird Tonal Seersucker', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Camo Fish', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Chedworth Paisley Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Chedworth Paisley Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Cherry Trellis Broderie', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Chocolate Gingham', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Cognac Gingham', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Coral Corsica Paisley', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Cornflower Ditsy Thistle', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Daisy Ditsy Toss Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Diamond Cherries Cherry Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Dusty Blue Gemstone Mosaic Scarf', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'English Daisy', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Flower Pots', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Green Jacquard Stripe', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Jacobean Sprig', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Lagoon Gingham', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Light Blue Jungle Floral', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Light Pink Trellis', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Lime Gingham', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Nantucket Seas', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Navy Gingham', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Navy Stripe', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Pastel Trellis', ARRAY[]::text[], NULL, NULL, null, 'Light', 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Peony Chintz', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Pink Broderie Voile', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Pink Doily Heart', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Pink Floral Dot Stripe', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Pink Monkey Block Stripe', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Pink Palm Ikat', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Pink Pond Floral', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Pink Scallop Bow Chintz', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Pink Variegated Stripe', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Poppy Damask Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Poppy Half Drop Rose', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Red Ticking Stripe', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Sea Scroll', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Sunset Gingham', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'Thornfield Tapestry', ARRAY[]::text[], NULL, NULL, null, null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'White Broderie Voile', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'White Lace', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'White Poppy Half Drop', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'White Rainbow Fish', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('hillhouse', 'White/Green Arcadia Border', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://hillhousehome.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Bitter Chocolate', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Butter', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Chocolate', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Daisy Meadow', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Eira Butter', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Eira Midnight', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Espresso Stripe', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Fiorello Rosso', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Geo Scape', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Grey Marle', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Ivory', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Liora Charcoal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Mocha', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Sommer Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Sorbet Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Vacanza Floral Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('sirthelabel', 'Washed Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.sirthelabel.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Black Lace', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Black and White Colorblock', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Cloud Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Collegiate Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Cowgirl Boots on Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Dark Heathered Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Denim Paint Splatter', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Jet Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Pink Candy Spill', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Purple Bows', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Rainbow Glitter Foil', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Rose', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Star Denim', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Starburst Tie Dye', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('terez', 'Terez Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://terez.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Army green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Beige', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Beige melange', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Blue background', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Blue herringbone tweed', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Bordeaux background', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Brick red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Brown Prince of Wales pattern', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Burgundy brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Cognac', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Dark blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Dark brown', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Dark gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Dark gray melange', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Dark green', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Dark wash blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Desert brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Dove gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Ecru', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Green Prince of Wales pattern', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Green background', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Hazelnut', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Icy gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Inky blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Light blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Light gray melange', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Light wash blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Medium wash blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Medium', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Neutral', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Olive green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Pale blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Sky blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'Tobacco brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'White and blue stripes', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'White and bordeaux stripes', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('velasca', 'White and sky blue stripes', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.velasca.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black Heather/Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black/Ghost Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black/Gold', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black/Jungle Camo', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black/Royal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black/Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black/Silver Reflective', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Black/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Charcoal/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Charcoal/Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Dark Charcoal/White', ARRAY[]::text[], NULL, NULL, 'White', 'Dark', 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Evergreen/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Ghost Grey/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Heather Gray/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Heather Grey/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Kombu Green/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Madder Brown/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Maroon/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Navy/Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Provincial Blue/Delicate Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Smoke/Smoke', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'Vetiver/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('virusintl', 'White/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.virusintl.com/products.json', 0.75, false, 'migration:00752'),
  ('wolaco', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://wolaco.com/products.json', 0.75, false, 'migration:00752'),
  ('wolaco', 'Black + Black + Black + Black + Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://wolaco.com/products.json', 0.75, false, 'migration:00752'),
  ('wolaco', 'Black w/ Chrome', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://wolaco.com/products.json', 0.75, false, 'migration:00752'),
  ('wolaco', 'Hudson Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://wolaco.com/products.json', 0.75, false, 'migration:00752'),
  ('wolaco', 'Lava', ARRAY[]::text[], NULL, NULL, null, null, 'https://wolaco.com/products.json', 0.75, false, 'migration:00752'),
  ('wolaco', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://wolaco.com/products.json', 0.75, false, 'migration:00752'),
  ('wolaco', 'Steel Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://wolaco.com/products.json', 0.75, false, 'migration:00752'),
  ('wolaco', 'Steel Green w/ Chrome', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://wolaco.com/products.json', 0.75, false, 'migration:00752'),
  ('wolaco', 'Stone Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://wolaco.com/products.json', 0.75, false, 'migration:00752')
on conflict do nothing;

-- US-1108 self-record footer.
insert into public.applied_migrations (version) values ('00752') on conflict do nothing;
