-- US-3125: eighteen running, intimates, bag and workwear-boot brands.
--
-- Catalogues read 2026-09-07 with scripts/ops/shopify-brand-harvest.mjs. Same
-- rules as 00734 and 00739: a colour on five or more products, a brand with at
-- least eight such colours and no more than 35% plain colour words, base_color
-- and shade from the brand's own facet where it publishes one and
-- aspect-normalize's family table otherwise.
--
-- Oiselle also returned a feed and is NOT here -- the KB has had it since 00472.
--
-- -- REGISTERED NUMBERS: EIGHT OF EIGHTEEN -----------------------------------
--
--     2XU                 RN 166581   2XU NORTH AMERICA LLC     [Men's Women's Children's apparel]
--     Big Bud Press       RN 159968   Big Bud Press             [Men's and Women's apparel]
--     Boden               RN 118027   JP BODEN USA LLC          [WEARING APPAREL]
--     Chrome Industries   RN 149758   CHROME INDUSTRIES, INC.   [SWEATSHIRTS SHIRTS JACKETS PANTS]
--     Harper Wilde        RN 160425   Harper Wilde, Inc.        [Women's apparel]
--     Knix                RN 169940   Knix Wear Inc.            [Children's and Women's apparel]
--     Mission Workshop    RN 153948   MISSION WORKSHOP, LLC     [Men's apparel]
--     Wildfang            RN 155218   Wildfang Co               [Women's apparel]
--
-- Boden is the founder-initials case: JP BODEN USA LLC keeps the label and adds
-- Johnnie Boden's initials, which is an addition rather than the replacement of
-- a distinctive token.
--
-- -- THE VINTAGE RULE FROM 00750 PAYS FOR ITSELF IMMEDIATELY -----------------
--
-- Altra returns RN 73198 ALTRA CORP., INC. -- an exact name plus a generic
-- word, which is normally an acceptance. It is refused on the NUMBER. 73198
-- sits below Stussy's 94974 and Brooks Brothers' 99458, so it was issued long
-- before Altra Running existed in 2009. One run after the rule was written down
-- it caught a hit that every other test on this list would have passed.
--
-- -- NINE OTHERS REFUSED -----------------------------------------------------
--
-- Farm Rio, Georgia Boot, Lisa Says Gah, Muck Boot, Negative Underwear, TomboyX
-- and Woxer return NOTHING. A legitimate absence.
--
-- Craft Sportswear and Nathan Sports are the substring trap, thirteen and
-- fourteen. "Craft Sportswear" pulls PEN-CRAFT, MODEL-CRAFT, STYLE-CRAFT and
-- MASTER-CRAFT SPORTSWEAR; "Nathan Sports" pulls JO-NATHAN SPORTSWEAR LTD. The
-- register matches on substring and neither brand has a registration at all.
--
-- -- COLOURS ----------------------------------------------------------------
--
-- Seeded: altra (86), bigbudpress (28), chromeindustries (15), farmrio (44), knix (95), missionworkshop (24), muckboot (86), nathansports (11), negativeunderwear (35), tomboyx (49), woxer (86).
-- Palette refused, too few or too plain: georgiaboot (6), harperwilde (19, 37% plain), lisasaysgah (6).
-- No colour survives the filter: 2xu (0 raw), boden (0 raw), craftsports (3 raw), wildfang (0 raw).
--
insert into public.brand_knowledge
  (brand_key, canonical_brand, aliases, category_focus, registered_numbers,
   notes, source_url, confidence, verified, updated_by)
values

  ('2xu', '2XU', ARRAY['2xu','two times you']::text[], ARRAY['compression','triathlon','activewear','australian']::text[], ARRAY['RN 166581']::text[],
   'RN 166581 is FTC-record sourced -- registrant "2XU NORTH AMERICA LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.2xu.com/', 0.60, false, 'migration:00751'),
  ('altra', 'Altra', ARRAY['altra','altra running','altra footwear']::text[], ARRAY['running','footwear','zero drop','outdoor']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.altrarunning.com/', 0.60, false, 'migration:00751'),
  ('bigbudpress', 'Big Bud Press', ARRAY['big bud press','bigbudpress']::text[], ARRAY['jumpsuits','unisex','made in la','colourful']::text[], ARRAY['RN 159968']::text[],
   'RN 159968 is FTC-record sourced -- registrant "Big Bud Press". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.bigbudpress.com/', 0.60, false, 'migration:00751'),
  ('boden', 'Boden', ARRAY['boden','jp boden','johnnie boden']::text[], ARRAY['womenswear','kids','british','prints']::text[], ARRAY['RN 118027']::text[],
   'RN 118027 is FTC-record sourced -- registrant "JP BODEN USA LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.boden.com/', 0.60, false, 'migration:00751'),
  ('chromeindustries', 'Chrome Industries', ARRAY['chrome','chrome industries']::text[], ARRAY['bags','cycling','messenger','footwear']::text[], ARRAY['RN 149758']::text[],
   'RN 149758 is FTC-record sourced -- registrant "CHROME INDUSTRIES, INC.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.chromeindustries.com/', 0.60, false, 'migration:00751'),
  ('craftsports', 'Craft Sportswear', ARRAY['craft','craft sportswear','craft sports']::text[], ARRAY['cycling','running','baselayer','swedish']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.craftsports.us/', 0.60, false, 'migration:00751'),
  ('farmrio', 'Farm Rio', ARRAY['farm rio','farmrio','farm']::text[], ARRAY['womenswear','prints','brazilian','dresses']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.farmrio.com/', 0.60, false, 'migration:00751'),
  ('georgiaboot', 'Georgia Boot', ARRAY['georgia boot','georgiaboot']::text[], ARRAY['boots','workwear','footwear','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.georgiaboot.com/', 0.60, false, 'migration:00751'),
  ('harperwilde', 'Harper Wilde', ARRAY['harper wilde','harperwilde']::text[], ARRAY['bras','intimates','womenswear']::text[], ARRAY['RN 160425']::text[],
   'RN 160425 is FTC-record sourced -- registrant "Harper Wilde, Inc.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://harperwilde.com/', 0.60, false, 'migration:00751'),
  ('knix', 'Knix', ARRAY['knix','knix wear','knixwear']::text[], ARRAY['intimates','leakproof','womenswear','bras']::text[], ARRAY['RN 169940']::text[],
   'RN 169940 is FTC-record sourced -- registrant "Knix Wear Inc.". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://knix.com/', 0.60, false, 'migration:00751'),
  ('lisasaysgah', 'Lisa Says Gah', ARRAY['lisa says gah','lisasaysgah','lsg']::text[], ARRAY['womenswear','prints','independent','contemporary']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://lisasaysgah.com/', 0.60, false, 'migration:00751'),
  ('missionworkshop', 'Mission Workshop', ARRAY['mission workshop','missionworkshop']::text[], ARRAY['bags','cycling','technical apparel','san francisco']::text[], ARRAY['RN 153948']::text[],
   'RN 153948 is FTC-record sourced -- registrant "MISSION WORKSHOP, LLC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://missionworkshop.com/', 0.60, false, 'migration:00751'),
  ('muckboot', 'Muck Boot', ARRAY['muck boot','muckboot','the original muck boot company']::text[], ARRAY['boots','rubber','farm','outdoor']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.muckbootcompany.com/', 0.60, false, 'migration:00751'),
  ('nathansports', 'Nathan Sports', ARRAY['nathan','nathan sports','nathansports']::text[], ARRAY['running','hydration','reflective','accessories']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.nathansports.com/', 0.60, false, 'migration:00751'),
  ('negativeunderwear', 'Negative Underwear', ARRAY['negative','negative underwear']::text[], ARRAY['intimates','bras','womenswear','minimal']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.negativeunderwear.com/', 0.60, false, 'migration:00751'),
  ('tomboyx', 'TomboyX', ARRAY['tomboyx','tomboy x']::text[], ARRAY['underwear','unisex','inclusive sizing','basics']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://tomboyx.com/', 0.60, false, 'migration:00751'),
  ('wildfang', 'Wildfang', ARRAY['wildfang','wild fang']::text[], ARRAY['womenswear','suiting','tomboy','portland']::text[], ARRAY['RN 155218']::text[],
   'RN 155218 is FTC-record sourced -- registrant "Wildfang Co". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.wildfang.com/', 0.60, false, 'migration:00751'),
  ('woxer', 'Woxer', ARRAY['woxer']::text[], ARRAY['underwear','boxers','womenswear','basics']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://woxer.com/', 0.60, false, 'migration:00751')
on conflict (brand_key) do nothing;

insert into public.brand_colorways
  (brand_key, color_name, aliases, hex, years, base_color, shade,
   source_url, confidence, verified, updated_by)
values

  ('altra', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black / Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black-Light Gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Black/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Lime', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/White/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Black/Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Blue/Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Blue/Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Blue/Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Blue/Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Boston', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Brown/Taupe', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Coral', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Coral/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Dark Blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Dark Gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Dark Purple', ARRAY[]::text[], NULL, NULL, 'Purple', 'Dark', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Dark Shadow', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Dark Slate', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Deep Navy-Medium Gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Deep Teal', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Dusty Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Dusty Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Dusty Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Gray/Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Gray/Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Gray/Lime', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Gray/Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Gray/Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Gray/Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Gray/Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Gray/Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Ice Flow Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Light Blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Light Gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Light Gray/Red', ARRAY[]::text[], NULL, NULL, 'Red', 'Light', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Light Green', ARRAY[]::text[], NULL, NULL, 'Green', 'Light', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Lime', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Lime/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Majolica Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Maroon', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Mineral Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Mint', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Navy/Coral', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Navy/Light blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Orange/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Orchid', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Purple/Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Raspberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Red/Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'SOAR', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Tan', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Taupe', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White/Black/Fiery Coral', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White/Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White/Coral', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White/Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White/Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White/Lime', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White/Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White/Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'White/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('altra', 'Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.altrarunning.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Baby Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Basic Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Bubblegum Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Burnt Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Burnt Terracotta', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Butter Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Dark Wash', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Espresso Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Evergreen', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Faded Grape', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Fudgesicle Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Golden Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Gross Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Hot Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Hunter Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Lagoon', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Light Wash', ARRAY[]::text[], NULL, NULL, null, 'Light', 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Marine Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Mustang Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Mustard Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Olive Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Paprika', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Red Wine', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Royal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Sage Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Sunshine Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Swamp Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('bigbudpress', 'Vintage Tee Off-White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.bigbudpress.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Black Canvas Leather', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Black X', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Black XRF', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Chrome', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Coyote', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Coyote X', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Future White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'J Prince', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Mauve X', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Red X', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Royale', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Sage', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('chromeindustries', 'Steel Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.chromeindustries.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'AMMONITE MULTICOLOR', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'ANIMAL', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'BANANA QUEEN', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'BEIGE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'BROWN', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'CARAMEL', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'COUNTRYSIDE LANDSCAPE MULTICOLOR', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'CUOIO', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'DENIM', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'EDENS BLOOM LIGHT PINK', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'EMILY FLORAL TAPESTRY OFF-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'FLORA TILE OFF-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'FRUIT GARDEN', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'HILO STRIPES LIGHT BLUSH', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'IVORY', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'LIGHT PINK', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'LIGIA FLORAL LIGHT PINK', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'MAIRA FLORAL DARK BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'MARINE SHELLS SAND', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'MARTINA TAPESTRY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'MOSAIC RIO', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'NATURE SAND', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'NINA OFF-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'OFF-WHITE', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'ORANGE', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'PARROTS FOREST GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'PEIXE COPA', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'PINK', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'RED', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'RIO SOUVENIR MIXED SCARF MULTICOLOR', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'ROYAL PINEAPLE GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'ROYAL SEA MULTICOLOR', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'SAND', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'STAINED GLASS BEAUTY SOFT BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'STITCHED GARDEN OFF-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'TOILE DE RIO OFF-WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'TROPICAL GROOVE BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'TROPICAL SCARF SAND', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'WALNUT', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'WINTER FLORAL CREAM', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('farmrio', 'YELLOW', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.farmrio.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Beach Fossil', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Berry Blossom/Polka Dot Patch/Strawberry Petal', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Berry Blue/Berry Bliss/Blueberry Bloom', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Black with White Polka Dot', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Black/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Blackberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Blue Coast', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Blue Light', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Blue Serpent', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Bluebell', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Blush', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Blush Berry', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Buttercup', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Candy Heart', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Candy Heart/Pink Bows/Deep Blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Cavassa', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Chartreuse', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Cheetah Print', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Cherry', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Cosmo', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Cypress', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Dahlia', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Dark Cherry', ARRAY[]::text[], NULL, NULL, 'Red', 'Dark', 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Deep Orchid', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Ditsy Blossom', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Ditsy Blossom/Bluebell/Cosmo', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Dove Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Dune', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Dusty Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Electric Orchid', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Electric Orchid/Teal Appeal/Lagoon', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Energize/Marina/Highlight', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Espresso', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Eucalyptus', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Fresh Fruit', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Heathered Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Horizon', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Hush', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Ice', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Ivory', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Ivy Bloom', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Jasmine Dusk', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Lavender', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Lotus', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Lucky', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Marina', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Meadows', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Midnight', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Mulberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Nautical Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Navy Seersucker', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Night Blossom/Velvet/Sweet Cherry', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Night Sky', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Night Sky/Beige/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'No. 5 Soft Tan', ARRAY[]::text[], NULL, NULL, 'Tan', 'Light', 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Orchid Ombre', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Oyster', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Pastel Wings/Pink Orchid/Blush', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Pepper', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Periwinkle', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Pewter', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Picnic Plaid/Cosmo/Ultra Violet', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Pink Hibiscus', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Pink Party', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Pink Pop', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Pink Red Plaid', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Poppy Petal', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Purple Heather', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Red Tulip', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Red Tulip/Scarlet/Super Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Rose Water', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Royal Reverie', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Sailor', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Scarlet', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Seabreeze', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Seaside Plaid', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Set Sail', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Shady Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Sola', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Sphere', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Strawberry Field/Sweet Tea/Baby Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Strawberry Picnic', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Thistle', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Tropical Punch', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Twilight Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Twilight Navy/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Warm Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Wave Pool', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'White with Black Polka Dot', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('knix', 'Wild Cat', ARRAY[]::text[], NULL, NULL, null, null, 'https://knix.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Black Camo', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Black EPX 200', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Black HT500', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Black Ultra', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Black Ultra [PREORDER]', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Black VX', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Black Waxed Canvas', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Brown Waxed Canvas', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Coyote VX', ARRAY[]::text[], NULL, NULL, null, null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Gray EPX 200', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Gray HT500', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Gray VX', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Olive EPX 200', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Olive VX', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Olive Waxed Canvas', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Orange VX', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Purple VX', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'White Ultra', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'White VX', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('missionworkshop', 'Yellow VX', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://missionworkshop.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'AMERICAN SWIRL', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK COFFEE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/BLUE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/BUFFALO PLAID', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/FUZZY HERRINGBONE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/GRAY GEO', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/GRAY PLAID FAUX FUR', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/GREY PLAID', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/GREY WAVE', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/HEATHER JERSEY', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/MAGENTA DIGI', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/MOUNTAIN TERRAIN', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/PINK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/PLAID', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/PURPLE ACAI', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/ROSE', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLACK/WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLUE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLUE QUILT FLORAL', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BLUE QUILTED FLORAL', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BROWN', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BROWN CHICKEN PRINT', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'BROWN PLAID', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'CARAMEL', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'CROCKERY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'DARK GREY', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'DESERT SAGE', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'DUCK CAMO', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'FOREST', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'GRAVEL GRAY/FLORAL', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'GRAY/PRINT', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'GREEN FLORAL', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'GREEN VEGGIE PRINT', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'GREY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'GREY HERRINGBONE', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'GREY WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'INDIA INK', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'INDIA INK/FLORAL', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'LIBERTY BLUE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'LIBERTY RED', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'LIBERTY WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'LIGHT GRAY/FLORAL', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MAROON/PINK FADE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MINIMAL GRAY/FLORAL', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MONUMENT', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSS', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSS HOUNDSTOOTH', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK BOTTOMLAND', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK BREAK UP', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK BREAK UP COUNTRY', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK COUNTRY DNA', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK COUNTRY ROOTS', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK FULL FOLIAGE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK GREENLEAF', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK ORIGINAL BOTTOMLAND', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK ORIGINAL TREESTAND', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MOSSY OAK SHADOW GRASS HABITAT', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MUDDY GIRL CAMO', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'MULTI SWIRL', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'NAVY', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'NAVY FLORAL', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'OATMEAL', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'OLIVE', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'OLIVE GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'OLIVE NIGHT', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'PERIWINKLE', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'PINK A BOO', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'RAISIN HERRINGBONE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'REALTREE EDGE', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'REALTREE ORIGINAL', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'RED BLACK CHECKERS', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'RESIDA GREEN', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'RESIDA GREEN SUNFLOWER', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'SAND', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'TAN QUILTED STRIPE', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'TAN/DARK BROWN', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'TAUPE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'TURKISH COFFEE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'WALNUT', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'WALNUT/BROWN', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'WALNUT/CHOCOLATE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'WINE/HERRINGBONE', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('muckboot', 'WOODROSE', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.muckbootcompany.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Black/Hex Print', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Black/High Vis Yellow', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Black/Reflective Silver', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Clear', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Deep Teal/Reflective Silver', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Electric Blue/Reflective Silver', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Hi Vis Yellow/Hex Print', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Safety Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Sailor Blue/Reflective Silver', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('nathansports', 'Vapor Grey/Sailor Blue', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.nathansports.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Babe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Black + White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Buff', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Buff + Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Buff + White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Cassis', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Cerise', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Cherry', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Cloud', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Cobalt', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Coral', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Deep', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Espresso', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Espresso Dot', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Garnet', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Glacier', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Honey', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Lilac', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Maritime', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Mink', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Mist', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Muse', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Peach', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Satellite', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Shell', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Shell Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Slate', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Sorbet', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('negativeunderwear', 'Zebra', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.negativeunderwear.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Batwing Brocade Chai', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Batwing Brocade MP', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Batwing Brocade Mauve', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Black Imperfects', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Black Rainbow Logo', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Black X=', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Black X= Rainbow', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Bluestone', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Bone And Vine MP', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Bone and Vine', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Bug Out', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Chai', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Chai Imperfects', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Cottage Witch', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Evergreen', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Forest Heather', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Future Dusk', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Jelly Magic', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Kraken', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Making Waves', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Melting Rainbow', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Modal Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Modal The Blues MP', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Moonlit Mushrooms', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Nightfall Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Off-Roadies', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Palm Dreams', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Plum', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Pumpkin Spice', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Rainbow Logo Imperfects', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Rainbow Wave', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Rainbow X=', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Red Edge', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Retro Charcoal Logo V2', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Road Trip', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Stripe Unbound', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Stripe Up MP', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'TENCEL Modal Animal Constellation', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'TENCEL Modal Garden Gazing', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'TENCEL Modal Ink Blue Edge', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'TENCEL Modal Purple Storm', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'TENCEL Modal Rainbow X=', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'TENCEL Modal Too Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Teal Time', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'Ultimate Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'X= Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('tomboyx', 'X= Chai', ARRAY[]::text[], NULL, NULL, null, null, 'https://tomboyx.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Action', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Aqua Amp', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Arctic', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Bare', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Black 2.0', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Brush of Us', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Chai', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Charcoal Heather 2.0', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Cherry', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Composition', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Coral Pride', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Crimson Canvas', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Desert Salt', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Dot Collective', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Douglas Fir', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Dusk Deluxe', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Espresso', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Flare', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Force Flux', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Graffiti', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Graffiti Art', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Ignite', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Inviting', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Jade', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Jet Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Latte 3.0', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Lilacline', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Marina', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Mazarine Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Mocha', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Muralist', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Mystery', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Navy 2.0', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Neutrals', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Orchid', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Our Mark', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Painted Paths', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Palm Set', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Peach', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Perishade', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Plum Tide', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Plush', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pop', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pride Align', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pride Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pride Black 3.0', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pride Blaze', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pride Ignite', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pride Spark', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pride Tide', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pride Wave', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Pulse', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Rhubarb', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Rhythm', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Rose Drift', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Royal Pride', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Sandstone', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Signal', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Skyline', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Soft Bloom', ARRAY[]::text[], NULL, NULL, null, 'Light', 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Solar Crush', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Sorbet', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Space Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Splash', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Steel Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Submerge', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Sunburst Sorbet', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Surf Pop', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Teal Your Story', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Tealcore', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Tectonic', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Tectonic Wave', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Tempo', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Tidal Bloom', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Tones', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Ultramarine', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Velvet', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Vivid', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Wild Sage', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751'),
  ('woxer', 'Wineberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://woxer.com/products.json', 0.75, false, 'migration:00751')
on conflict do nothing;

-- US-1108 self-record footer.
insert into public.applied_migrations (version) values ('00751') on conflict do nothing;
