-- US-3125: nineteen merino, cashmere, hemp and slow-fashion brands.
--
-- Catalogues read 2026-09-07 with scripts/ops/shopify-brand-harvest.mjs. Same
-- rules as 00734 and 00739: a colour on five or more products, a brand with at
-- least eight such colours and no more than 35% plain colour words, base_color
-- and shade from the brand's own facet where it publishes one and
-- aspect-normalize's family table otherwise.
--
-- This run took TWO probe batches to reach nineteen brands, and the reason is
-- worth recording. The first list was European technical outdoor labels -- 40
-- domains returned 9 feeds, three of which the KB already held. Those brands
-- run bespoke platforms rather than Shopify. The second list, US small-batch and
-- slow-fashion, returned 13 from 40. The open-feed method is not exhausted; it
-- is specific to who builds on Shopify.
--
-- The refusal rate is climbing all the same: 18 of the second batch's 40 had a
-- catalogue and declined us, against 1 in 40 last run.
--
-- -- REGISTERED NUMBERS: THREE BRANDS, FOUR NUMBERS --------------------------
--
--     Autumn Cashmere   RN 140782   AUTUMN CASHMERE INC       [CASHMERE AND COTTON APPARREL]
--     Icebreaker        RN 152785   ICEBREAKER NATURE CLOTHING INC
--     Icebreaker        RN 159200   Icebreaker, A Division of VF Outdoor LLC
--     Jungmaven         RN 150988   JUNGMAVEN                 [HEMP TSHIRTS]
--
-- -- ICEBREAKER SETTLES A QUESTION SMARTWOOL LEFT OPEN ------------------------
--
-- 00748 REFUSED Smartwool because its only hit was "VF OUTDOOR, LLC" -- a
-- registrant sharing no token with the label, even though VF really does own
-- Smartwool. That refusal looked over-strict at the time.
--
-- Icebreaker is also VF-owned, and VF registered it as "Icebreaker, A Division
-- of VF Outdoor LLC". The label is right there in the registrant name. So the
-- same parent company produces a usable registration for one brand and an
-- unusable one for the other, and the rule reads both correctly without
-- knowing anything about VF: keep the ones that name the label, refuse the ones
-- that do not. A parent's identity is not evidence about a subsidiary; the
-- REGISTRANT STRING is.
--
-- Icebreaker's second number, 152785 ICEBREAKER NATURE CLOTHING INC, is the
-- pre-acquisition entity. Both are kept for the same reason as Dakine and Jetty
-- in 00753 -- a garment can carry either.
--
-- -- SIXTEEN REFUSED ---------------------------------------------------------
--
-- Fourteen return NOTHING: Baleaf, Jack Wolfskin, SOAR, American Hat Makers,
-- Blundstone, Christy Dawn, Collina Strada, Elizabeth Suzann, Harvest & Mill,
-- Kancan, Lems, Minnie Rose, Nooworks and Vervet.
--
-- SCARPA returns SCARPA TENNIS TAPES INC and LA SCARPA FASHIONS LTD -- the
-- substring trap, and both numbers (55025, 76643) are far too early for these to
-- be an Italian climbing-shoe maker's US registration anyway. WoolX returns
-- Hank's Clothing For Men And Women Inc., which shares no token with the label.
--
-- -- COLOURS ----------------------------------------------------------------
--
-- Seeded: baleaf (55), christydawn (19), elizabethsuzann (17), icebreaker (30), jungmaven (43), minnierose (17), woolx (108).
-- Palette refused, too few or too plain: americanhatmakers (6), kancan (33, 52% plain), lems (2), vervet (8, 50% plain).
-- No colour survives the filter: autumncashmere (9 raw), blundstone (0 raw), collinastrada (0 raw), harvestandmill (2 raw), jackwolfskin (0 raw), nooworks (8 raw), scarpa (0 raw).
--
insert into public.brand_knowledge
  (brand_key, canonical_brand, aliases, category_focus, registered_numbers,
   notes, source_url, confidence, verified, updated_by)
values

  ('americanhatmakers', 'American Hat Makers', ARRAY['american hat makers','americanhatmakers','ahm']::text[], ARRAY['hats','leather','handmade','accessories']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.americanhatmakers.com/', 0.60, false, 'migration:00755'),
  ('autumncashmere', 'Autumn Cashmere', ARRAY['autumn cashmere','autumncashmere']::text[], ARRAY['cashmere','knitwear','womenswear','sweaters']::text[], ARRAY['RN 140782']::text[],
   'RN 140782 is FTC-record sourced -- registrant "AUTUMN CASHMERE INC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.autumncashmere.com/', 0.60, false, 'migration:00755'),
  ('baleaf', 'Baleaf', ARRAY['baleaf','baleaf sports']::text[], ARRAY['activewear','cycling','running','value']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.baleaf.com/', 0.60, false, 'migration:00755'),
  ('blundstone', 'Blundstone', ARRAY['blundstone','blundstones','blunnies']::text[], ARRAY['boots','chelsea boots','australian','footwear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.blundstone.com/', 0.60, false, 'migration:00755'),
  ('christydawn', 'Christy Dawn', ARRAY['christy dawn','christydawn']::text[], ARRAY['womenswear','deadstock','dresses','regenerative']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://christydawn.com/', 0.60, false, 'migration:00755'),
  ('collinastrada', 'Collina Strada', ARRAY['collina strada','collinastrada']::text[], ARRAY['womenswear','avant garde','sustainable','new york']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://collinastrada.com/', 0.60, false, 'migration:00755'),
  ('elizabethsuzann', 'Elizabeth Suzann', ARRAY['elizabeth suzann','elizabethsuzann']::text[], ARRAY['womenswear','slow fashion','linen','made to order']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://elizabethsuzann.com/', 0.60, false, 'migration:00755'),
  ('harvestandmill', 'Harvest & Mill', ARRAY['harvest & mill','harvest and mill','harvestandmill']::text[], ARRAY['basics','organic cotton','made in usa','tees']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.harvestandmill.com/', 0.60, false, 'migration:00755'),
  ('icebreaker', 'Icebreaker', ARRAY['icebreaker','icebreaker merino']::text[], ARRAY['merino','baselayer','outdoor','new zealand']::text[], ARRAY['RN 152785','RN 159200']::text[],
   'RN 152785 is FTC-record sourced -- registrant "ICEBREAKER NATURE CLOTHING INC". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.icebreaker.com/', 0.60, false, 'migration:00755'),
  ('jackwolfskin', 'Jack Wolfskin', ARRAY['jack wolfskin','jackwolfskin']::text[], ARRAY['outdoor','hiking','german','outerwear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.jack-wolfskin.com/', 0.60, false, 'migration:00755'),
  ('jungmaven', 'Jungmaven', ARRAY['jungmaven','jung maven']::text[], ARRAY['hemp','tees','basics','sustainable']::text[], ARRAY['RN 150988']::text[],
   'RN 150988 is FTC-record sourced -- registrant "JUNGMAVEN". ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.jungmaven.com/', 0.60, false, 'migration:00755'),
  ('kancan', 'Kancan', ARRAY['kancan','kancan usa','kancan jeans']::text[], ARRAY['denim','womenswear','wholesale','jeans']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.kancanusa.com/', 0.60, false, 'migration:00755'),
  ('lems', 'Lems Shoes', ARRAY['lems','lems shoes','lemsshoes']::text[], ARRAY['footwear','barefoot','zero drop','outdoor']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.lemsshoes.com/', 0.60, false, 'migration:00755'),
  ('minnierose', 'Minnie Rose', ARRAY['minnie rose','minnierose']::text[], ARRAY['cashmere','knitwear','womenswear','resort']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.minnierose.com/', 0.60, false, 'migration:00755'),
  ('nooworks', 'Nooworks', ARRAY['nooworks','noo works']::text[], ARRAY['womenswear','prints','san francisco','independent']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://nooworks.com/', 0.60, false, 'migration:00755'),
  ('scarpa', 'SCARPA', ARRAY['scarpa']::text[], ARRAY['footwear','climbing','mountaineering','italian']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.scarpa.com/', 0.60, false, 'migration:00755'),
  ('soarrunning', 'SOAR Running', ARRAY['soar','soar running','soarrunning']::text[], ARRAY['running','technical apparel','british','performance']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.soarrunning.com/', 0.60, false, 'migration:00755'),
  ('vervet', 'Vervet', ARRAY['vervet','vervet denim','vervet by flying monkey']::text[], ARRAY['denim','womenswear','jeans','wholesale']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.vervetdenim.com/', 0.60, false, 'migration:00755'),
  ('woolx', 'WoolX', ARRAY['woolx','wool x']::text[], ARRAY['merino','baselayer','outdoor','socks']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER SEEDED: the FTC register either returns nothing for this brand (a legitimate absence, not a failed lookup) or returns a registrant whose name is not the label, which is refused rather than guessed. ⚠ NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find.',
   'https://www.woolx.com/', 0.60, false, 'migration:00755')
on conflict (brand_key) do nothing;

insert into public.brand_colorways
  (brand_key, color_name, aliases, hex, years, base_color, shade,
   source_url, confidence, verified, updated_by)
values

  ('baleaf', 'Anthracite', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Aqua Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Army Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Black/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Caramel Cafe', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Charcoal Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Cocoa Crème', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Dark Brown', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Dark Gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Dark Purple', ARRAY[]::text[], NULL, NULL, 'Purple', 'Dark', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Dark Sapphire', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Deep Blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Doeskin', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Ebony', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Estate Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Fluorescent Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Heather Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Heather Light Gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Hot Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Kentucky Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Lavender Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Light Blue', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Light Gray', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Light Green', ARRAY[]::text[], NULL, NULL, 'Green', 'Light', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Light Pink', ARRAY[]::text[], NULL, NULL, 'Pink', 'Light', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Light Purple', ARRAY[]::text[], NULL, NULL, 'Purple', 'Light', 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Lucent White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Navy Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Niagara', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Oatmeal', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Olive Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Peacoat', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Pink Dogwood', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Rifle Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Rose Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Royal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Smoked Pearl', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Star White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Teak Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Teal Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Weathered Teak', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Wine Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('baleaf', 'Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.baleaf.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Alabaster', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Chamomile Rose Cluster', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Dotted Plaid', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Ivory', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Night', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Noir Daisy', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Oak Leaf', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Pearl', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Rose Garden', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Rose Trellis', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Slate', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Spring Mushroom Medley', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Summer Bounty', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Summer Orchard', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Vintage Bloom', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Wild Berries', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('christydawn', 'Wild Bloom', ARRAY[]::text[], NULL, NULL, null, null, 'https://christydawn.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Cacao', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Canyon', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Cedar', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Flax', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Lichen', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Moss', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Olivine', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Overcast', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Pear', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Salt', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Umber', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Verte', ARRAY[]::text[], NULL, NULL, null, null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('elizabethsuzann', 'Washed Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://elizabethsuzann.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Abyss', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Agate', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Bittersweet', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Black/Dawn', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Black/Ether', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Black/Graphite', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Black/Obsidian', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Black/Snow', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Blizzard Hthr/Alloy', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Cumin', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Dark Berry', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Dark Loden', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Dawn', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Grey Plum', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Gritstone Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Jet Heather', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Jet Heather/Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Lazurite', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Lichen', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Metro Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Midnight Navy', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Obsidian', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Obsidian/black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Pink quartz', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Port', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Praline', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Proto Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Undyed', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('icebreaker', 'Zinc Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.icebreaker.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Agave Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Athletic Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Black Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Blue Heaven', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Burnt Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Coastal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Coffee Bean', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Coyote', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Dark', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Deep Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Deep Teal', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Desert Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Diesel Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Electric Fuchsia', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Hunter Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Lapis Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Light', ARRAY[]::text[], NULL, NULL, null, 'Light', 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Lt. Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Medium', ARRAY[]::text[], NULL, NULL, null, 'Medium', 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Oasis Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Oat Milk', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Olive Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Pistachio', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Poppy Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Powder Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Pumpkin Spice', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Rain Washed', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Rainbow', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Red/White/Blue Stripe', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Rose Water', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Shortbread', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Stormy Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Stucco Beige', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Sunbleached Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Sunset Coral', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Washed White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Whispering Peach', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Wisteria', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('jungmaven', 'Yucca', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.jungmaven.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Blueberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Bordeaux', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Brown Sugar', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Camel', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Cameo Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Dark Cherry', ARRAY[]::text[], NULL, NULL, 'Red', 'Dark', 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Foxy Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Fresco Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Golden Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Grey Shadow', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Lotus', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Rose Petal', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Sky Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'Starch', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('minnierose', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.minnierose.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Beet Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Berry Ice Pop', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Berry Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Black Pepper', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Black Stripe', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Blue Horizon', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Blue Pine', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Blue Razz', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Blue Sand Stripe', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Bluebell', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Bracken', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Brick Dust', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Buttercream', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Buttercream Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Butterscotch', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Cabana Crush', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Carbon Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Charcoal Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Cinder Melange', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Cinnamon Spice', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Cloudy Bay', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Coastal Mini Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Coastal Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Cool Jade', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Cream Heather', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Dark Espresso', ARRAY[]::text[], NULL, NULL, 'Brown', 'Dark', 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Dark Forest Marled', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Dark Grey Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', 'Dark', 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Dark Navy Marled', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Deep Navy', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Deep Pine', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Deep Timber', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Dewdrop Pearl', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Dolphin', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Duffel Bag', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Ecru', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Evening Tide', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Everleaf', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Forest Friends', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'French Oak', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Frog Hop', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Grape Harvest', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Graphite Heather', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Hibiscus', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Hopscotch Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Icicle', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Jungle', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Light Ash', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Light Grey Stripe', ARRAY[]::text[], NULL, NULL, 'Gray', 'Light', 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Little Ballerina', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Majolica Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Majolica Blue Stripe', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Maraschino Cherry', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Morning Fog', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Moroccan Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Navy Carbon', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Nutmeg', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Ocean Cavern', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Olive Leaf', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Pebble', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Peppercorn', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Pinky Promise', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Pinot Noir', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Polar White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Poppy Spark', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Purple Iris', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Purple Wine', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Raspberry Fizz', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Rhubarb', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Rhubarb Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Riverbank Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Rosewater', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Rosie Posie', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Sable Heather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Sage Olive', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Sailor Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Sand Dollar', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Sienna Kiss', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Simply Taupe', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Skyline', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Steel Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Stone Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Summer Sorbet', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Surfside', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Sweet Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Taffy Twist', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Toasted Almond', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Toasted Garnet', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Turtle Shell', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Vanilla', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Vintage Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Vintage Khaki', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Vivid Rose', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Warm Violet', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Whipped Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'White Lightning', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Wild Blossom', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Wildberry Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Wildflower', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Winter Moss', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Woodland Mini Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755'),
  ('woolx', 'Woodland Stripe', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.woolx.com/products.json', 0.75, false, 'migration:00755')
on conflict do nothing;

-- US-1108 self-record footer.
insert into public.applied_migrations (version) values ('00755') on conflict do nothing;
