-- US-3125: fifteen brands whose catalogs refused us the first time.
--
-- Every brand here was probed in an earlier run and answered with a catalog it
-- would not serve -- HTTP 429, 503, or a bot challenge. They were recorded as
-- "refused, retry" rather than "no feed", and this is the retry. 15 of 30
-- answered; the other 10 still refuse and 5 now have no feed at all.
--
-- That distinction was worth keeping. A refusal is a moment in time and a
-- missing feed is a fact about the store, and collapsing them would have lost
-- fifteen brands permanently.
--
-- -- REGISTERED NUMBERS: FIVE OF FIFTEEN -------------------------------------
--
--     Branwyn          RN 159124   Branwyn                          [Women's apparel]
--     Hunter Bell      RN 143037   HUNTER BELL                      [APPARELL]
--     Mara Hoffman     RN 124749   MARA HOFFMAN, INC.               [GARMENTS/APPAREL]
--     MATE the Label   RN 157267   MATE the Label                   [Women's apparel]
--     Unbound Merino   RN 172558   Unbound Merino Properties LLC    [Unisex and Women's]
--
-- ("APPARELL" is the register's own spelling, recorded as seen.)
--
-- Ten refused. Crown Northampton, Industry of All Nations, Older Brother,
-- Pistola, Stan Ray, State Cashmere, Whimsy + Row and Xero Shoes return
-- nothing. Astral returns ASTRAL PLANE LLC and AMERICAN ASTRAL CORP, neither of
-- which is the label.
--
-- norda is refused twice over, which is worth recording because the two rules
-- agree: NORDALPES, INC. is the substring trap (NORDA-lpes), AND its RN 77647
-- sits below Stussy's 94974, so it was issued decades before norda was founded
-- in 2022. Either test alone rejects it.
--
-- -- COLORS ------------------------------------------------------------------
--
-- Same rules as 00734 and 00758. A declared Color variant option is preferred
-- and carries confidence 0.75; a color parsed from the product title is a
-- fallback at 0.55, and only when at least 15% of its values resolve to a
-- color family. Pistola publishes both and the option wins.
--
-- Seeded: astral (8, option), crownnorthampton (101, title), hunterbell (12, option), industryofallnations (28, option), matethelabel (14, option), norda (59, title), olderbrother (36, title), pistola (181, title), unbound (51, option), xeroshoes (12, title).
-- Too few colors to seed: branwyn (7), marahoffman (1), stanray (0), statecashmere (7), whimsyandrow (0).
-- No usable feed: none.

insert into public.brand_knowledge
  (brand_key, canonical_brand, aliases, category_focus, registered_numbers,
   notes, source_url, confidence, verified, updated_by)
values

  ('astral', 'Astral', ARRAY['astral','astral designs','astral footwear']::text[], ARRAY['footwear','watersports','outdoor','paddling']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://astraldesigns.com/', 0.60, false, 'migration:00761'),
  ('branwyn', 'Branwyn', ARRAY['branwyn']::text[], ARRAY['merino','intimates','womenswear','performance']::text[], ARRAY['RN 159124']::text[],
   'RN 159124 is FTC-record sourced -- registrant "Branwyn". NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://branwyn.com/', 0.60, false, 'migration:00761'),
  ('crownnorthampton', 'Crown Northampton', ARRAY['crown northampton','crownnorthampton','crown']::text[], ARRAY['footwear','sneakers','english-made','leather']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://www.crownnorthampton.com/', 0.60, false, 'migration:00761'),
  ('hunterbell', 'Hunter Bell', ARRAY['hunter bell','hunterbell','hunter bell nyc']::text[], ARRAY['womenswear','dresses','contemporary','new york']::text[], ARRAY['RN 143037']::text[],
   'RN 143037 is FTC-record sourced -- registrant "HUNTER BELL". NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://hunterbellnyc.com/', 0.60, false, 'migration:00761'),
  ('industryofallnations', 'Industry of All Nations', ARRAY['industry of all nations','ioan','industryofallnations']::text[], ARRAY['sustainable','basics','transparent supply','menswear']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://industryofallnations.com/', 0.60, false, 'migration:00761'),
  ('marahoffman', 'Mara Hoffman', ARRAY['mara hoffman','marahoffman']::text[], ARRAY['womenswear','swim','sustainable','prints']::text[], ARRAY['RN 124749']::text[],
   'RN 124749 is FTC-record sourced -- registrant "MARA HOFFMAN, INC.". NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://marahoffman.com/', 0.60, false, 'migration:00761'),
  ('matethelabel', 'MATE the Label', ARRAY['mate the label','matethelabel','mate']::text[], ARRAY['organic cotton','loungewear','womenswear','clean']::text[], ARRAY['RN 157267']::text[],
   'RN 157267 is FTC-record sourced -- registrant "MATE the Label". NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://matethelabel.com/', 0.60, false, 'migration:00761'),
  ('norda', 'norda', ARRAY['norda','norda run']::text[], ARRAY['trail running','footwear','dyneema','canadian']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://nordarun.com/', 0.60, false, 'migration:00761'),
  ('olderbrother', 'Older Brother', ARRAY['older brother','olderbrother']::text[], ARRAY['natural dye','unisex','portland','sustainable']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://olderbrother.us/', 0.60, false, 'migration:00761'),
  ('pistola', 'Pistola', ARRAY['pistola','pistola denim']::text[], ARRAY['denim','womenswear','jeans','los angeles']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://pistoladenim.com/', 0.60, false, 'migration:00761'),
  ('stanray', 'Stan Ray', ARRAY['stan ray','stanray','stan''s']::text[], ARRAY['workwear','painter pants','fatigues','made in usa']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://stanray.com/', 0.60, false, 'migration:00761'),
  ('statecashmere', 'State Cashmere', ARRAY['state cashmere','statecashmere']::text[], ARRAY['cashmere','knitwear','basics','value']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://statecashmere.com/', 0.60, false, 'migration:00761'),
  ('unbound', 'Unbound Merino', ARRAY['unbound','unbound merino','unboundmerino']::text[], ARRAY['merino','travel','basics','menswear']::text[], ARRAY['RN 172558']::text[],
   'RN 172558 is FTC-record sourced -- registrant "Unbound Merino Properties LLC". NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://unboundmerino.com/', 0.60, false, 'migration:00761'),
  ('whimsyandrow', 'Whimsy + Row', ARRAY['whimsy + row','whimsy and row','whimsyandrow']::text[], ARRAY['sustainable','womenswear','deadstock','los angeles']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://whimsyandrow.com/', 0.60, false, 'migration:00761'),
  ('xeroshoes', 'Xero Shoes', ARRAY['xero','xero shoes','xeroshoes']::text[], ARRAY['footwear','barefoot','zero drop','minimalist']::text[], ARRAY[]::text[],
   'NO REGISTERED NUMBER: the FTC register returns nothing for this brand, which is a legitimate absence rather than a failed lookup. NOT RESEARCHED: tag eras, country patterns and authentication tells are empty because nobody has done that work, NOT because there is nothing to find. Colorways and the size run come from the brand''s own catalog.',
   'https://xeroshoes.com/', 0.60, false, 'migration:00761')
on conflict (brand_key) do nothing;

insert into public.brand_colorways
  (brand_key, color_name, aliases, hex, years, base_color, shade,
   source_url, confidence, verified, updated_by)
values

  ('astral', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://astraldesigns.com/', 0.75, false, 'migration:00761'),
  ('astral', 'Fire Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://astraldesigns.com/', 0.75, false, 'migration:00761'),
  ('astral', 'Gray', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://astraldesigns.com/', 0.75, false, 'migration:00761'),
  ('astral', 'Salty White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://astraldesigns.com/', 0.75, false, 'migration:00761'),
  ('astral', 'Silver Pine', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://astraldesigns.com/', 0.75, false, 'migration:00761'),
  ('astral', 'Sirius Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://astraldesigns.com/', 0.75, false, 'migration:00761'),
  ('astral', 'Space Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://astraldesigns.com/', 0.75, false, 'migration:00761'),
  ('astral', 'Water Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://astraldesigns.com/', 0.75, false, 'migration:00761'),
  ('crownnorthampton', 'All Black Calf', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'All White Calf', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Black Calf', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Black Calf Leather', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Black Horween Buffalo', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Black Horween Dearborn', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Black Kudu Suede', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Bracken Horween Dearborn', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Brown Calf', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Brown Horween Buffalo', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Brown Kudu Suede', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Burgundy', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'CORDOVAN BLACK 01', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'CORDOVAN NEUTRAL 02', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Caramel Horween Dearborn', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Chamois Cotton', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Deluxe Care Pack', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'For Cordovan', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Gaucho Naked Kudu', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Grey Calf', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Grey Horween Buffalo', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Horween Black Chromexcel', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Horween Brown Chromexcel', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Horween Ink Chromexcel', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Horween Natural Chromexcel', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Horween No8 Chromexcel', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Horween Sunflower Chromexcel', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Insoles', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Leopard Hair On', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Mad Dog', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Medium Brown', ARRAY[]::text[], NULL, NULL, 'Brown', 'Medium', 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Natural Beech Wood', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Natural Maple Wood', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Natural Oak Wood', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Navy Calf', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Navy Kudu Suede', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Neutral', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Nutmeg Naked Kudu', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Olive Calf Suede', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 1', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 10', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 11', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 12', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 13', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 14', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 15', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 16', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 17', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 18', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 19', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 2', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 20', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 21', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 22', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 23', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 24', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 25', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 26', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 27', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 28', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 3', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 4', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 5', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 6', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 7', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 8', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Piece 9', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Plaited', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Resole Service', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 10', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 11', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 13', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 14', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 15', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 16', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 20', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 22', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 25', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 26', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 29', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 33', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 39', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 40', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 47', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 48', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 5', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 7', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'SRE4 8', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Sand Calf', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Sand Kudu Suede', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Snuff Naked Kudu', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Sokoto Leather', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Sokoto Nubuck', ARRAY[]::text[], NULL, NULL, null, null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Tan Horween Buffalo', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'Tan Horween Dearborn', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'White Calf', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('crownnorthampton', 'White Calf Leather', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://www.crownnorthampton.com/', 0.55, false, 'migration:00761'),
  ('hunterbell', 'Amber Glen Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Bermuda Toile', ARRAY[]::text[], NULL, NULL, null, null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Coastal Conversation', ARRAY[]::text[], NULL, NULL, null, null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Coconut Sand Dot', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Deep Sea', ARRAY[]::text[], NULL, NULL, null, 'Dark', 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Glen Paisley', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Lost At Sea', ARRAY[]::text[], NULL, NULL, null, null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Morning Glory', ARRAY[]::text[], NULL, NULL, null, null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Pink Trellis', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Somers Shell Mint', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'Still Life Symphony', ARRAY[]::text[], NULL, NULL, null, null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('hunterbell', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://hunterbellnyc.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Acacia', ARRAY[]::text[], NULL, NULL, null, null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Azul', ARRAY[]::text[], NULL, NULL, null, null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Beige', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Brown', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Cacao', ARRAY[]::text[], NULL, NULL, null, null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Camel', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Caramel', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Coco', ARRAY[]::text[], NULL, NULL, null, null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Denim', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Ecru Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Heather Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Honey', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Honey Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Indian Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Indigo 12', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Indigo 2', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Indigo 6', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Iron 4', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Iron 8', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Light Denim', ARRAY[]::text[], NULL, NULL, 'Blue', 'Light', 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Shellac 2', ARRAY[]::text[], NULL, NULL, null, null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Tabaquin', ARRAY[]::text[], NULL, NULL, null, null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'Undyed', ARRAY[]::text[], NULL, NULL, null, null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('industryofallnations', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://industryofallnations.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'BONE', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'ESPRESSO', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'FOREST', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'HEATHER GREY', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'HEATHER OAT', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'JET BLACK', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'MIDNIGHT', ARRAY[]::text[], NULL, NULL, 'Black', 'Dark', 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'MINERAL', ARRAY[]::text[], NULL, NULL, null, null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'MOCHA', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'MULBERRY', ARRAY[]::text[], NULL, NULL, null, null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'PACIFIC STRIPE', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'PEBBLE', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'SAND', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('matethelabel', 'TRUE WHITE', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://matethelabel.com/', 0.75, false, 'migration:00761'),
  ('norda', 'Abyss', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Almond', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Alpine White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Ash', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Ash Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Astral', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Bark', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Cinder', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Comet', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Cream', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Dark Sage', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Grey Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Hinoki', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Horizon', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Ice Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Kanagawa', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Kingfisher', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'LTD Edition/Orange', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Laser', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Loam', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Maple', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Moonbeam', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Moss', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Multicolor', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Neve', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Nylon', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Oak', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Off White', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Oud', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Pewter', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Pink Fudge', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Pitch Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'RZ Edition/Fireclay', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Rose', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Sage', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Scoria', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Sea Salt', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Serpentine', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Sky', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Smoky Quartz', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Star Anise', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Stealth Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Stone', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Strato', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Summit Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Thistle', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Travertine', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'White Gum', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'Zephyr', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'gnorda/Aqua', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'gnorda/Kangaroo', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'gnorda/Moon Rock', ARRAY[]::text[], NULL, NULL, null, null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'gnorda/Plaza Taupe', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'norda x CIMORO/White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('norda', 'norda x Raide/Sage', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://nordarun.com/', 0.55, false, 'migration:00761'),
  ('olderbrother', '"Hand-Me Down"', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', '"Hand-Me-Down"', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Black Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Black Indigo Check', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Chambray', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Clay', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Clay Splatter', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Contrast Denim', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Dark Denim', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Denim', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Denim Contrast', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Denim Tonal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Gold Clay', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Hand Me Down', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Hand Me Downs', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Hand-Me-Down', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Hand-Me-Downs', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Indigo Tint', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Kakishibu', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Mud Clay', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Mud Clay Check', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Mud Clay Splatter', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Mud Clay Wash', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Mud Mix', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Ochre', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Plant Material', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Pomace Stone', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Powder Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Red Clay', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Red Clay Check', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Stonewash', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Stonewash Denim', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'Waxed Windbreaker', ARRAY[]::text[], NULL, NULL, null, null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('olderbrother', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://olderbrother.us/', 0.55, false, 'migration:00761'),
  ('pistola', 'Acai', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Aegean', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'After Hours', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Ami', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Antique White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Aries', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Artisan', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Attitude', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Azalea', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Berkeley', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Bistro', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Black Vanilla Ice', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Blissful', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Blizzard', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Blue Cloud', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Blue Depths', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Blue Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Blush', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Bowie', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Bramble', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Break', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Bristol Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Brooklyn', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Bruna', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Bruna Black Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Cabernet', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Calling', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Camel', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Cameo Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Care Free', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Celeste', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Chateau', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Cherry Wine', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Chevron', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Chili', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Ciel', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Claret', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Coastal Fade', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Coral Rose', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Cosmic', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Cultivate', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Daring', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Dark Teal', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Day Glow', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Deep Crimson', ARRAY[]::text[], NULL, NULL, 'Red', 'Dark', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Deep Moss', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Deep Teal', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Desert Egret', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Dolce Vita Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Dune', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Dusk', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Ecru', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Egret', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Egyptian Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Egyptian Blue Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Escape', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Eternity', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Expanse', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Fade To Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Flourish', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Focus', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'French Riviera', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Great Falls', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Green Blue Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Hazy', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Heartfelt', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Heather Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Hidden Gem', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Honey', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Hot Toddy', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Hurst Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Ice Pink', ARRAY[]::text[], NULL, NULL, 'Pink', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Illusion', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Inkwell', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Ivory Luster', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Java', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Java Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Laguna', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Le Blanc', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Legend', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Light Turmeric', ARRAY[]::text[], NULL, NULL, null, 'Light', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Light Turmeric Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', 'Light', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Linden', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Lindt', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Lovina Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Luna', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Luxe White Vintage', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Magenta Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Mantis', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Maraschino', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Maritime Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Maroon Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Meadow', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Mellow', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Mercury', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Metropolis', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Midnight Haze', ARRAY[]::text[], NULL, NULL, 'Black', 'Dark', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Mirage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Misted Eve', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Mocha', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Moonlit Violet', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Moonwave', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Nautical', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Navy Ship', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Navy White Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Negroni', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Night Club', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Night Flight', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Nightfall', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Nile', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Noir', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Normandy Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Off White', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Old Blues', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Onyx', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Optic White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Oyster Shell', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Pale Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', 'Light', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Paper White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Peacoat', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Peanut Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Penthouse', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Perspective', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Postcards', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Postcards Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Racer Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Racer Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Radiant Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Rhythm Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'River', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Road Trip', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Roche', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Rosette', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Rosslyn', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Sage Egret Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Sail Away', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Savvy Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Sea Haze', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Sea Salt', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Sequoia', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Serendipity', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Serpentine Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Skyscraper', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Slate Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Soft Moss', ARRAY[]::text[], NULL, NULL, 'Green', 'Light', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Soft White', ARRAY[]::text[], NULL, NULL, 'White', 'Light', 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Soho', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Solina', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Sorensen', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Spark', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Spectacle', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Star Studded', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Stardew', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Starstruck', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Stellar', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Stormy', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Sun-Kissed Vintage', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Sycamore', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Tannin Ecru Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Tealwood Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Terrace', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Vert Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Vibes', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Vivid Moss', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Vivid White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Washed Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Waves', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Wheat', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Whisper', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'White Oxblood', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'White Red Stripe', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Wilcox', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Wild Heart', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Windswept', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Wintergreen', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Woodland', ARRAY[]::text[], NULL, NULL, null, null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Yellow', ARRAY[]::text[], NULL, NULL, 'Yellow', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Zebra', ARRAY[]::text[], NULL, NULL, 'Multicolor', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('pistola', 'Zebra Silver', ARRAY[]::text[], NULL, NULL, 'Silver', null, 'https://pistoladenim.com/', 0.55, false, 'migration:00761'),
  ('unbound', 'Almond', ARRAY[]::text[], NULL, NULL, null, null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Amber', ARRAY[]::text[], NULL, NULL, 'Orange', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Azure', ARRAY[]::text[], NULL, NULL, null, null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Black', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Cadet Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Crimson', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Dark Olive', ARRAY[]::text[], NULL, NULL, 'Green', 'Dark', 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Dusty Purple', ARRAY[]::text[], NULL, NULL, 'Purple', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Earth', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Fossil', ARRAY[]::text[], NULL, NULL, null, null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Harbor Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Heather Camel', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Heather Charcoal', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Heather Earth', ARRAY[]::text[], NULL, NULL, 'Brown', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Heather Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Heather Oat', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Ivory', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Merlot', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Mulberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Natural', ARRAY[]::text[], NULL, NULL, 'Ivory', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Natural White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Pine Green', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Royal Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Sail Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Sand', ARRAY[]::text[], NULL, NULL, 'Beige', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Sierra Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Stout', ARRAY[]::text[], NULL, NULL, null, null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Tan', ARRAY[]::text[], NULL, NULL, 'Tan', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'Vintage Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', 'White', ARRAY[]::text[], NULL, NULL, 'White', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Cobalt', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Dark Teal', ARRAY[]::text[], NULL, NULL, 'Blue', 'Dark', 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Dark Violet', ARRAY[]::text[], NULL, NULL, 'Purple', 'Dark', 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Dusty Teal', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Forest', ARRAY[]::text[], NULL, NULL, 'Green', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Fossil', ARRAY[]::text[], NULL, NULL, null, null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Harbor Grey', ARRAY[]::text[], NULL, NULL, 'Gray', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Iceberg', ARRAY[]::text[], NULL, NULL, null, null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Merlot', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Moonlight Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Mulberry', ARRAY[]::text[], NULL, NULL, null, null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Navy', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Ruby Waves', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Sail Blue', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Sedona', ARRAY[]::text[], NULL, NULL, null, null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Sierra Red', ARRAY[]::text[], NULL, NULL, 'Red', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('unbound', '_Vintage Indigo', ARRAY[]::text[], NULL, NULL, 'Blue', null, 'https://unboundmerino.com/', 0.75, false, 'migration:00761'),
  ('xeroshoes', 'Big Kids', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Coastal Treasures', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Complete', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Gold Chain', ARRAY[]::text[], NULL, NULL, 'Gold', null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Good Vibes', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Jet Set', ARRAY[]::text[], NULL, NULL, 'Black', null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Knit', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Leather', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Little Kids', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Men', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Unisex', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761'),
  ('xeroshoes', 'Women', ARRAY[]::text[], NULL, NULL, null, null, 'https://xeroshoes.com/', 0.55, false, 'migration:00761')
on conflict (brand_key, color_name) do nothing;

-- US-1108 self-record footer.
insert into public.applied_migrations (version) values ('00761') on conflict do nothing;
