// Is a migration actually applied to production? Ask the database, not the file.
//
// PENDING_MIGRATIONS.md is a hand-edited marker, and it has gone stale in both
// directions: scripts/held-migration-gate.mjs exists because migrations reached
// origin while still marked HELD, and 00674 was the reverse - applied to prod
// while the file, the gate and the session-start hook all still called it HELD
// and BLOCKING. A marker maintained by hand is not evidence about a database.
//
// THE PROOF IS THE SELF-RECORD FOOTER, NOT THE SCHEMA. Every migration ends
// with `insert into public.applied_migrations (version) values ('NNNNN')`, and
// that is the LAST statement in the file. So a row for NNNNN means every
// statement above it ran. Checking instead that some column the migration adds
// now exists proves only that the migration got that far, which is exactly the
// mistake this script was written to stop repeating - a column shows up in
// PostgREST's OpenAPI document whether or not the CHECK constraint two
// statements later ever ran.
//
// READ-ONLY. It writes nothing.
//
//   deno run --allow-net --allow-env --allow-read scripts/check-prod-migration.ts [00674 ...]
//
// With no arguments it reports every migration file in the repo that prod has
// no record of.
//
// TWO WAYS TO GET THE ANSWER, AND THE SECOND NEEDS NO CREDENTIALS (US-2832).
//
//   1. SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY: read public.applied_migrations
//      directly. Complete - it sees every recorded version, including pre-
//      footer-era ones and rows no build knows about.
//
//   2. No key: fall back to the edge's own /health/ready. That endpoint reads
//      applied_migrations through the service-role client and publishes the SET
//      DIFFERENCE against the manifest the running build ships, as `missing`.
//      So an ABSENT `missing` key is a positive statement that every version in
//      that manifest has a row - which settles a specific version without any
//      secret at all.
//
//      This used to exit(1) with "refusing to report a false negative" the
//      moment the key was unusable, which is right about a row read and wrong as
//      a final answer: a conclusive public answer existed the whole time and
//      nobody was reaching for it. US-2832 is exactly the story where that cost
//      something - "is the listings.draft_id repair recorded on prod" sat as an
//      operator step while /health/ready had been answering it for weeks.
//
// The fallback is honest about its ceiling. It can only speak for versions the
// DEPLOYED build's manifest covers, and it says `UNKNOWN` with a reason for the
// rest rather than guessing. A pre-footer-era migration (below 00254) is never
// in any manifest, so the completeness set cannot see it - that blind spot IS
// the 00134 blind spot this whole story came out of, and naming it is the point.

import { createClient } from "@supabase/supabase-js";
import { EXPECTED_SCHEMA_VERSION } from "../src/lib/schema-version.ts";
import { EXPECTED_MIGRATIONS, FOOTER_ERA_START } from "../src/lib/migration-manifest.ts";

// Migrations that are ABSENT FROM PROD ON PURPOSE. Without this, the sweep
// reports a permanent one-line gap that everybody learns to scroll past, which
// is how a real gap gets missed. Listed with the reason, so the exception is
// auditable rather than folklore.
const DELIBERATELY_UNAPPLIED: Record<string, string> = {
  "00527":
    "owner decision, permanent: its blanket REVOKE segfaults the DB on a denied " +
    "anon/authenticated call. US-2282's fix is a per-function authorization " +
    "check instead. Do not apply.",
};

const DEFAULT_HEALTH_URL = "https://functions.gradethread.com/health/ready";

/** The `schema` block of /health/ready. Shape owned by routes/health.ts. */
export interface HealthSchema {
  expected: string;
  applied: string | null;
  status: string;
  /** Manifest versions with NO applied_migrations row. Absent when the set is empty. */
  missing?: string[];
  /** Versions the DB records that this build has no file for. */
  unexpected?: string[];
  /** False when the applied SET could not be read. Absent means it was read. */
  complete?: boolean;
}

export type Verdict = "applied" | "not-applied" | "unknown";

export interface VerdictResult {
  verdict: Verdict;
  why: string;
}

/**
 * What /health/ready alone can say about one version.
 *
 * `manifest` is THIS checkout's manifest. The deployed build's manifest is not
 * published, but it is generated by the same script from the same directory, so
 * it is the footer-era files up to its own `expected`. Migrations are only ever
 * appended (never renumbered below an already-deployed maximum), so
 * "in this manifest AND <= deployed expected" is the deployed manifest. That
 * assumption is stated here rather than hidden: if it ever stops holding, this
 * function is the thing that goes wrong.
 */
export function verdictFromHealth(
  version: string,
  schema: HealthSchema | undefined,
  manifest: readonly string[] = EXPECTED_MIGRATIONS,
): VerdictResult {
  if (!schema) {
    return { verdict: "unknown", why: "/health/ready published no schema block" };
  }
  if (schema.complete === false) {
    return {
      verdict: "unknown",
      why: "the edge could not read the applied SET (complete:false) - not a claim of health",
    };
  }
  const missing = schema.missing ?? [];
  if (missing.includes(version)) {
    return {
      verdict: "not-applied",
      why: "named in /health/ready's `missing` set - the deployed build expects it and the DB has no row",
    };
  }
  if (version < FOOTER_ERA_START) {
    return {
      verdict: "unknown",
      why:
        `pre-footer-era (below ${FOOTER_ERA_START}): it carries no self-record footer, so no ` +
        `manifest has ever covered it and the completeness set cannot see it. This is the ` +
        `00134 blind spot. Only a service-role read of applied_migrations, or ` +
        `scripts/prod-schema-audit.sql, can speak for it.`,
    };
  }
  if (!manifest.includes(version)) {
    return {
      verdict: "unknown",
      why: "not in this checkout's manifest, so nothing here knows whether the deployed build tracks it",
    };
  }
  if (version > schema.expected) {
    return {
      verdict: "unknown",
      why:
        `the deployed build expects ${schema.expected}, which is older than ${version} - ` +
        `its manifest cannot contain this version, so its silence means nothing`,
    };
  }
  return {
    verdict: "applied",
    why:
      `in the deployed build's manifest (<= its expected ${schema.expected}) and absent from ` +
      `its \`missing\` set, so applied_migrations has a row for it`,
  };
}

/** Read /health/ready. Returns undefined on any transport or parse failure. */
async function readHealth(url: string): Promise<HealthSchema | undefined> {
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), 25_000);
  try {
    const res = await fetch(url, { signal: ctl.signal });
    const body = await res.json() as { schema?: HealthSchema };
    return body.schema;
  } catch (err) {
    console.error(`! ${url} unreadable: ${err instanceof Error ? err.message : String(err)}`);
    return undefined;
  } finally {
    clearTimeout(timer);
  }
}

/** Every NNNNN prefix under supabase/migrations, sorted. */
async function migrationVersions(): Promise<string[]> {
  // Resolved from import.meta.url so it does not depend on the working
  // directory, and handed to Deno.readDir as a URL rather than converted to a
  // string. `new URL(...).pathname` is the trap here: it keeps a leading slash
  // before the drive letter on Windows and produces a different shape on Linux,
  // so the hand-rolled conversion works on the machine you wrote it on and
  // fails in CI. Deno's filesystem APIs take a URL directly.
  const dir = new URL("../../../supabase/migrations/", import.meta.url);
  const files: string[] = [];
  for await (const entry of Deno.readDir(dir)) {
    const m = /^(\d{5})_/.exec(entry.name);
    if (entry.isFile && m?.[1]) files.push(m[1]);
  }
  files.sort();
  return files;
}

/** The service-role path: read applied_migrations directly. */
async function runWithKey(url: string, key: string, asked: string[]): Promise<number> {
  const db = createClient(url, key, { auth: { persistSession: false } });
  const { data, error } = await db.from("applied_migrations").select("version");
  if (error) {
    console.error(`! applied_migrations unreadable: ${error.message}`);
    return 1;
  }
  const applied = new Set(
    (data ?? []).map((r) => String((r as { version: string }).version)),
  );
  console.log(`${url} records ${applied.size} applied migration(s).`);
  console.log(`this build expects EXPECTED_SCHEMA_VERSION = ${EXPECTED_SCHEMA_VERSION}`);

  if (asked.length > 0) {
    let missing = 0;
    for (const v of asked) {
      const ok = applied.has(v);
      if (!ok) missing += 1;
      console.log(`  ${ok ? "APPLIED" : "NOT APPLIED"}  ${v}`);
    }
    return missing > 0 ? 1 : 0;
  }

  // No arguments: everything in the repo that prod has no record of.
  const files = await migrationVersions();
  const gaps = files.filter((v) => !applied.has(v));
  const real = gaps.filter((v) => !DELIBERATELY_UNAPPLIED[v]);
  const expected = gaps.filter((v) => DELIBERATELY_UNAPPLIED[v]);
  console.log(`${files.length} migration file(s) on disk`);

  // THE OTHER DIRECTION, which the gap list alone cannot show: versions the
  // database records that no file in this build produces. That is what a
  // rollback leaves behind (00638 dropped what earlier migrations built and
  // removed their applied_migrations rows), and it is also what a database ahead
  // of the checkout looks like. Reported, not failed - an older checkout is a
  // normal state, and making it an error would train people to ignore the exit
  // code.
  const fileSet = new Set(files);

  // Some rows carry an extra leading zero - '000355' alongside '00355', for
  // three versions, both forms recorded. They are duplicate records of a
  // migration that did run, not evidence of anything, and left unexplained they
  // put a permanent three-line complaint on a report whose whole value is that
  // its output is normally empty. Normalised to the five-digit form before
  // comparing, and counted separately so the oddity stays visible without being
  // alarming.
  const fiveDigit = (v: string) => v.replace(/^0+(\d{5})$/, "$1");
  const miscounted = [...applied]
    .filter((v) => !fileSet.has(v) && fileSet.has(fiveDigit(v)))
    .sort();
  const orphans = [...applied]
    .filter((v) => !fileSet.has(v) && !fileSet.has(fiveDigit(v)))
    .sort();

  if (miscounted.length > 0) {
    console.log(
      `  (${miscounted.length} row(s) recorded with an extra leading zero, ` +
        `duplicating a version that did run: ${miscounted.join(", ")})`,
    );
  }
  if (orphans.length > 0) {
    console.log(
      `\n${orphans.length} version(s) recorded on prod with NO migration file here: ${
        orphans.join(", ")
      }`,
    );
    console.log("  (a rollback, or this checkout is behind the database)");
  }

  for (const v of expected) {
    console.log(`  (expected gap) ${v} - ${DELIBERATELY_UNAPPLIED[v]}`);
  }
  if (real.length === 0) {
    console.log("prod has a record of every migration that is meant to be applied.");
    return 0;
  }
  console.log(`\n${real.length} NOT recorded on prod:`);
  for (const v of real) console.log(`  ${v}`);
  return 1;
}

/** The credential-free path: infer from /health/ready's completeness set. */
async function runWithoutKey(healthUrl: string, asked: string[]): Promise<number> {
  const schema = await readHealth(healthUrl);
  console.log(`${healthUrl} reports schema ${JSON.stringify(schema ?? null)}`);
  console.log(`this checkout expects EXPECTED_SCHEMA_VERSION = ${EXPECTED_SCHEMA_VERSION}`);

  const targets = asked.length > 0
    ? asked
    // No arguments: the only thing the public path can enumerate is what the
    // deployed build already named as missing. It cannot sweep the directory,
    // because it has no way to speak for anything outside that build's manifest.
    : (schema?.missing ?? []);

  if (asked.length === 0) {
    if (!schema) {
      console.log("no schema block - nothing can be established without credentials.");
      return 2;
    }
    if (schema.complete === false) {
      console.log("the edge could not read the applied SET (complete:false) - not a claim of health.");
      return 2;
    }
    if (targets.length === 0) {
      console.log(
        `NOTHING MISSING: every version in the deployed build's manifest (footer-era ` +
          `${FOOTER_ERA_START}..${schema.expected}) has an applied_migrations row.`,
      );
      console.log(
        `  This cannot speak for anything below ${FOOTER_ERA_START} - those carry no footer ` +
          `and no manifest covers them. Run scripts/prod-schema-audit.sql for those.`,
      );
      return 0;
    }
  }

  let bad = 0;
  let unknown = 0;
  for (const v of targets) {
    const { verdict, why } = verdictFromHealth(v, schema);
    if (verdict === "not-applied") bad += 1;
    if (verdict === "unknown") unknown += 1;
    console.log(`  ${verdict.toUpperCase().padEnd(11)} ${v}  - ${why}`);
  }
  if (bad > 0) return 1;
  return unknown > 0 ? 2 : 0;
}

// --- self-test ---------------------------------------------------------------
//
// Every case below is a verdict the fallback has to get right, and each one is a
// shape that has actually happened to this repo. Run it with no network and no
// credentials:
//
//   deno run --allow-env scripts/check-prod-migration.ts --self-test
//
// --allow-env is for the IMPORTS, not for this function: schema-version.ts pulls
// in env.ts, which reads config at module load. Nothing here touches the network.

function selfTest(): number {
  const manifest = ["00254", "00660", "00784"];
  const base: HealthSchema = { expected: "00784", applied: "00785", status: "ahead" };
  const cases: Array<[string, VerdictResult["verdict"], HealthSchema | undefined, string]> = [
    // The live 2026-09-11 shape: no `missing` key at all.
    ["00660", "applied", base, "covered version, empty missing set"],
    // The US-2620 shape: a hole under the maximum.
    ["00660", "not-applied", { ...base, missing: ["00660"] }, "named in missing"],
    // The 00134 blind spot - the entire reason this story exists.
    ["00134", "unknown", base, "pre-footer-era"],
    // A migration this checkout has and the deployed build does not.
    ["00790", "unknown", base, "newer than the deployed expected"],
    // Read failure must never render as clean.
    ["00660", "unknown", { ...base, complete: false }, "complete:false"],
    // No schema block at all (an old build, or a shape change).
    ["00660", "unknown", undefined, "no schema block"],
  ];
  let failed = 0;
  for (const [version, want, schema, label] of cases) {
    const got = verdictFromHealth(version, schema, manifest);
    const ok = got.verdict === want;
    if (!ok) failed += 1;
    console.log(`  ${ok ? "ok  " : "FAIL"} ${label}: ${version} -> ${got.verdict} (want ${want})`);
  }
  // A version that is in the manifest but NOT below the footer era and NOT
  // above expected must never come back unknown - that would make every answer
  // useless while still exiting 0.
  const positive = verdictFromHealth("00784", base, manifest);
  if (positive.verdict !== "applied") {
    failed += 1;
    console.log(`  FAIL boundary: 00784 == expected must be applied, got ${positive.verdict}`);
  } else {
    console.log("  ok   boundary: a version equal to the deployed expected is covered");
  }
  console.log(failed === 0 ? "self-test: 7 passed" : `self-test: ${failed} FAILED`);
  return failed === 0 ? 0 : 1;
}

// --- main --------------------------------------------------------------------

if (Deno.args.includes("--self-test")) {
  Deno.exit(selfTest());
}

const asked = Deno.args.filter((a) => /^\d{5}$/.test(a));
const url = Deno.env.get("SUPABASE_URL")?.trim();
const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")?.trim();
const healthUrl = Deno.env.get("EDGE_HEALTH_URL")?.trim() || DEFAULT_HEALTH_URL;

// A key that is not header-safe fails per query rather than at connect time, so
// supabase-js reports it as "this table is unreadable" and a caller that treats
// an unreadable table as "no rows" prints a confident, wrong, empty answer. So
// the row read is refused - but the public path still runs, because it is
// evidence rather than a guess.
function keyIsUsable(k: string | undefined): { ok: boolean; why: string } {
  if (!k) return { ok: false, why: "SUPABASE_SERVICE_ROLE_KEY is not set" };
  const badChar = /[^\x21-\x7e]/.exec(k);
  if (badChar || k.split(".").length !== 3 || k.length < 100) {
    return {
      ok: false,
      why: `SUPABASE_SERVICE_ROLE_KEY is not a usable JWT (${k.length} characters, ` +
        `${k.split(".").length} segments${
          badChar ? `, bad character at index ${badChar.index}` : ""
        })`,
    };
  }
  return { ok: true, why: "" };
}

const usable = keyIsUsable(key);
if (url && usable.ok && key) {
  Deno.exit(await runWithKey(url, key, asked));
}
console.log(
  `${usable.why || "SUPABASE_URL is not set"} - reading the deployed build's completeness set instead.`,
);
console.log("(read-only, no credentials; see the header for what this can and cannot settle)");
Deno.exit(await runWithoutKey(healthUrl, asked));
